#pragma once

#include <math.h>
#include <stdint.h>
#include <string.h>

// AI: below section was generated by an AI

struct DownbeatEstimate {
  bool locked = false;
  uint8_t beatInBar = 0;
  uint8_t confidence = 0;
  uint8_t downbeatSlot = 0;
  uint16_t observations = 0;
  uint16_t revision = 0;
};

// Assigns accepted beat onsets to one of four possible 4/4 bar alignments.
// This is the beat-synchronous filtering idea used by Metricon's StreamingBarTracker,
// reduced to the fixed 4/4 meter used by Tubes:
// https://pypi.org/project/metricon/
class DownbeatTracker {
  public:
    static constexpr uint8_t BEATS_PER_BAR = 4;

    void reset() {
      memset(slotCue, 0, sizeof(slotCue));
      memset(slotObservations, 0, sizeof(slotObservations));
      meanKick = 0.0f;
      meanSnare = 0.0f;
      meanNovelty = 0.0f;
      observations = 0;
      lastOrdinal = 0;
      ordinalReady = false;
      candidateSlot = INVALID_SLOT;
      candidateAge = 0;
      lockedSlot = INVALID_SLOT;
      revision = 0;
      confidence = 0;
    }

    // Adds the spectral evidence belonging to one accepted beat. `beatOrdinal`
    // may skip values when the onset detector misses beats; its low two bits
    // preserve the correct candidate bar position across those gaps.
    void observe(uint32_t beatOrdinal, float kick, float snare, float novelty) {
      if (ordinalReady && beatOrdinal < lastOrdinal) {
        reset();
      } else if (ordinalReady && beatOrdinal - lastOrdinal > MAXIMUM_BEAT_GAP) {
        reset();
      }
      lastOrdinal = beatOrdinal;
      ordinalReady = true;

      if (!observations) {
        meanKick = kick;
        meanSnare = snare;
        meanNovelty = novelty;
      }

      float kickRelative = relativeAccent(kick, meanKick);
      float snareRelative = relativeAccent(snare, meanSnare);
      float noveltyRelative = relativeAccent(novelty, meanNovelty);

      // Beat 1 in electronic music is commonly a relatively strong low-frequency
      // onset accompanied by a broader arrangement change. A relative snare peak
      // is weak contrary evidence, helping reject beats 2 and 4.
      float cue = 0.55f * kickRelative
          + 0.35f * noveltyRelative
          - 0.20f * positive(snareRelative);
      cue = clamp(cue, -2.0f, 2.0f);

      uint8_t slot = beatOrdinal & (BEATS_PER_BAR - 1);
      uint8_t count = slotObservations[slot];
      float weight = count < INITIAL_SLOT_SAMPLES
          ? 1.0f / (count + 1.0f)
          : SLOT_ADAPTATION;
      slotCue[slot] += (cue - slotCue[slot]) * weight;
      if (count < UINT8_MAX)
        slotObservations[slot]++;
      if (observations < UINT16_MAX)
        observations++;

      updateMean(meanKick, kick);
      updateMean(meanSnare, snare);
      updateMean(meanNovelty, novelty);
      evaluateAlignment();
    }

    DownbeatEstimate estimate(uint32_t beatOrdinal) const {
      DownbeatEstimate result;
      result.locked = lockedSlot != INVALID_SLOT;
      result.downbeatSlot = result.locked ? lockedSlot : 0;
      result.beatInBar = result.locked
          ? uint8_t((beatOrdinal - lockedSlot) & (BEATS_PER_BAR - 1))
          : 0;
      result.confidence = confidence;
      result.observations = observations;
      result.revision = revision;
      return result;
    }

  private:
    static constexpr uint8_t INVALID_SLOT = UINT8_MAX;
    static constexpr uint8_t INITIAL_SLOT_SAMPLES = 4;
    static constexpr uint8_t REQUIRED_CANDIDATE_BEATS = 8;
    static constexpr uint8_t REQUIRED_SWITCH_BEATS = 16;
    static constexpr uint8_t MAXIMUM_BEAT_GAP = 16;
    static constexpr float SLOT_ADAPTATION = 0.20f;
    static constexpr float MEAN_ADAPTATION = 1.0f / 24.0f;
    static constexpr float MINIMUM_CUE = 0.10f;
    static constexpr float MINIMUM_MARGIN = 0.16f;
    static constexpr float SWITCH_MARGIN = 0.35f;

    float slotCue[BEATS_PER_BAR] = {0.0f};
    uint8_t slotObservations[BEATS_PER_BAR] = {0};
    float meanKick = 0.0f;
    float meanSnare = 0.0f;
    float meanNovelty = 0.0f;
    uint16_t observations = 0;
    uint32_t lastOrdinal = 0;
    bool ordinalReady = false;
    uint8_t candidateSlot = INVALID_SLOT;
    uint8_t candidateAge = 0;
    uint8_t lockedSlot = INVALID_SLOT;
    uint16_t revision = 0;
    uint8_t confidence = 0;

    static float positive(float value) {
      return value > 0.0f ? value : 0.0f;
    }

    static float clamp(float value, float minimum, float maximum) {
      if (value < minimum) return minimum;
      if (value > maximum) return maximum;
      return value;
    }

    // Expresses an onset relative to the recent song level, keeping the bar
    // decision stable across microphone gain and overall loudness changes.
    static float relativeAccent(float value, float mean) {
      float denominator = mean > 1.0f ? mean : 1.0f;
      return clamp((value - mean) / denominator, -1.0f, 3.0f);
    }

    static void updateMean(float& mean, float value) {
      mean += (value - mean) * MEAN_ADAPTATION;
    }

    bool allSlotsReady() const {
      for (uint8_t slot = 0; slot < BEATS_PER_BAR; slot++)
        if (slotObservations[slot] < INITIAL_SLOT_SAMPLES)
          return false;
      return true;
    }

    // Requires a persistent winner before locking, and substantially stronger
    // contrary evidence before changing an existing bar alignment.
    void evaluateAlignment() {
      if (!allSlotsReady())
        return;

      uint8_t best = 0;
      uint8_t second = 1;
      if (slotCue[second] > slotCue[best]) {
        best = 1;
        second = 0;
      }
      for (uint8_t slot = 2; slot < BEATS_PER_BAR; slot++) {
        if (slotCue[slot] > slotCue[best]) {
          second = best;
          best = slot;
        } else if (slotCue[slot] > slotCue[second]) {
          second = slot;
        }
      }

      float margin = slotCue[best] - slotCue[second];
      confidence = uint8_t(clamp(margin * 320.0f, 0.0f, 255.0f));
      bool credible = slotCue[best] >= MINIMUM_CUE && margin >= MINIMUM_MARGIN;
      if (!credible) {
        candidateSlot = INVALID_SLOT;
        candidateAge = 0;
        return;
      }

      if (best != candidateSlot) {
        candidateSlot = best;
        candidateAge = 1;
      } else if (candidateAge < UINT8_MAX) {
        candidateAge++;
      }

      if (lockedSlot == INVALID_SLOT) {
        if (candidateAge >= REQUIRED_CANDIDATE_BEATS) {
          lockedSlot = best;
          revision++;
        }
        return;
      }

      if (best == lockedSlot) {
        candidateAge = REQUIRED_SWITCH_BEATS;
        return;
      }

      float lockedMargin = slotCue[best] - slotCue[lockedSlot];
      if (lockedMargin >= SWITCH_MARGIN && candidateAge >= REQUIRED_SWITCH_BEATS) {
        lockedSlot = best;
        revision++;
      }
    }
};

// AI: end
