#pragma once

#include <stdint.h>

// AI: below section was generated by an AI
// Preserves Tubes' existing inclusive 0-255 chance contract for every effect source.
constexpr bool effectChanceAccepts(uint8_t chance, uint8_t roll) {
  return roll <= chance;
}
// AI: end
