#pragma once

#include <stdint.h>
#include <string.h>

#include "device_report_protocol.h"
#include "generated/update_contract_generated.h"

// AI: below section was generated by an AI
// Internal admission contract only. This structure is deliberately not packed,
// serialized, or assigned a mesh action key; Steve's wire protocol remains the
// authority for how these facts are eventually exchanged.
enum FirmwareChipFamily : uint8_t {
  FirmwareChipUnknown = 0,
  FirmwareChipEsp32 = 1,
  FirmwareChipEsp32C3 = 2,
  FirmwareChipEsp32S3 = 3,
};

enum FirmwareFlashMode : uint8_t {
  FirmwareFlashModeUnknown = 0,
  FirmwareFlashModeDio = 1,
  FirmwareFlashModeQio = 2,
  FirmwareFlashModeOpi = 3,
};

struct FirmwareTargetContract {
  CanonicalTargetId targetId = CanonicalTargetUnknown;
  uint8_t hardwareFamily = TubeHardwareUnknown;
  uint8_t chipFamily = FirmwareChipUnknown;
  uint8_t flashMode = FirmwareFlashModeUnknown;
  uint32_t flashSizeBytes = 0;
  uint8_t otaSlotCount = 0;
  CanonicalOtaSlotRecord otaSlots[CANONICAL_MAX_OTA_SLOTS] = {};
  uint8_t inactiveOtaSlot = CANONICAL_MAX_OTA_SLOTS;
  uint8_t partitionTableSha256[32] = {0};
};

// Projects generated build-time constants without claiming runtime slot
// evidence. The returned static target is intentionally receiver-incomplete.
// Hardware family remains the existing device-report vocabulary until Steve's
// additive identity packet defines a canonical Waveshare value on main.
inline FirmwareTargetContract firmwareStaticTargetFromCanonical(
    const CanonicalTargetRecord& canonical,
    uint8_t hardwareFamily
) {
  FirmwareTargetContract target;
  target.targetId = canonical.targetId;
  target.hardwareFamily = hardwareFamily;
  target.chipFamily = canonical.chipFamily;
  target.flashMode = canonical.flashMode;
  target.flashSizeBytes = canonical.flashSizeBytes;
  target.otaSlotCount = canonical.otaSlotCount;
  memcpy(target.otaSlots, canonical.otaSlots, sizeof(target.otaSlots));
  memcpy(target.partitionTableSha256, canonical.partitionTableSha256,
      sizeof(target.partitionTableSha256));
  return target;
}

enum FirmwareTargetMatch : uint8_t {
  FirmwareTargetMatchExact = 0,
  FirmwareTargetUnknown,
  FirmwareTargetHardwareMismatch,
  FirmwareTargetChipMismatch,
  FirmwareTargetFlashModeMismatch,
  FirmwareTargetFlashSizeMismatch,
  FirmwareTargetPartitionMismatch,
  FirmwareTargetOtaSlotMismatch,
};

inline bool firmwareTargetHasPartitionIdentity(const FirmwareTargetContract& target) {
  for (uint8_t value : target.partitionTableSha256) {
    if (value != 0)
      return true;
  }
  return false;
}

inline bool firmwareStaticTargetIsKnown(const FirmwareTargetContract& target) {
  return target.targetId != CanonicalTargetUnknown
      && target.hardwareFamily != TubeHardwareUnknown
      && target.chipFamily != FirmwareChipUnknown
      && target.flashMode != FirmwareFlashModeUnknown
      && target.flashSizeBytes > 0
      && target.otaSlotCount > 0
      && target.otaSlotCount <= CANONICAL_MAX_OTA_SLOTS
      && firmwareTargetHasPartitionIdentity(target);
}

// Applies verified receiver runtime evidence to a static target. Callers must
// obtain inactiveOtaSlot from partition inspection; no slot is inferred.
inline bool firmwareReceiverTargetFromStatic(
    const FirmwareTargetContract& staticTarget,
    uint8_t inactiveOtaSlot,
    FirmwareTargetContract& receiverTarget
) {
  receiverTarget = FirmwareTargetContract();
  if (!firmwareStaticTargetIsKnown(staticTarget)
      || inactiveOtaSlot >= staticTarget.otaSlotCount
      || staticTarget.otaSlots[inactiveOtaSlot].sizeBytes == 0)
    return false;
  receiverTarget = staticTarget;
  receiverTarget.inactiveOtaSlot = inactiveOtaSlot;
  return true;
}

inline bool firmwareTargetIsKnown(const FirmwareTargetContract& target) {
  return firmwareStaticTargetIsKnown(target)
      && target.inactiveOtaSlot < target.otaSlotCount
      && target.otaSlots[target.inactiveOtaSlot].sizeBytes > 0
      && firmwareTargetHasPartitionIdentity(target);
}

inline FirmwareTargetMatch matchFirmwareArtifactTarget(
    const FirmwareTargetContract& artifactTarget,
    const FirmwareTargetContract& receiverTarget
) {
  if (!firmwareStaticTargetIsKnown(artifactTarget) || !firmwareTargetIsKnown(receiverTarget))
    return FirmwareTargetUnknown;
  if (artifactTarget.targetId != receiverTarget.targetId)
    return FirmwareTargetHardwareMismatch;
  if (artifactTarget.hardwareFamily != receiverTarget.hardwareFamily)
    return FirmwareTargetHardwareMismatch;
  if (artifactTarget.chipFamily != receiverTarget.chipFamily)
    return FirmwareTargetChipMismatch;
  if (artifactTarget.flashMode != receiverTarget.flashMode)
    return FirmwareTargetFlashModeMismatch;
  if (artifactTarget.flashSizeBytes != receiverTarget.flashSizeBytes)
    return FirmwareTargetFlashSizeMismatch;
  if (memcmp(artifactTarget.partitionTableSha256, receiverTarget.partitionTableSha256,
      sizeof(artifactTarget.partitionTableSha256)) != 0)
    return FirmwareTargetPartitionMismatch;
  if (artifactTarget.otaSlotCount != receiverTarget.otaSlotCount
      || memcmp(artifactTarget.otaSlots, receiverTarget.otaSlots,
          sizeof(artifactTarget.otaSlots)) != 0)
    return FirmwareTargetOtaSlotMismatch;
  return FirmwareTargetMatchExact;
}

struct FirmwareUpdateDestination {
  uint8_t otaSlot = CANONICAL_MAX_OTA_SLOTS;
  uint32_t offset = 0;
  uint32_t sizeBytes = 0;
};

inline FirmwareUpdateDestination firmwareInactiveSlotDestination(
    const FirmwareTargetContract& target
) {
  FirmwareUpdateDestination destination;
  if (!firmwareTargetIsKnown(target))
    return destination;
  destination.otaSlot = target.inactiveOtaSlot;
  destination.offset = target.otaSlots[target.inactiveOtaSlot].offset;
  destination.sizeBytes = target.otaSlots[target.inactiveOtaSlot].sizeBytes;
  return destination;
}

inline bool firmwareArtifactFitsInactiveSlot(
    const FirmwareTargetContract& target,
    const FirmwareUpdateDestination& destination,
    uint32_t length
) {
  if (!firmwareTargetIsKnown(target) || length == 0)
    return false;
  const CanonicalOtaSlotRecord& slot = target.otaSlots[target.inactiveOtaSlot];
  return destination.otaSlot == target.inactiveOtaSlot
      && destination.offset == slot.offset
      && destination.sizeBytes == slot.sizeBytes
      && length <= destination.sizeBytes;
}
// AI: end
