#pragma once

#include <stdint.h>

#define TUBES_PROTOCOL_V2 2
#define TUBES_PROTOCOL_V3 3
#define CURRENT_NODE_VERSION TUBES_PROTOCOL_V3
#define MESSAGE_DATA_SIZE 64

typedef uint8_t CommandId;

#pragma pack(push,4)
// The four-byte packing is part of the deployed wire format.
typedef enum {
    RECIPIENTS_ALL=0,
    RECIPIENTS_ROOT=1,
    // Deliver only to direct radio neighbors; never forward or relay.
    RECIPIENTS_NEIGHBORS=2,
} MessageRecipients;

typedef uint16_t DeviceId;
typedef uint16_t ProtocolLocalValue;

// AI: below section was generated by an AI
constexpr DeviceId PROTOCOL_LOCAL_VALUE_MASK = 0x0FFF;
constexpr DeviceId PROTOCOL_GENERATION_MASK = 0xF000;
constexpr uint8_t PROTOCOL_GENERATION_SHIFT = 12;
constexpr uint8_t LEGACY_PROTOCOL_GENERATION = 0;
constexpr uint8_t CHANNEL_PROTOCOL_GENERATION = 1;
constexpr uint8_t CURRENT_PROTOCOL_GENERATION = CHANNEL_PROTOCOL_GENERATION;

static_assert((PROTOCOL_LOCAL_VALUE_MASK & PROTOCOL_GENERATION_MASK) == 0,
  "protocol generation and Device ID fields must not overlap");
static_assert(CURRENT_PROTOCOL_GENERATION <= 0x0F,
  "protocol generation must fit in the high Device ID nibble");

// Device IDs are full words: protocol generation first, then a 12-bit local value.
constexpr DeviceId makeDeviceId(uint8_t generation, ProtocolLocalValue localValue) {
  return (DeviceId(generation & 0x0F) << PROTOCOL_GENERATION_SHIFT)
      | (localValue & PROTOCOL_LOCAL_VALUE_MASK);
}

constexpr ProtocolLocalValue protocolLocalValueFromId(DeviceId id) {
  return id & PROTOCOL_LOCAL_VALUE_MASK;
}

constexpr uint8_t protocolGenerationFromId(DeviceId id) {
  return (id & PROTOCOL_GENERATION_MASK) >> PROTOCOL_GENERATION_SHIFT;
}

static_assert(makeDeviceId(LEGACY_PROTOCOL_GENERATION, 0x0ADC) == 0x0ADC,
  "legacy generation must preserve deployed IDs");
static_assert(makeDeviceId(CHANNEL_PROTOCOL_GENERATION, 0x0ADC) == 0x1ADC,
  "channel generation Device ID encoding changed");
static_assert(protocolLocalValueFromId(0x1ADC) == 0x0ADC,
  "Device ID must preserve its protocol-local value");
static_assert(protocolGenerationFromId(0x1ADC) == CHANNEL_PROTOCOL_GENERATION,
  "Device ID must preserve its protocol generation");
// AI: end

struct MeshNodeHeader {
    DeviceId id = 0;
    DeviceId uplinkId = 0;
    uint8_t version = CURRENT_NODE_VERSION;
};

struct NodeMessage {
    MeshNodeHeader header;
    MessageRecipients recipients;
    uint32_t timebase;
    CommandId command;
    uint8_t data[MESSAGE_DATA_SIZE] = {0};
};
#pragma pack(pop)

static_assert(sizeof(NodeMessage) == 84, "NodeMessage wire size changed");

struct MeshRoutePlan {
    bool accepted;
    bool applyLocally;
    bool relay;
    bool synchronizeClock;
};

// A child naming this node as its uplink needs this node to carry traffic. A rootless
// lower-ID neighbor also needs help discovering the stronger leader this node can reach.
inline bool shouldRenewRelayDuty(
    const MeshNodeHeader& localHeader,
    const MeshNodeHeader& peerHeader
) {
    return peerHeader.uplinkId == localHeader.id
        || (peerHeader.uplinkId == 0 && peerHeader.id < localHeader.id);
}

// Decide how one accepted wire packet moves through the current root-oriented tree.
// Root requests travel upward without being applied by intermediate relays. The root
// applies the request, then changes it into an all-recipient declaration for the
// downward trip. Only declarations from the selected uplink may set a follower's clock.
inline MeshRoutePlan planMeshRoute(
    const MeshNodeHeader& localHeader,
    bool localIsFollowing,
    bool localIsLeading,
    const NodeMessage& message
) {
    bool accepted = false;
    switch (message.recipients) {
        case RECIPIENTS_ALL:
            accepted = message.header.id == localHeader.uplinkId;
            break;

        case RECIPIENTS_ROOT:
            accepted = message.header.uplinkId == localHeader.id;
            break;

        case RECIPIENTS_NEIGHBORS:
            accepted = true;
            break;

        default:
            return {false, false, false, false};
    }

    if (!accepted)
        return {false, false, false, false};

    bool applyLocally = message.recipients != RECIPIENTS_ROOT || !localIsFollowing;
    bool relay = localIsLeading && message.recipients != RECIPIENTS_NEIGHBORS;
    bool synchronizeClock = applyLocally && message.recipients == RECIPIENTS_ALL;
    return {true, applyLocally, relay, synchronizeClock};
}

// Preserve the command and payload while making the forwarding node the next-hop sender.
// A root converts an upward request into the authoritative downward declaration.
inline NodeMessage makeRelayedMessage(
    const MeshNodeHeader& localHeader,
    bool localIsFollowing,
    const NodeMessage& received
) {
    NodeMessage relayed = received;
    uint8_t receivedVersion = received.header.version;
    relayed.header = localHeader;
    // Relays stamp their physical ID but preserve the packet family's decoder contract.
    relayed.header.version = receivedVersion;
    if (!localIsFollowing)
        relayed.recipients = RECIPIENTS_ALL;
    return relayed;
}
