#pragma once

#include <stdint.h>

// AI: below section was generated by an AI

// Advances a 24.8 beat frame toward a remote clock without ever stepping the
// local frame backward or jumping it forward. Explicit resets remain available
// for operator actions that intentionally start a new phrase.
class RubberBandBeatClock {
  public:
    using BeatFrame = uint32_t;

    static constexpr uint16_t MINIMUM_BPM_Q8 = 40U << 8;

    // Establishes a new clock immediately. Callers should reserve this for boot
    // and explicit phrase resets because it may reposition the beat frame.
    bool reset(uint16_t bpmQ8, BeatFrame beatFrame) {
      if (bpmQ8 < MINIMUM_BPM_Q8)
        return false;

      goalBpmQ8 = bpmQ8;
      runningBpmQ8 = bpmQ8;
      localFrame = beatFrame;
      goalFrame = beatFrame;
      localRemainder = 0;
      goalRemainder = 0;
      slewRemainder = 0;
      phaseGoalActive = false;
      initialized = true;
      return true;
    }

    // Changes the target tempo and phase while preserving the current local
    // frame. Subsequent updates close the difference by changing clock speed.
    bool setGoal(uint16_t bpmQ8, BeatFrame beatFrame) {
      if (bpmQ8 < MINIMUM_BPM_Q8)
        return false;
      if (!initialized)
        return reset(bpmQ8, beatFrame);

      goalBpmQ8 = bpmQ8;
      goalFrame = beatFrame;
      goalRemainder = 0;
      phaseGoalActive = true;
      return true;
    }

    // Changes only the target tempo, so a BPM command cannot reinterpret the
    // current beat as the beginning of the phrase.
    bool setTempoGoal(uint16_t bpmQ8) {
      if (bpmQ8 < MINIMUM_BPM_Q8)
        return false;
      if (!initialized)
        return reset(bpmQ8, 0);

      goalBpmQ8 = bpmQ8;
      goalFrame = localFrame;
      goalRemainder = localRemainder;
      phaseGoalActive = false;
      return true;
    }

    // Advances both clocks, then slews the local rate toward a bounded
    // phase-corrected rate. The local frame only changes through forward time.
    void advance(uint32_t deltaMicros) {
      if (!initialized || deltaMicros == 0)
        return;

      int32_t errorBeforeAdvance = phaseError();
      slewRunningBpm(phaseGoalActive ? desiredRunningBpm() : goalBpmQ8, deltaMicros);
      if (phaseGoalActive)
        advanceFrame(goalFrame, goalRemainder, goalBpmQ8, deltaMicros);
      advanceFrame(localFrame, localRemainder, runningBpmQ8, deltaMicros);
      if (!phaseGoalActive) {
        goalFrame = localFrame;
        goalRemainder = localRemainder;
        return;
      }
      int32_t errorAfterAdvance = phaseError();

      // Finish a correction at the first crossing. Both clocks reached the same
      // neighborhood through forward motion, so aligning their sub-frame state
      // cannot create the large discontinuity that `setGoal()` deliberately avoids.
      bool crossedFromBehind = errorBeforeAdvance > 0 && errorAfterAdvance <= 0;
      bool crossedFromAhead = errorBeforeAdvance < 0 && errorAfterAdvance >= 0;
      if (crossedFromBehind || crossedFromAhead) {
        localFrame = goalFrame;
        localRemainder = goalRemainder;
        runningBpmQ8 = goalBpmQ8;
        slewRemainder = 0;
        phaseGoalActive = false;
      }
    }

    BeatFrame frame() const {
      return localFrame;
    }

    uint16_t goalBpm() const {
      return goalBpmQ8;
    }

    uint16_t runningBpm() const {
      return runningBpmQ8;
    }

    int32_t phaseError() const {
      return int32_t(goalFrame - localFrame);
    }

  private:
    static constexpr uint32_t MICROS_PER_MINUTE = 60000000U;
    static constexpr uint32_t MICROS_PER_SECOND = 1000000U;
    static constexpr uint8_t PHASE_SETTLE_SECONDS = 4;
    static constexpr uint8_t MAXIMUM_PHASE_RATE_DIVISOR = 8;
    static constexpr uint16_t MINIMUM_RUNNING_BPM_Q8 = 1U << 8;
    static constexpr uint16_t BPM_SLEW_PER_SECOND_Q8 = 1U << 8;

    BeatFrame localFrame = 0;
    BeatFrame goalFrame = 0;
    uint32_t localRemainder = 0;
    uint32_t goalRemainder = 0;
    uint32_t slewRemainder = 0;
    uint16_t goalBpmQ8 = 0;
    uint16_t runningBpmQ8 = 0;
    bool phaseGoalActive = false;
    bool initialized = false;

    // Converts elapsed microseconds and Q8.8 BPM into 24.8 beat-frame units
    // while retaining the fractional numerator for the next update.
    static void advanceFrame(
        BeatFrame& beatFrame,
        uint32_t& remainder,
        uint16_t bpmQ8,
        uint32_t deltaMicros
    ) {
      uint64_t numerator = remainder + uint64_t(deltaMicros) * bpmQ8;
      beatFrame += numerator / MICROS_PER_MINUTE;
      remainder = numerator % MICROS_PER_MINUTE;
    }

    // A four-second proportional correction closes small phase errors smoothly.
    // The one-eighth rate bound keeps large errors from producing implausible tempos.
    uint16_t desiredRunningBpm() const {
      int32_t error = phaseError();
      if (error == 0)
        return goalBpmQ8;
      int32_t correction = int32_t((int64_t(error) * 60) / PHASE_SETTLE_SECONDS);
      int32_t maximumCorrection = goalBpmQ8 / MAXIMUM_PHASE_RATE_DIVISOR;
      if (correction > maximumCorrection)
        correction = maximumCorrection;
      else if (correction < -maximumCorrection)
        correction = -maximumCorrection;

      int32_t desired = int32_t(goalBpmQ8) + correction;
      if (desired < MINIMUM_RUNNING_BPM_Q8)
        return MINIMUM_RUNNING_BPM_Q8;
      if (desired > UINT16_MAX)
        return UINT16_MAX;
      return uint16_t(desired);
    }

    // Limits rate changes to one BPM per second. The retained remainder keeps
    // the limit effective even when loop updates are shorter than one Q8.8 step.
    void slewRunningBpm(uint16_t desiredBpmQ8, uint32_t deltaMicros) {
      if (runningBpmQ8 == desiredBpmQ8) {
        slewRemainder = 0;
        return;
      }

      uint64_t available = slewRemainder
          + uint64_t(deltaMicros) * BPM_SLEW_PER_SECOND_Q8;
      uint32_t maximumStep = available / MICROS_PER_SECOND;
      slewRemainder = available % MICROS_PER_SECOND;
      if (maximumStep == 0)
        return;

      if (runningBpmQ8 < desiredBpmQ8) {
        uint32_t increased = uint32_t(runningBpmQ8) + maximumStep;
        runningBpmQ8 = increased >= desiredBpmQ8 ? desiredBpmQ8 : uint16_t(increased);
      } else {
        uint32_t difference = runningBpmQ8 - desiredBpmQ8;
        runningBpmQ8 = maximumStep >= difference
            ? desiredBpmQ8
            : uint16_t(runningBpmQ8 - maximumStep);
      }
    }
};

// AI: end
