#pragma once

#include <stddef.h>
#include <stdint.h>

#include "device_report_protocol.h"
#include "firmware_image_source.h"

// AI: below section was generated by an AI
struct RunningImageInfo {
  uint32_t partitionAddress = 0;
  uint32_t partitionSizeBytes = 0;
  uint32_t imageLengthBytes = 0;
  uint32_t releaseHash = 0;
  uint8_t hardwareFamily = TubeHardwareUnknown;
  uint8_t firmwareVariant = TubeVariantStandard;
  uint8_t imageSha256[32] = {0};
};

inline bool runningImageRangeIsValid(size_t imageLength, size_t offset, size_t length) {
  return firmwareImageRangeIsValid(imageLength, offset, length);
}

#if defined(ARDUINO_ARCH_ESP32)
bool inspectRunningImage(RunningImageInfo& info, char* error, size_t errorLength);
bool readRunningImageChunk(
    const RunningImageInfo& info,
    size_t offset,
    uint8_t* destination,
    size_t length,
    char* error,
    size_t errorLength
);

// Adapts only the canonical Dig2Go v14 running application to the source
// contract used by stored carrier artifacts. No other canonical running
// artifact is registered, so the supported target is explicit in this type.
class Dig2GoV14RunningFirmwareImageSource : public FirmwareImageSource {
public:
  Dig2GoV14RunningFirmwareImageSource()
      : _artifactTarget(firmwareStaticTargetFromCanonical(
          CANONICAL_TARGET_QUINLED_DIG2GO, TubeHardwareDig2Go)) {}

  bool inspect(FirmwareImageArtifact& artifact) override;
  bool read(size_t offset, uint8_t* destination, size_t length) override;

private:
  FirmwareTargetContract _artifactTarget;
  RunningImageInfo _runningInfo;
  bool _inspected = false;
};
#endif
// AI: end
