#pragma once

#include <stddef.h>
#include <stdint.h>

// AI: below section was generated by an AI
// Bounded receiver-evidence catalog for the S3 Surveyor. It stores only facts
// present on the existing Tubes frame and ESP-NOW receive callback; RSSI is not
// converted to distance or location.
static constexpr size_t S3_PEER_CAPACITY = 12;
static constexpr uint32_t S3_PEER_FRESH_MS = 60000;

struct S3PeerEvidence {
  uint16_t remoteId = 0;
  uint16_t uplinkId = 0;
  int8_t rssi = 0;
  uint32_t lastSeenMs = 0;
};

class S3PeerCatalog {
public:
  void observe(uint16_t remoteId, uint16_t uplinkId, int8_t rssi, uint32_t nowMs) {
    if (remoteId == 0) return;
    size_t slot = S3_PEER_CAPACITY;
    size_t oldest = 0;
    for (size_t index = 0; index < S3_PEER_CAPACITY; index++) {
      if (_entries[index].remoteId == remoteId) {
        slot = index;
        break;
      }
      if (_entries[index].remoteId == 0 && slot == S3_PEER_CAPACITY) slot = index;
      if (_entries[index].lastSeenMs < _entries[oldest].lastSeenMs) oldest = index;
    }
    if (slot == S3_PEER_CAPACITY) slot = oldest;
    _entries[slot] = {remoteId, uplinkId, rssi, nowMs};
  }

  size_t copyFresh(uint32_t nowMs, uint16_t localRemoteId,
      S3PeerEvidence* destination, size_t capacity) const {
    if (!destination || capacity == 0) return 0;
    size_t count = 0;
    for (const S3PeerEvidence& candidate : _entries) {
      if (candidate.remoteId == 0 || candidate.remoteId == localRemoteId
          || nowMs - candidate.lastSeenMs > S3_PEER_FRESH_MS)
        continue;
      size_t at = count < capacity ? count++ : capacity;
      if (at == capacity) {
        const S3PeerEvidence& weakest = destination[capacity - 1];
        if (candidate.rssi < weakest.rssi
            || (candidate.rssi == weakest.rssi && candidate.remoteId >= weakest.remoteId))
          continue;
        at = capacity - 1;
      }
      while (at > 0 && stronger(candidate, destination[at - 1])) {
        if (at < capacity) destination[at] = destination[at - 1];
        at--;
      }
      destination[at] = candidate;
    }
    return count;
  }

private:
  static bool stronger(const S3PeerEvidence& candidate, const S3PeerEvidence& prior) {
    return candidate.rssi > prior.rssi
        || (candidate.rssi == prior.rssi && candidate.remoteId < prior.remoteId);
  }

  S3PeerEvidence _entries[S3_PEER_CAPACITY] = {};
};
// AI: end
