
#include "wled.h"
#include "fcn_declare.h"
#include "particle.h"
#include "tempo_tracker.h"
#include "effect_chance.h"
#include "../audioreactive/audio_tempo_data.h"

// AI: below section was generated by an AI
struct SoundAccent {
  uint8_t kick = 0;
  uint8_t snare = 0;
  uint8_t music = 0;
};
// AI: end

class Sounder {
  public:
    bool active = false;
    bool overlay = false;
    bool tempoTracking = false;
    bool tempoLocked = false;
    uint16_t tempoBpmQ8 = 0;
    uint8_t tempoConfidence = 0;
    bool tempoPhaseTracked = false;
    int16_t tempoPhaseErrorMs = 0;
    uint8_t tempoTimingEvents = 0;
    bool programActive = false;
    uint8_t volume = 0;
    // AI: below section was generated by an AI
    uint16_t volumeRaw = 0;
    bool samplePeak = false;
    uint32_t samplePeakCount = 0;
    float majorFrequency = 0.0f;
    float magnitude = 0.0f;
    uint8_t strongestBin = 0;
    uint8_t strongestBinLevel = 0;
    uint8_t spectrumLevels[12] = {};
    uint8_t kickStrength = 0;
    uint8_t snareStrength = 0;
    uint8_t musicStrength = 0;
    // AI: end

    void setup() {
      // AI: below section was generated by an AI
      // Boot always clears both optional audio consumers, including a persisted
      // AudioReactive enable left behind by an earlier session.
      setTempoTracking(false);
      setOverlay(false);
      // AI: end
    }

    // AI: below section was generated by an AI
    // Couples the visible overlay to AudioReactive's runtime processing state.
    // The requested overlay remains set if the source is temporarily unavailable,
    // allowing update() to recover without another fleet command.
    bool setOverlay(bool enabled) {
      overlay = enabled;
      active = false;
      if (!enabled && !tempoTracking) {
        volume = 0;
        particleVolume = DEFAULT_PARTICLE_VOLUME;
      }
      return setAudioProcessing(overlay || tempoTracking);
    }

    // Enables local microphone tempo estimation without enabling its visual overlay.
    bool setTempoTracking(bool enabled) {
      tempoTracking = enabled;
      tempoTracker.reset();
      tempoEstimatePending = false;
      tempoLocked = false;
      tempoBpmQ8 = 0;
      tempoConfidence = 0;
      tempoPhaseTracked = false;
      tempoPhaseErrorMs = 0;
      tempoTimingEvents = 0;
      lastTempoSpectrumSequence = 0;
      if (!enabled && !overlay) {
        active = false;
        volume = 0;
        particleVolume = DEFAULT_PARTICLE_VOLUME;
      }
      return setAudioProcessing(overlay || tempoTracking);
    }

    void setProgramActive(bool enabled) {
      programActive = enabled;
    }

    void setOverlayChance(uint8_t chance) {
      overlayChance = chance;
    }

    // Beat ownership gates tempo tracking; every pole may render its local microphone transients.
    void setLocalTransientAuthority(bool enabled) {
      if (localTransientAuthority == enabled)
        return;
      localTransientAuthority = enabled;
      tempoTracker.reset();
      tempoEstimatePending = false;
      tempoLocked = false;
      tempoPhaseTracked = false;
      tempoPhaseErrorMs = 0;
      tempoTimingEvents = 0;
      lastTempoSpectrumSequence = 0;
    }

    void update() {
      decayAccent();
      if (!overlay && !tempoTracking) {
        active = false;
        clearAccent();
        particleVolume = DEFAULT_PARTICLE_VOLUME; // Average volume
        return;
      }

      um_data_t *um_data = nullptr;
      if (!UsermodManager::getUMData(&um_data, USERMOD_ID_AUDIOREACTIVE)
          || !um_data
          || um_data->u_size < 1
          || !um_data->u_data
          || !um_data->u_data[0]) {
        active = false;
        particleVolume = DEFAULT_PARTICLE_VOLUME;
        return;
      }

      active = true;
      float volumeSmth = *(float*)um_data->u_data[0];
      volume = constrain(volumeSmth, 0, 255);     // Keep the sample from overflowing.
      particleVolume = volume;

      if (um_data->u_size >= 6
          && um_data->u_data[1]
          && um_data->u_data[2]
          && um_data->u_data[3]
          && um_data->u_data[4]
          && um_data->u_data[5]) {
        volumeRaw = *(uint16_t*)um_data->u_data[1];
        bool nextPeak = *(uint8_t*)um_data->u_data[3];
        if (nextPeak && !samplePeak)
          samplePeakCount++;
        samplePeak = nextPeak;
        majorFrequency = *(float*)um_data->u_data[4];
        magnitude = *(float*)um_data->u_data[5];
        uint8_t* fftResult = (uint8_t*)um_data->u_data[2];
        strongestBin = 0;
        strongestBinLevel = fftResult[0];
        for (uint8_t bin = 1; bin < 16; bin++) {
          if (fftResult[bin] <= strongestBinLevel)
            continue;
          strongestBin = bin;
          strongestBinLevel = fftResult[bin];
        }
        for (uint8_t bin = 0; bin < 12; bin++) spectrumLevels[bin] = fftResult[bin];
        if (overlay)
          updateTransientDetector(fftResult);
        else
          clearAccent();
        updateTempoTracker(um_data);
      }
    }

    bool takeTempoEstimate(TempoEstimate& result) {
      if (!tempoEstimatePending)
        return false;
      result = pendingTempoEstimate;
      tempoEstimatePending = false;
      return true;
    }

    const TempoDiagnostics& tempoDiagnostics() const {
      return tempoTracker.currentDiagnostics();
    }

    bool isLocalBeatAuthority() const {
      return localTransientAuthority;
    }

    // Gives one transient the same independent per-pole chance used by regular effects.
    void tryApplyAccent(const SoundAccent& accent) {
      if (!effectChanceAccepts(overlayChance, random8()))
        return;
      kickStrength = max(kickStrength, accent.kick);
      snareStrength = max(snareStrength, accent.snare);
      musicStrength = max(musicStrength, accent.music);
      lastAccentDecayMs = millis();
    }

    uint8_t scaledAccentOpacity(uint8_t maximumOpacity) const {
      return scale8(maximumOpacity, visualAccentStrength());
    }
    // AI: end

    void handleOverlayDraw() {
      // Native WLED segment programs provide their own visual layer.
      if (programActive)
        return;
      if (!active)
        return;
      if (!overlay)
        return;

      Segment& segment = strip.getMainSegment();
      uint16_t total = strip.getLengthTotal();
      uint16_t musicLength = scale8(musicStrength, total / 12);
      uint8_t musicBlend = scale8(musicStrength, 38);
      for (uint16_t i = 0; i < musicLength; i++) {
        CRGB base = strip.getPixelColor(i);
        CRGB accent = segment.color_from_palette(i, true, true, 255, 192);
        nblend(base, accent, musicBlend);
        strip.setPixelColor(i, base);
      }

      uint16_t maximumKickLength = total / 3;
      if (!maximumKickLength)
        maximumKickLength = 1;
      uint16_t kickLength = scale8(kickStrength, maximumKickLength);
      for (uint16_t i = 0; i < kickLength; i++) {
        uint32_t color = segment.color_from_palette(i, true, true, 255, 192);
        strip.setPixelColor(i, color);
      }

      // A snare/clap adds a sparse full-height accent while the kick stays grounded.
      if (snareStrength > 24) {
        uint8_t offset = (particle_beat_frame >> 8) % 5;
        for (uint16_t i = offset; i < total; i += 5) {
          CRGB base = strip.getPixelColor(i);
          CRGB accent = segment.color_from_palette(i, true, true, 255, 192);
          nblend(base, accent, snareStrength);
          strip.setPixelColor(i, base);
        }
      }
    }

    static float mapf(float x, float in_min, float in_max, float out_min, float out_max){
      return (x - in_min) * (out_max - out_min) / (in_max - in_min) + out_min;
    }

  private:
    // AI: below section was generated by an AI
    bool localTransientAuthority = false;
    uint8_t overlayChance = 255;
    bool transientDetectorPrimed = false;
    uint8_t previousBins[16] = {0};
    uint16_t kickFluxFloorQ8 = 0;
    uint16_t snareFluxFloorQ8 = 0;
    uint16_t musicFluxFloorQ8 = 0;
    uint32_t lastDetectedAccentMs = 0;
    uint32_t lastAccentDecayMs = 0;
    TempoTracker tempoTracker;
    TempoEstimate pendingTempoEstimate;
    bool tempoEstimatePending = false;
    uint32_t lastTempoSpectrumSequence = 0;

    bool setAudioProcessing(bool enabled) {
      Usermod *audioReactive = UsermodManager::lookup(USERMOD_ID_AUDIOREACTIVE);
      return audioReactive && audioReactive->setEnabled(enabled);
    }

    // Takes a consistent copy of each raw FFT mapping without blocking its task.
    void updateTempoTracker(um_data_t* data) {
      if (!tempoTracking
          || !localTransientAuthority
          || data->u_size < 11
          || !data->u_data[10])
        return;

      AudioTempoData* source = (AudioTempoData*)data->u_data[10];
      uint32_t sequence = __atomic_load_n(&source->publishedSequence, __ATOMIC_ACQUIRE);
      if (!sequence || sequence == lastTempoSpectrumSequence)
        return;

      float spectrum[TempoTracker::SPECTRUM_BINS];
      AudioTempoSpectrum& published = source->slots[sequence & 1U];
      uint32_t spectrumTimestampUs = published.timestampUs;
      memcpy(spectrum, published.bands, sizeof(spectrum));
      if (sequence != __atomic_load_n(&source->publishedSequence, __ATOMIC_ACQUIRE))
        return;

      uint32_t elapsedFrames = lastTempoSpectrumSequence
          ? sequence - lastTempoSpectrumSequence
          : 1;
      lastTempoSpectrumSequence = sequence;
      uint8_t missingFrames = elapsedFrames > 256 ? 255 : uint8_t(elapsedFrames - 1);
      tempoTracker.addSpectrumAt(spectrum, spectrumTimestampUs, missingFrames);

      TempoEstimate nextEstimate;
      if (!tempoTracker.takeEstimate(nextEstimate))
        return;
      pendingTempoEstimate = nextEstimate;
      tempoEstimatePending = true;
      tempoLocked = nextEstimate.locked;
      tempoBpmQ8 = nextEstimate.bpmQ8;
      tempoConfidence = nextEstimate.confidence;
      tempoPhaseTracked = nextEstimate.phaseTracked;
      tempoPhaseErrorMs = nextEstimate.phaseErrorMs;
      tempoTimingEvents = nextEstimate.timingEvents;
    }

    uint8_t visualAccentStrength() const {
      return max(kickStrength, max(scale8(snareStrength, 192), scale8(musicStrength, 38)));
    }

    static uint8_t transientStrength(uint16_t flux, uint16_t floorQ8, uint8_t minimumThreshold) {
      uint16_t threshold = (floorQ8 >> 8) + minimumThreshold;
      if (threshold < minimumThreshold)
        threshold = minimumThreshold;
      if (flux <= threshold)
        return 0;
      return constrain((flux - threshold) * 8, 0, 255);
    }

    // Detects positive spectral flux in kick and snare bands instead of sustained loudness.
    // FFT band mapping: https://github.com/wled/WLED/blob/main/usermods/audioreactive/audio_reactive.cpp
    void updateTransientDetector(const uint8_t* bins) {
      if (!transientDetectorPrimed) {
        memcpy(previousBins, bins, sizeof(previousBins));
        transientDetectorPrimed = true;
        return;
      }

      uint8_t positiveChange[16];
      uint16_t musicFlux = 0;
      for (uint8_t bin = 0; bin < 16; bin++) {
        positiveChange[bin] = bins[bin] > previousBins[bin] ? bins[bin] - previousBins[bin] : 0;
        previousBins[bin] = bins[bin];
        musicFlux += positiveChange[bin];
      }
      uint16_t kickFlux =
          (5U * positiveChange[0] + 10U * positiveChange[1] + 7U * positiveChange[2]) / 22U;
      uint16_t snareFlux = 0;
      for (uint8_t bin = 9; bin <= 13; bin++)
        snareFlux += positiveChange[bin];
      snareFlux /= 5;
      musicFlux /= 16;

      int32_t kickFloorDelta = (int32_t(kickFlux) << 8) - kickFluxFloorQ8;
      int32_t snareFloorDelta = (int32_t(snareFlux) << 8) - snareFluxFloorQ8;
      int32_t musicFloorDelta = (int32_t(musicFlux) << 8) - musicFluxFloorQ8;
      kickFluxFloorQ8 = uint16_t(int32_t(kickFluxFloorQ8) + kickFloorDelta / 32);
      snareFluxFloorQ8 = uint16_t(int32_t(snareFluxFloorQ8) + snareFloorDelta / 32);
      musicFluxFloorQ8 = uint16_t(int32_t(musicFluxFloorQ8) + musicFloorDelta / 32);

      SoundAccent accent;
      uint8_t rawKick = transientStrength(kickFlux, kickFluxFloorQ8, 5);
      uint8_t rawSnare = transientStrength(snareFlux, snareFluxFloorQ8, 4);
      accent.music = transientStrength(musicFlux, musicFluxFloorQ8, 6);

      // Spectral concentration raises confidence that a transient is actual percussion.
      uint8_t kickConfidence = uint32_t(kickFlux) * 255U / (kickFlux + 2U * musicFlux + 1U);
      uint8_t snareConfidence = uint32_t(snareFlux) * 255U / (snareFlux + 2U * musicFlux + 1U);
      accent.kick = scale8(rawKick, 128 + scale8(kickConfidence, 127));
      accent.snare = scale8(rawSnare, 112 + scale8(snareConfidence, 143));
      uint8_t visualStrength = max(
          accent.kick,
          max(scale8(accent.snare, 192), scale8(accent.music, 38))
      );
      uint32_t nowMs = millis();
      if (visualStrength < 24 || nowMs - lastDetectedAccentMs < 90)
        return;

      lastDetectedAccentMs = nowMs;
      // Each pole renders its own microphone transient. Broadcasting these
      // short-lived accents as complete Beat states overwhelmed clock traffic.
      if (overlay)
        tryApplyAccent(accent);
    }

    void decayAccent() {
      uint32_t nowMs = millis();
      if (!lastAccentDecayMs) {
        lastAccentDecayMs = nowMs;
        return;
      }
      uint32_t elapsedMs = nowMs - lastAccentDecayMs;
      if (!elapsedMs)
        return;
      lastAccentDecayMs = nowMs;
      uint32_t decayValue = elapsedMs * 255U / 240U;
      uint16_t kickDecay = decayValue > 255 ? 255 : decayValue;
      uint32_t snareDecayValue = elapsedMs * 255U / 180U;
      uint16_t snareDecay = snareDecayValue > 255 ? 255 : snareDecayValue;
      uint32_t musicDecayValue = elapsedMs * 255U / 600U;
      uint16_t musicDecay = musicDecayValue > 255 ? 255 : musicDecayValue;
      kickStrength = qsub8(kickStrength, kickDecay);
      snareStrength = qsub8(snareStrength, snareDecay);
      musicStrength = qsub8(musicStrength, musicDecay);
    }

    void clearAccent() {
      kickStrength = 0;
      snareStrength = 0;
      musicStrength = 0;
      transientDetectorPrimed = false;
      lastAccentDecayMs = 0;
    }
    // AI: end

};
