#pragma once

#include "wled.h"
#include "fastled_compat.h"

#include "util.h"
#include "options.h"

// #define USERADIO

#include "FX.h"

#include "virtual_strip.h"
#include "led_strip.h"
#include "master.h"
#include "s3_field_api.h"

#include "controller.h"
#include "debug.h"

#ifndef PIXEL_COUNTS
#define PIXEL_COUNTS DEFAULT_LED_COUNT
#endif

#ifndef DATA_PINS
#define DATA_PINS DEFAULT_LED_PIN
#endif

#ifndef LED_TYPES
#define LED_TYPES DEFAULT_LED_TYPE
#endif

#ifndef DEFAULT_LED_COLOR_ORDER
#define DEFAULT_LED_COLOR_ORDER COL_ORDER_GRB
#endif

#define MASTER_PIN 25
#define LEGACY_PIN 32  // DigUno Q4


class TubesUsermod : public Usermod {
  private:
    PatternController controller = PatternController();
    DebugController debug = DebugController(controller);
    Master master = Master(controller);
    bool isLegacy = false;
    bool checkedLedSegments = false;

    void randomize() {
      randomSeed(esp_random());
      random16_set_seed(random(0, 65535));
      random16_add_entropy(esp_random());
    }

    void recoverLedBussesIfNeeded() {
#ifdef TUBES_NULL_OUTPUT
      BusManager::removeAll();
      busConfigs.clear();
      uint8_t noPins[OUTPUT_MAX_PINS] = {255, 255, 255, 255, 255};
      busConfigs.emplace_back(TYPE_TUBES_NULL, noPins, 0, PIXEL_COUNTS, COL_ORDER_RGB);
      doInitBusses = true;
      return;
#endif
      if (strip.getLengthTotal() > 0 || BusManager::getNumBusses() > 0 || !busConfigs.empty()) return;

      constexpr unsigned defDataTypes[] = {LED_TYPES};
      constexpr unsigned defDataPins[] = {DATA_PINS};
      constexpr unsigned defCounts[] = {PIXEL_COUNTS};
      constexpr unsigned defNumTypes = sizeof(defDataTypes) / sizeof(defDataTypes[0]);
      constexpr unsigned defNumPins = sizeof(defDataPins) / sizeof(defDataPins[0]);
      constexpr unsigned defNumCounts = sizeof(defCounts) / sizeof(defCounts[0]);

      unsigned pinsIndex = 0;
      unsigned start = 0;
      for (unsigned i = 0; i < WLED_MAX_BUSSES; i++) {
        uint8_t pins[OUTPUT_MAX_PINS] = {255, 255, 255, 255, 255};
        unsigned dataType = defDataTypes[(i < defNumTypes) ? i : defNumTypes - 1];
        unsigned busPins = Bus::getNumberOfPins(dataType);
        if (pinsIndex + busPins > defNumPins) break;

        for (unsigned j = 0; j < busPins && j < OUTPUT_MAX_PINS; j++) {
          pins[j] = defDataPins[pinsIndex + j];
        }
        pinsIndex += busPins;

        unsigned count = defCounts[(i < defNumCounts) ? i : defNumCounts - 1];
        if (Bus::isPWM(dataType) || Bus::isOnOff(dataType)) count = 1;

        busConfigs.emplace_back(dataType, pins, start, count, DEFAULT_LED_COLOR_ORDER, false, 0, RGBW_MODE_MANUAL_ONLY, 0, LED_MILLIAMPS_DEFAULT, ABL_MILLIAMPS_DEFAULT, 0);
        start += count;
      }

      if (!busConfigs.empty()) {
        doInitBusses = true;
        Serial.println(F("Tubes: recovered default LED bus config"));
      }
    }

    void recoverLedSegmentsIfNeeded() {
      if (checkedLedSegments || doInitBusses || strip.getLengthTotal() == 0 || BusManager::getNumBusses() == 0) return;

      bool needsSegments = strip.getSegmentsNum() == 0;
#ifdef TUBES_NULL_OUTPUT
      if (!needsSegments) {
        const Segment& seg = strip.getMainSegment();
        needsSegments = seg.length() != strip.getLengthTotal() || seg.start >= strip.getLengthTotal();
      }
#else
      if (!needsSegments) {
        const Segment& seg = strip.getMainSegment();
        // WLED may retain its one-pixel placeholder after the LED bus is restored.
        needsSegments = seg.length() == 0
          || seg.start >= strip.getLengthTotal()
          || (strip.getSegmentsNum() == 1 && seg.start == 0 && seg.stop == 1 && strip.getLengthTotal() > 1);
      }
#endif

      if (needsSegments) {
        strip.makeAutoSegments(true);
        Serial.println(F("Tubes: recovered LED segment config"));
      }
      checkedLedSegments = true;
    }

  public:
    // AI: below section was generated by an AI
    // Supplies the board UI with a fixed-size, read-only snapshot of Tubes state.
    void readS3FieldStatus(TubesS3FieldStatus &status) {
      status.isMaster = controller.isMasterRole();
      status.isFollowing = controller.node.isFollowing();
      status.radioReady = espnowBroadcast.isStarted();
      status.powerSave = controller.power_save;
      status.canForceNext = controller.can_force_next();
      status.role = static_cast<uint8_t>(controller.role);
      status.radioChannel = WiFi.channel();
      status.patternId = controller.current_state.pattern_id;
      status.paletteId = controller.current_state.palette_id;
      status.bpm = controller.current_state.bpm >> 8;
      status.beatFrame = controller.current_state.beat_frame;
      status.beat = (controller.current_state.beat_frame >> 8) % 16;
      status.currentPatternPhrase = controller.current_state.beat_frame >> 12;
      status.nextPatternPhrase = controller.next_state.pattern_phrase;
      status.localNodeId = controller.node.header.id;
      status.uplinkId = controller.node.header.uplinkId;
      status.tubesVersion = RELEASE_VERSION;
      status.currentSyncMode = controller.current_state.pattern_sync_id;
      status.nextPatternId = controller.next_state.pattern_id;
      status.nextSyncMode = controller.next_state.pattern_sync_id;
      status.currentPalettePhrase = controller.current_state.palette_phrase;
      status.nextPalettePhrase = controller.next_state.palette_phrase;
      status.nextPaletteId = controller.next_state.palette_id;
      const uint32_t now = millis();
      status.peerCount = controller.node.peerTelemetry.freshCount(now, 60000);
      fillS3ChannelStatus(status.beatChannel, BeatChannel, now);
      fillS3ChannelStatus(status.patternChannel, PatternChannel, now);
      fillS3ChannelStatus(status.paletteChannel, PaletteChannel, now);
      snprintf(status.patternName, sizeof(status.patternName), "Pattern %u", status.patternId);
      const uint16_t length = strip.getLengthTotal();
      for (size_t i = 0; i < TUBES_S3_PREVIEW_PIXELS; i++) {
        const uint16_t pixel = length == 0 ? 0 : static_cast<uint16_t>((i * length) / TUBES_S3_PREVIEW_PIXELS);
        status.preview[i] = length == 0 ? 0 : strip.getPixelColor(pixel);
      }
    }

    void fillS3ChannelStatus(TubesS3ChannelStatus &status, uint8_t channel, uint32_t now) {
      status = TubesS3ChannelStatus{};
      status.localChannelId = controller.localChannelId(channel);
      const ChannelWinner &winner = controller.channelWinners.get(channel, now);
      status.active = winner.active;
      if (!winner.active) return;
      status.ownerChannelId = winner.authority.channelId;
      status.ownerControlId = winner.authority.controlId;
      status.sourceSession = winner.sourceSession;
      status.sequence = winner.sequence;
      status.leaseRemainingMs = static_cast<int32_t>(winner.expiresAtMs - now) > 0
          ? winner.expiresAtMs - now : 0;
    }

    bool readS3Peer(size_t index, TubesS3PeerStatus &peer) const {
      const PeerTelemetryEntry *entry = controller.node.peerTelemetry.entry(index);
      if (entry == nullptr) return false;
      peer.nodeId = entry->nodeId;
      peer.uplinkId = entry->uplinkId;
      peer.lastSeenMs = entry->lastSeenMs;
      peer.samples = entry->samples;
      peer.latestRssi = entry->latestRssi;
      peer.protocolGeneration = entry->protocolGeneration;
      peer.tubesVersion = entry->tubesVersion;
      peer.rssiKnown = entry->rssiKnown;
      return true;
    }

    bool s3ForceNext() { return controller.force_next_if_authoritative(); }
    bool s3BroadcastFleetOffer(const FleetUpdateOffer &offer) {
      return controller.broadcastFleetUpdateOffer(offer);
    }
    bool s3RequestDeviceReport(const uint8_t mac[6], uint32_t nonce) {
      return controller.requestDeviceReport(mac, nonce);
    }
    // AI: end

    void setup() {
      randomize();

      recoverLedBussesIfNeeded();
      // Start timing
      globalTimer.setup();
      controller.setup();

      if (!controller.isHomeLightRole()) {
        if (PinManager::isPinOk(MASTER_PIN)) {
          pinMode(MASTER_PIN, INPUT_PULLUP);
          if(PinManager::isPinOk(LEGACY_PIN)) {
            pinMode(LEGACY_PIN, INPUT_PULLUP);
          }
          isLegacy = (digitalRead(MASTER_PIN) == LOW);
        }

        // Override some behaviors on Tubes that render the mesh patterns.
        bootPreset = 0;  // Try to prevent initial playlists from starting
        transitionDelay = 8000;   // Fade them for a long time
        strip.setTransition(transitionDelay);
        strip.setTargetFps(60);
        strip.setCCT(100);
      }

      if (controller.isMasterRole()) {
#ifndef TUBES_S3_FIELD_OS
        master.setup();
#endif
      }
      debug.setup();
    }

    void loop()
    {
      EVERY_N_MILLISECONDS(10000) {
        randomize();
      }

      globalTimer.update();
      recoverLedSegmentsIfNeeded();

      if (controller.isMasterRole()) {
#ifndef TUBES_S3_FIELD_OS
        master.update();
#endif
      }
      controller.update();
      debug.update();

      // Draw after everything else is done
      controller.led_strip.update();
    }

    void readFromJsonState(JsonObject& root) override {
      controller.readJsonOperations(root);
    }

    void addToJsonInfo(JsonObject& root) override {
      controller.addV3JsonInfo(root);
    }

    void handleOverlayDraw() {
      // WiFi mode leaves the WLED frame untouched; Tubes mode renders the mesh.
      if (!controller.shouldRenderTubes())
        return;

      // AI: below section was generated by an AI
      // Preserve both render inputs so diagnostics can explain the final composited frame.
      debug.captureRenderInputs();
      // AI: end

      // Draw effects layers over whatever WLED is doing.
      controller.handleOverlayDraw();
      debug.handleOverlayDraw();
      if (controller.isMasterRole()) {
#ifndef TUBES_S3_FIELD_OS
        master.handleOverlayDraw();
#endif
      }

      // When AP mode is on, make sure it's obvious
      // Blink when there's a connected client
      if (apActive) {
        strip.setPixelColor(0, CRGB::Purple);
        if (millis() % 4000 > 1000 && WiFi.softAPgetStationNum()) {
          strip.setPixelColor(0, CRGB::Black);
        }
        strip.setPixelColor(1, CRGB::Black);
      }

      // AI: below section was generated by an AI
      controller.handleIdentifyOverlayDraw();
      // AI: end

      // AI: below section was generated by an AI
      debug.observeRenderedOutput();
      // AI: end
    }

    bool handleButton(uint8_t b) {
      if (controller.isHomeLightRole())
        return false;

      // Special code for handling the "power save" button
      if (b == 100) { // Press button 0 for WLED_LONG_POWER_SAVE ms
        controller.togglePowerSave();
        return true;
      }
      if (b == 101) { // Short press button 0 (piggybacks with default)
        controller.cancelOverrides();
        return true;
      }
      if (b == 102) { // Double-click button 0
        controller.acknowledge();
        if (controller.isSelecting()) {
          if (controller.isSelected())
            controller.deselect();
          else
            controller.select();
        } else {
          controller.request_new_bpm();
        }
        return true;
      }

      return false;
    }

    uint16_t getId() override { return USERMOD_ID_TUBES; }
};
