#include "Tubes.h"

static TubesUsermod tubes;
REGISTER_USERMOD(tubes);

bool tubesS3ReadStatus(TubesS3FieldStatus &status) {
  tubes.readS3FieldStatus(status);
  return true;
}

bool tubesS3ReadPeer(size_t index, TubesS3PeerStatus &peer) {
  return tubes.readS3Peer(index, peer);
}

bool tubesS3ForceNext() {
  return tubes.s3ForceNext();
}

// AI: below section was generated by an AI
bool tubesS3SelectPattern(uint8_t patternId) {
  return tubes.s3SelectPattern(patternId);
}

bool tubesS3ScheduleGradient(const uint32_t colors[3]) {
  return tubes.s3ScheduleGradient(colors);
}

bool tubesS3SetTempoListening(bool enabled) {
  return tubes.s3SetTempoListening(enabled);
}

bool tubesS3TapDownbeat() {
  return tubes.s3TapDownbeat();
}

bool tubesS3SelectBeatOverlay(uint8_t choice) {
  return tubes.s3SelectBeatOverlay(choice);
}
// AI: end

bool tubesS3BroadcastFleetOffer(const FleetUpdateOffer &offer) {
  return tubes.s3BroadcastFleetOffer(offer);
}

bool tubesS3RequestDeviceReport(const uint8_t mac[6], uint32_t nonce) {
  return tubes.s3RequestDeviceReport(mac, nonce);
}
