#pragma once

#include <stdint.h>
#include <string.h>

#include "global_state.h"
#include "mesh_protocol.h"

// AI: below section was generated by an AI

constexpr uint8_t TUBES_CHANNEL_VERSION_1 = 1;
constexpr uint8_t TUBES_CHANNEL_ENVELOPE_SIZE = 16;
constexpr uint8_t TUBES_CHANNEL_BODY_SIZE = MESSAGE_DATA_SIZE - TUBES_CHANNEL_ENVELOPE_SIZE;
constexpr uint32_t TUBES_CHANNEL_LEASE_MS = 20000;
constexpr uint16_t TUBES_CHANNEL_LEASE_DECISECONDS = TUBES_CHANNEL_LEASE_MS / 100;

enum TubesChannel : uint8_t {
  ControlChannel = 0x10,
  BeatChannel = 0x11,
  PatternChannel = 0x12,
  PaletteChannel = 0x13,
};

enum TubesChannelMessageKind : uint8_t {
  ChannelRequest = 1,
  ChannelDeclaration = 2,
  ControlBeacon = 3,
};

#pragma pack(push, 1)
struct TubesChannelEnvelope {
  uint8_t channelVersion = TUBES_CHANNEL_VERSION_1;
  uint8_t messageKind = ChannelRequest;
  uint8_t flags = 0;
  uint8_t bodyLength = 0;
  DeviceId channelId = 0;
  DeviceId sourceControlId = 0;
  uint32_t sourceSession = 0;
  uint16_t sequence = 0;
  uint16_t leaseDeciseconds = TUBES_CHANNEL_LEASE_DECISECONDS;
};

struct TubesChannelPayload {
  TubesChannelEnvelope envelope;
  uint8_t body[TUBES_CHANNEL_BODY_SIZE] = {0};
};

struct BeatChannelState {
  accum88 bpm = 0;
  BeatFrame_24_8 beatFrame = 0;
};

struct PatternChannelEntry {
  uint16_t patternPhrase = 0;
  uint8_t patternId = 0;
  uint8_t syncMode = 0;
  uint16_t effectPhrase = 0;
  uint8_t effect = 0;
  uint8_t pen = 0;
  uint8_t beat = 0;
  uint8_t chance = 0;
};

struct PatternChannelState {
  PatternChannelEntry current;
  PatternChannelEntry next;
};

struct PaletteChannelEntry {
  uint16_t palettePhrase = 0;
  uint8_t paletteId = 0;
};

struct PaletteChannelState {
  PaletteChannelEntry current;
  PaletteChannelEntry next;
};

struct ControlChannelBody {
  CommandId command = 0;
  uint8_t commandLength = 0;
  uint8_t commandData[TUBES_CHANNEL_BODY_SIZE - 2] = {0};
};

struct ControlBeaconBody {
  uint32_t bootSession = 0;
  uint8_t maximumChannelVersion = TUBES_CHANNEL_VERSION_1;
  uint8_t reserved[3] = {0};
};
#pragma pack(pop)

static_assert(sizeof(TubesChannelEnvelope) == TUBES_CHANNEL_ENVELOPE_SIZE, "channel envelope wire size changed");
static_assert(sizeof(TubesChannelPayload) == MESSAGE_DATA_SIZE, "channel payload wire size changed");
static_assert(sizeof(BeatChannelState) <= TUBES_CHANNEL_BODY_SIZE, "Beat state exceeds channel body");
static_assert(sizeof(PatternChannelState) <= TUBES_CHANNEL_BODY_SIZE, "Pattern state exceeds channel body");
static_assert(sizeof(PaletteChannelState) <= TUBES_CHANNEL_BODY_SIZE, "Palette state exceeds channel body");

inline bool isKnownTubesChannel(uint8_t channel) {
  return channel >= ControlChannel && channel <= PaletteChannel;
}

inline bool isApplicationChannel(uint8_t channel) {
  return channel == BeatChannel || channel == PatternChannel || channel == PaletteChannel;
}

inline bool isValidChannelEnvelope(const TubesChannelEnvelope& envelope) {
  if (envelope.channelVersion != TUBES_CHANNEL_VERSION_1
      || envelope.bodyLength > TUBES_CHANNEL_BODY_SIZE
      || envelope.sourceControlId == 0
      || protocolGenerationFromId(envelope.sourceControlId) < CHANNEL_PROTOCOL_GENERATION
      || protocolGenerationFromId(envelope.channelId) < CHANNEL_PROTOCOL_GENERATION)
    return false;
  if (envelope.messageKind != ChannelRequest
      && envelope.messageKind != ChannelDeclaration
      && envelope.messageKind != ControlBeacon)
    return false;
  if (envelope.messageKind == ControlBeacon)
    return envelope.channelId == envelope.sourceControlId
        && envelope.flags == 0
        && envelope.leaseDeciseconds == 0;
  return envelope.channelId != 0
      && envelope.leaseDeciseconds > 0
      && envelope.leaseDeciseconds <= TUBES_CHANNEL_LEASE_DECISECONDS
      && envelope.flags == 0;
}

inline bool hasExpectedChannelBodyLength(uint8_t channel, const TubesChannelPayload& payload) {
  if (payload.envelope.messageKind == ControlBeacon)
    return channel == ControlChannel && payload.envelope.bodyLength == sizeof(ControlBeaconBody);
  switch (channel) {
    case BeatChannel: return payload.envelope.bodyLength == sizeof(BeatChannelState);
    case PatternChannel: return payload.envelope.bodyLength == sizeof(PatternChannelState);
    case PaletteChannel: return payload.envelope.bodyLength == sizeof(PaletteChannelState);
    case ControlChannel: {
      if (payload.envelope.bodyLength < 2)
        return false;
      ControlChannelBody body;
      memset(&body, 0, sizeof(body));
      memcpy(&body, payload.body, payload.envelope.bodyLength);
      return body.commandLength <= sizeof(body.commandData)
          && payload.envelope.bodyLength == uint8_t(body.commandLength + 2);
    }
    default: return false;
  }
}

inline bool isValidTubesChannelPayload(uint8_t channel, const TubesChannelPayload& payload) {
  return isKnownTubesChannel(channel)
      && isValidChannelEnvelope(payload.envelope)
      && hasExpectedChannelBodyLength(channel, payload);
}

template<typename T>
inline bool readChannelBody(const TubesChannelPayload& payload, T& value) {
  if (payload.envelope.bodyLength != sizeof(T) || sizeof(T) > sizeof(payload.body))
    return false;
  memcpy(&value, payload.body, sizeof(T));
  return true;
}

inline bool writeChannelBody(TubesChannelPayload& payload, const void* body, uint8_t bodyLength) {
  if (bodyLength > sizeof(payload.body) || (bodyLength && body == nullptr))
    return false;
  memset(payload.body, 0, sizeof(payload.body));
  if (bodyLength)
    memcpy(payload.body, body, bodyLength);
  payload.envelope.bodyLength = bodyLength;
  return true;
}

struct ChannelAuthority {
  DeviceId channelId = 0;
  DeviceId controlId = 0;
};

inline int compareChannelAuthority(const ChannelAuthority& first, const ChannelAuthority& second) {
  if (first.channelId != second.channelId)
    return first.channelId > second.channelId ? 1 : -1;
  if (first.controlId != second.controlId)
    return first.controlId > second.controlId ? 1 : -1;
  return 0;
}

inline ChannelAuthority channelAuthority(const TubesChannelEnvelope& envelope) {
  ChannelAuthority authority;
  authority.channelId = envelope.channelId;
  authority.controlId = envelope.sourceControlId;
  return authority;
}

inline bool channelDeadlineReached(uint32_t nowMs, uint32_t deadlineMs) {
  return int32_t(nowMs - deadlineMs) >= 0;
}

struct ChannelWinner {
  bool active = false;
  ChannelAuthority authority;
  uint32_t sourceSession = 0;
  uint16_t sequence = 0;
  uint32_t expiresAtMs = 0;
};

class ChannelWinnerTable {
  public:
    bool acceptRequest(uint8_t channel, const TubesChannelEnvelope& envelope, uint32_t nowMs) {
      if (!isApplicationChannel(channel) || envelope.messageKind != ChannelRequest)
        return false;
      ChannelWinner& winner = entries[indexFor(channel)];
      expireOne(winner, nowMs);
      ChannelAuthority candidate = channelAuthority(envelope);
      bool sameSource = winner.active
          && winner.authority.channelId == candidate.channelId
          && winner.authority.controlId == candidate.controlId
          && winner.sourceSession == envelope.sourceSession;
      if (winner.active && !sameSource && compareChannelAuthority(candidate, winner.authority) <= 0)
        return false;
      if (sameSource && !sequenceIsNewer(envelope.sequence, winner.sequence))
        return false;
      setWinner(winner, envelope, nowMs);
      return true;
    }

    bool acceptDeclaration(uint8_t channel, const TubesChannelEnvelope& envelope, uint32_t nowMs) {
      if (!isApplicationChannel(channel) || envelope.messageKind != ChannelDeclaration)
        return false;
      ChannelWinner& winner = entries[indexFor(channel)];
      bool sameSource = winner.active
          && winner.authority.channelId == envelope.channelId
          && winner.authority.controlId == envelope.sourceControlId
          && winner.sourceSession == envelope.sourceSession;
      if (sameSource && !sequenceIsNewer(envelope.sequence, winner.sequence))
        return false;
      setWinner(winner, envelope, nowMs);
      return true;
    }

    const ChannelWinner& get(uint8_t channel, uint32_t nowMs) {
      static const ChannelWinner empty;
      if (!isApplicationChannel(channel)) return empty;
      ChannelWinner& winner = entries[indexFor(channel)];
      expireOne(winner, nowMs);
      return winner;
    }

    bool localMayRequest(uint8_t channel, DeviceId localChannelId, DeviceId localControlId, uint32_t nowMs) {
      const ChannelWinner& winner = get(channel, nowMs);
      if (!winner.active) return true;
      ChannelAuthority local;
      local.channelId = localChannelId;
      local.controlId = localControlId;
      return compareChannelAuthority(local, winner.authority) >= 0;
    }

    void clear() {
      for (ChannelWinner& winner : entries)
        winner = ChannelWinner();
    }

    void clear(uint8_t channel) {
      if (isApplicationChannel(channel))
        entries[indexFor(channel)] = ChannelWinner();
    }

  private:
    ChannelWinner entries[3];

    static uint8_t indexFor(uint8_t channel) {
      return channel - BeatChannel;
    }

    static bool sequenceIsNewer(uint16_t candidate, uint16_t previous) {
      return candidate != previous && int16_t(candidate - previous) > 0;
    }

    static void setWinner(ChannelWinner& winner, const TubesChannelEnvelope& envelope, uint32_t nowMs) {
      winner.active = true;
      winner.authority = channelAuthority(envelope);
      winner.sourceSession = envelope.sourceSession;
      winner.sequence = envelope.sequence;
      winner.expiresAtMs = nowMs + uint32_t(envelope.leaseDeciseconds) * 100U;
    }

    static void expireOne(ChannelWinner& winner, uint32_t nowMs) {
      if (winner.active && channelDeadlineReached(nowMs, winner.expiresAtMs))
        winner = ChannelWinner();
    }
};

// AI: end
