#pragma once

#include <stddef.h>
#include <stdint.h>
#include <string.h>

#include "mesh_protocol.h"

// AI: below section was generated by an AI

constexpr uint8_t TUBES_CHANNEL_VERSION_1 = 1;
constexpr uint8_t TUBES_CHANNEL_VERSION_2 = 2;
constexpr uint16_t TUBES_CHANNEL_MAGIC = 0x4354; // "TC" little-endian.
constexpr uint8_t TUBES_CHANNEL_ENVELOPE_SIZE = 16;
constexpr uint8_t TUBES_CHANNEL_BODY_SIZE = MESSAGE_DATA_SIZE - TUBES_CHANNEL_ENVELOPE_SIZE;
constexpr uint16_t TUBES_ESPNOW_MAX_MESSAGE_SIZE = 250;
constexpr uint8_t TUBES_NODE_MESSAGE_PREFIX_SIZE = offsetof(NodeMessage, data);
constexpr uint32_t TUBES_CHANNEL_LEASE_MS = 20000;
constexpr uint16_t TUBES_CHANNEL_LEASE_DECISECONDS = TUBES_CHANNEL_LEASE_MS / 100;
constexpr uint8_t TUBES_BEAT_FRAME_PHRASE_SHIFT = 12;
constexpr uint8_t TUBES_BEAT_FRAME_FRACTION_SHIFT = 8;

// The first beat in each 16-beat phrase is the bounded mesh clock correction point.
constexpr bool isTubesMeasureDownbeat(uint32_t beatFrame) {
  return ((beatFrame >> TUBES_BEAT_FRAME_FRACTION_SHIFT) & 0x0F) == 0;
}

// Every pole invokes `pickDelay` and retains the resulting speculative schedule.
// Channel authority decides only whether that local schedule may be published.
template<typename DelayPicker>
bool scheduleSpeculativeChannelChange(
    uint16_t currentPhrase,
    uint16_t& effectivePhrase,
    bool mayPublish,
    DelayPicker pickDelay
) {
  effectivePhrase = currentPhrase + pickDelay();
  return mayPublish;
}

enum TubesChannel : uint8_t {
  ControlChannel = 0x10,
  BeatChannel = 0x11,
  PatternChannel = 0x12,
  PaletteChannel = 0x13,
};

enum TubesChannelMessageKind : uint8_t {
  ChannelRequest = 1,
  ChannelDeclaration = 2,
  ControlBeacon = 3,
};

#pragma pack(push, 1)
struct TubesChannelEnvelope {
  uint8_t channelVersion = TUBES_CHANNEL_VERSION_1;
  uint8_t messageKind = ChannelRequest;
  uint8_t flags = 0;
  uint8_t bodyLength = 0;
  DeviceId channelId = 0;
  DeviceId sourceControlId = 0;
  uint32_t sourceSession = 0;
  uint16_t sequence = 0;
  uint16_t leaseDeciseconds = TUBES_CHANNEL_LEASE_DECISECONDS;
};

struct TubesChannelPayload {
  TubesChannelEnvelope envelope;
  uint8_t body[TUBES_CHANNEL_BODY_SIZE] = {0};
};

// Version 2 channel packets retain the deployed mesh prefix but carry a magic-tagged,
// variable-length body. The received byte count is part of validation at ESP-NOW ingress.
struct TubesChannelEnvelopeV2 {
  uint16_t magic = TUBES_CHANNEL_MAGIC;
  uint8_t channelVersion = TUBES_CHANNEL_VERSION_2;
  uint8_t messageKind = ChannelRequest;
  uint8_t flags = 0;
  uint8_t bodyLength = 0;
  DeviceId channelId = 0;
  DeviceId sourceControlId = 0;
  uint32_t sourceSession = 0;
  uint16_t sequence = 0;
  uint16_t leaseDeciseconds = TUBES_CHANNEL_LEASE_DECISECONDS;
};

struct BeatChannelState {
  uint16_t bpm = 0;
  uint32_t beatFrame = 0;
};

enum SoundProgramFlag : uint8_t {
  SoundProgramEnabled = 1 << 0,
};

enum SoundProgramOption : uint8_t {
  SoundProgramCheck1 = 1 << 0,
  SoundProgramCheck2 = 1 << 1,
  SoundProgramCheck3 = 1 << 2,
};

struct SoundProgramEntry {
  uint16_t effectivePhrase = 0;
  uint8_t flags = 0;
  uint8_t wledEffect = 0;
  uint8_t palette = 0;
  uint8_t speed = 0;
  uint8_t intensity = 0;
  uint8_t custom1 = 0;
  uint8_t custom2 = 0;
  uint8_t custom3 = 0;
  uint8_t options = 0;
  uint8_t blendMode = 0;
  uint8_t opacity = 0;
};

constexpr uint32_t BEAT_SOUND_PROGRAM_MAGIC = 0x31504453; // "SDP1" little-endian.
constexpr uint8_t BEAT_SOUND_PROGRAM_VERSION_1 = 1;

struct BeatSoundProgramExtension {
  uint32_t magic = BEAT_SOUND_PROGRAM_MAGIC;
  uint8_t version = BEAT_SOUND_PROGRAM_VERSION_1;
  uint8_t length = sizeof(SoundProgramEntry) * 2;
  uint8_t reserved[2] = {0};
  SoundProgramEntry current;
  SoundProgramEntry next;
};

constexpr uint16_t BEAT_TRANSIENT_MAGIC = 0x5442; // "BT" little-endian.
constexpr uint8_t BEAT_TRANSIENT_VERSION_1 = 1;

struct BeatTransientExtension {
  uint16_t magic = BEAT_TRANSIENT_MAGIC;
  uint8_t version = BEAT_TRANSIENT_VERSION_1;
  uint8_t sequence = 0;
  uint8_t kick = 0;
  uint8_t snare = 0;
  uint8_t music = 0;
  uint8_t reserved = 0;
};

struct PatternChannelEntry {
  uint16_t patternPhrase = 0;
  uint8_t patternId = 0;
  uint8_t syncMode = 0;
  uint16_t effectPhrase = 0;
  uint8_t effect = 0;
  uint8_t pen = 0;
  uint8_t beat = 0;
  uint8_t chance = 0;
};

struct PatternChannelState {
  PatternChannelEntry current;
  PatternChannelEntry next;
};

struct PaletteChannelEntry {
  uint16_t palettePhrase = 0;
  uint8_t paletteId = 0;
};

struct PaletteChannelState {
  PaletteChannelEntry current;
  PaletteChannelEntry next;
};

struct PaletteGradientStop {
  uint8_t position = 0;
  uint8_t red = 0;
  uint8_t green = 0;
  uint8_t blue = 0;
};

struct PaletteGradientDefinition {
  uint8_t count = 0;
  PaletteGradientStop stops[8];
};

struct PaletteGradient16 {
  uint8_t rgb[16][3] = {{0}};
};

struct PaletteChannelSchedule {
  PaletteChannelState state;
  uint16_t currentDefinitionSequence = 0;
  uint16_t nextDefinitionSequence = 0;
};

struct BeatChannelSnapshot {
  BeatChannelState state;
  BeatSoundProgramExtension soundProgram;
  BeatTransientExtension transient;
};

struct PaletteChannelSnapshot {
  PaletteChannelState state;
  uint16_t transitionMs = 0;
  PaletteGradient16 currentDefinition;
  PaletteGradient16 nextDefinition;
};

struct ControlChannelBody {
  CommandId command = 0;
  uint8_t commandLength = 0;
  uint8_t commandData[TUBES_CHANNEL_BODY_SIZE - 2] = {0};
};

struct ControlBeaconBody {
  uint32_t bootSession = 0;
  uint8_t maximumChannelVersion = TUBES_CHANNEL_VERSION_2;
  uint8_t reserved[3] = {0};
};
#pragma pack(pop)

#pragma pack(push, 4)
// The prefix layout intentionally matches NodeMessage through command. Only the
// version-2 envelope and body use the new variable-length channel contract.
struct TubesChannelMessageV2 {
  MeshNodeHeader header;
  MessageRecipients recipients = RECIPIENTS_ALL;
  uint32_t timebase = 0;
  CommandId command = 0;
  TubesChannelEnvelopeV2 envelope;
  uint8_t body[TUBES_ESPNOW_MAX_MESSAGE_SIZE
      - TUBES_NODE_MESSAGE_PREFIX_SIZE
      - sizeof(TubesChannelEnvelopeV2)] = {0};
};
#pragma pack(pop)

static_assert(sizeof(TubesChannelEnvelope) == TUBES_CHANNEL_ENVELOPE_SIZE, "channel envelope wire size changed");
static_assert(sizeof(TubesChannelPayload) == MESSAGE_DATA_SIZE, "channel payload wire size changed");
static_assert(sizeof(TubesChannelEnvelopeV2) == 18, "variable channel envelope wire size changed");
static_assert(offsetof(TubesChannelMessageV2, envelope) == TUBES_NODE_MESSAGE_PREFIX_SIZE,
              "variable channel mesh prefix changed");
static_assert(offsetof(TubesChannelMessageV2, body)
              + sizeof(((TubesChannelMessageV2*)nullptr)->body)
              == TUBES_ESPNOW_MAX_MESSAGE_SIZE,
              "variable channel packet no longer fills the ESP-NOW payload limit");
static_assert(sizeof(SoundProgramEntry) == 13, "sound program wire size changed");
static_assert(sizeof(BeatSoundProgramExtension) == 34, "Beat sound extension wire size changed");
static_assert(sizeof(BeatTransientExtension) == 8, "Beat transient extension wire size changed");
static_assert(sizeof(BeatChannelState) <= TUBES_CHANNEL_BODY_SIZE, "Beat state exceeds channel body");
static_assert(sizeof(BeatChannelState) + sizeof(BeatSoundProgramExtension) + sizeof(BeatTransientExtension)
              == TUBES_CHANNEL_BODY_SIZE, "Beat extensions must fill the channel body");
static_assert(sizeof(PatternChannelState) <= TUBES_CHANNEL_BODY_SIZE, "Pattern state exceeds channel body");
static_assert(sizeof(PaletteChannelState) <= TUBES_CHANNEL_BODY_SIZE, "Palette state exceeds channel body");
static_assert(sizeof(PaletteGradientDefinition) == 33, "Palette gradient wire size changed");
static_assert(sizeof(PaletteGradient16) == TUBES_CHANNEL_BODY_SIZE,
              "Palette16 definition must fill one channel body");
static_assert(sizeof(PaletteChannelSchedule) == 10, "Palette schedule wire size changed");
static_assert(sizeof(BeatChannelSnapshot) == 48, "Beat snapshot wire size changed");
static_assert(sizeof(PaletteChannelSnapshot) == 104, "Palette snapshot wire size changed");
static_assert(offsetof(TubesChannelMessageV2, body) + sizeof(PaletteChannelSnapshot)
              <= TUBES_ESPNOW_MAX_MESSAGE_SIZE,
              "Palette snapshot exceeds one ESP-NOW packet");

inline bool isKnownTubesChannel(uint8_t channel) {
  return channel >= ControlChannel && channel <= PaletteChannel;
}

inline bool isApplicationChannel(uint8_t channel) {
  return channel == BeatChannel || channel == PatternChannel || channel == PaletteChannel;
}

inline uint16_t tubesPhraseForBeatFrame(uint32_t beatFrame) {
  return beatFrame >> TUBES_BEAT_FRAME_PHRASE_SHIFT;
}

// State-changing requests target the next whole phrase; current entries remain
// snapshots that late receivers may apply immediately to catch up.
inline uint16_t nextTubesPhraseBoundary(uint32_t beatFrame) {
  return tubesPhraseForBeatFrame(beatFrame) + 1;
}

inline uint16_t shiftScheduledPhrase(
    uint16_t scheduledPhrase,
    uint16_t earliestPhrase,
    uint16_t targetPhrase
) {
  if (scheduledPhrase == UINT16_MAX)
    return UINT16_MAX;
  return scheduledPhrase + uint16_t(targetPhrase - earliestPhrase);
}

inline bool isValidChannelEnvelope(const TubesChannelEnvelope& envelope) {
  if (envelope.channelVersion != TUBES_CHANNEL_VERSION_1
      || envelope.bodyLength > TUBES_CHANNEL_BODY_SIZE
      || envelope.sourceControlId == 0
      || protocolGenerationFromId(envelope.sourceControlId) < CHANNEL_PROTOCOL_GENERATION
      || protocolGenerationFromId(envelope.channelId) < CHANNEL_PROTOCOL_GENERATION)
    return false;
  if (envelope.messageKind != ChannelRequest
      && envelope.messageKind != ChannelDeclaration
      && envelope.messageKind != ControlBeacon)
    return false;
  if (envelope.messageKind == ControlBeacon)
    return envelope.channelId == envelope.sourceControlId
        && envelope.flags == 0
        && envelope.leaseDeciseconds == 0;
  return envelope.channelId != 0
      && envelope.leaseDeciseconds > 0
      && envelope.leaseDeciseconds <= TUBES_CHANNEL_LEASE_DECISECONDS
      && envelope.flags == 0;
}

inline bool isValidChannelEnvelope(const TubesChannelEnvelopeV2& envelope) {
  if (envelope.magic != TUBES_CHANNEL_MAGIC
      || envelope.channelVersion != TUBES_CHANNEL_VERSION_2
      || envelope.sourceControlId == 0
      || envelope.sourceSession == 0
      || protocolGenerationFromId(envelope.sourceControlId) < CHANNEL_PROTOCOL_GENERATION
      || protocolGenerationFromId(envelope.channelId) < CHANNEL_PROTOCOL_GENERATION)
    return false;
  if (envelope.messageKind != ChannelRequest && envelope.messageKind != ChannelDeclaration)
    return false;
  return envelope.channelId != 0
      && envelope.leaseDeciseconds > 0
      && envelope.leaseDeciseconds <= TUBES_CHANNEL_LEASE_DECISECONDS
      && envelope.flags == 0;
}

inline uint8_t expectedChannelSnapshotBodyLength(uint8_t channel) {
  switch (channel) {
    case BeatChannel: return sizeof(BeatChannelSnapshot);
    case PatternChannel: return sizeof(PatternChannelState);
    case PaletteChannel: return sizeof(PaletteChannelSnapshot);
    default: return 0;
  }
}

inline size_t channelMessageV2WireSize(uint8_t bodyLength) {
  return offsetof(TubesChannelMessageV2, body) + bodyLength;
}

// This bounded ingress check runs in the Wi-Fi task before a packet is copied into
// WLED's ring buffer. It only reads fields proven present by the preceding length test.
inline bool isValidChannelMessageV2Prefix(const uint8_t* data, size_t length) {
  if (!data || length < offsetof(TubesChannelMessageV2, body)
      || length > TUBES_ESPNOW_MAX_MESSAGE_SIZE)
    return false;

  constexpr size_t versionOffset = offsetof(TubesChannelMessageV2, header)
      + offsetof(MeshNodeHeader, version);
  constexpr size_t commandOffset = offsetof(TubesChannelMessageV2, command);
  constexpr size_t envelopeOffset = offsetof(TubesChannelMessageV2, envelope);
  if (data[versionOffset] != TUBES_PROTOCOL_V3
      || !isApplicationChannel(data[commandOffset])
      || data[envelopeOffset] != uint8_t(TUBES_CHANNEL_MAGIC)
      || data[envelopeOffset + 1] != uint8_t(TUBES_CHANNEL_MAGIC >> 8)
      || data[envelopeOffset + 2] != TUBES_CHANNEL_VERSION_2)
    return false;

  TubesChannelEnvelopeV2 envelope;
  memcpy(&envelope, data + envelopeOffset, sizeof(envelope));
  if (!isValidChannelEnvelope(envelope)
      || envelope.bodyLength != expectedChannelSnapshotBodyLength(data[commandOffset])
      || channelMessageV2WireSize(envelope.bodyLength) != length)
    return false;

  MessageRecipients recipients;
  memcpy(&recipients, data + offsetof(TubesChannelMessageV2, recipients), sizeof(recipients));
  if (recipients != RECIPIENTS_ALL && recipients != RECIPIENTS_ROOT)
    return false;
  return envelope.messageKind == (recipients == RECIPIENTS_ROOT
      ? ChannelRequest
      : ChannelDeclaration);
}

template<typename Body>
inline bool writeChannelMessageV2Body(TubesChannelMessageV2& message, const Body& body) {
  static_assert(sizeof(Body) <= sizeof(message.body), "channel snapshot exceeds ESP-NOW body");
  if (sizeof(Body) != expectedChannelSnapshotBodyLength(message.command))
    return false;
  memcpy(message.body, &body, sizeof(body));
  message.envelope.bodyLength = sizeof(body);
  return true;
}

template<typename Body>
inline bool readChannelMessageV2Body(const TubesChannelMessageV2& message, Body& body) {
  if (message.envelope.bodyLength != sizeof(Body)
      || sizeof(Body) != expectedChannelSnapshotBodyLength(message.command))
    return false;
  memcpy(&body, message.body, sizeof(body));
  return true;
}

inline bool hasExpectedChannelBodyLength(uint8_t channel, const TubesChannelPayload& payload) {
  if (payload.envelope.messageKind == ControlBeacon)
    return channel == ControlChannel
        && payload.envelope.channelVersion == TUBES_CHANNEL_VERSION_1
        && payload.envelope.bodyLength == sizeof(ControlBeaconBody);
  switch (channel) {
    case BeatChannel: return payload.envelope.bodyLength == sizeof(BeatChannelState);
    case PatternChannel:
      return payload.envelope.channelVersion == TUBES_CHANNEL_VERSION_1
          && payload.envelope.bodyLength == sizeof(PatternChannelState);
    case PaletteChannel:
      if (payload.envelope.channelVersion != TUBES_CHANNEL_VERSION_1)
        return false;
      return payload.envelope.bodyLength == sizeof(PaletteChannelState)
          || payload.envelope.bodyLength == sizeof(PaletteGradient16)
          || payload.envelope.bodyLength == sizeof(PaletteChannelSchedule);
    case ControlChannel: {
      if (payload.envelope.channelVersion != TUBES_CHANNEL_VERSION_1)
        return false;
      if (payload.envelope.bodyLength < 2)
        return false;
      ControlChannelBody body;
      memset(&body, 0, sizeof(body));
      memcpy(&body, payload.body, payload.envelope.bodyLength);
      return body.commandLength <= sizeof(body.commandData)
          && payload.envelope.bodyLength == uint8_t(body.commandLength + 2);
    }
    default: return false;
  }
}

inline bool isValidTubesChannelPayload(uint8_t channel, const TubesChannelPayload& payload) {
  return isKnownTubesChannel(channel)
      && isValidChannelEnvelope(payload.envelope)
      && hasExpectedChannelBodyLength(channel, payload);
}

template<typename T>
inline bool readChannelBody(const TubesChannelPayload& payload, T& value) {
  if (payload.envelope.bodyLength != sizeof(T) || sizeof(T) > sizeof(payload.body))
    return false;
  memcpy(&value, payload.body, sizeof(T));
  return true;
}

inline bool writeChannelBody(TubesChannelPayload& payload, const void* body, uint8_t bodyLength) {
  if (bodyLength > sizeof(payload.body) || (bodyLength && body == nullptr))
    return false;
  memset(payload.body, 0, sizeof(payload.body));
  if (bodyLength)
    memcpy(payload.body, body, bodyLength);
  payload.envelope.bodyLength = bodyLength;
  return true;
}

inline bool hasBeatSoundProgramExtension(const TubesChannelPayload& payload) {
  if (payload.envelope.bodyLength != sizeof(BeatChannelState))
    return false;
  uint32_t magic = 0;
  memcpy(&magic, payload.body + sizeof(BeatChannelState), sizeof(magic));
  return magic == BEAT_SOUND_PROGRAM_MAGIC;
}

inline bool readBeatSoundProgramExtension(
    const TubesChannelPayload& payload,
    BeatSoundProgramExtension& extension
) {
  if (!hasBeatSoundProgramExtension(payload))
    return false;
  memcpy(
      &extension,
      payload.body + sizeof(BeatChannelState),
      sizeof(extension)
  );
  return extension.version == BEAT_SOUND_PROGRAM_VERSION_1
      && extension.length == sizeof(SoundProgramEntry) * 2
      && extension.reserved[0] == 0
      && extension.reserved[1] == 0;
}

inline bool writeBeatSoundProgramExtension(
    TubesChannelPayload& payload,
    const BeatSoundProgramExtension& extension
) {
  if (payload.envelope.bodyLength != sizeof(BeatChannelState)
      || extension.magic != BEAT_SOUND_PROGRAM_MAGIC
      || extension.version != BEAT_SOUND_PROGRAM_VERSION_1
      || extension.length != sizeof(SoundProgramEntry) * 2)
    return false;
  memcpy(
      payload.body + sizeof(BeatChannelState),
      &extension,
      sizeof(extension)
  );
  return true;
}

inline bool hasBeatTransientExtension(const TubesChannelPayload& payload) {
  uint16_t magic = 0;
  constexpr size_t offset = sizeof(BeatChannelState) + sizeof(BeatSoundProgramExtension);
  memcpy(&magic, payload.body + offset, sizeof(magic));
  return magic == BEAT_TRANSIENT_MAGIC;
}

// Reads the additive transient trailer that old generation-1 nodes safely relay as padding.
inline bool readBeatTransientExtension(
    const TubesChannelPayload& payload,
    BeatTransientExtension& extension
) {
  if (!hasBeatTransientExtension(payload))
    return false;
  constexpr size_t offset = sizeof(BeatChannelState) + sizeof(BeatSoundProgramExtension);
  memcpy(&extension, payload.body + offset, sizeof(extension));
  return extension.version == BEAT_TRANSIENT_VERSION_1 && extension.reserved == 0;
}

inline bool writeBeatTransientExtension(
    TubesChannelPayload& payload,
    const BeatTransientExtension& extension
) {
  if (payload.envelope.bodyLength != sizeof(BeatChannelState)
      || extension.magic != BEAT_TRANSIENT_MAGIC
      || extension.version != BEAT_TRANSIENT_VERSION_1
      || extension.reserved != 0)
    return false;
  constexpr size_t offset = sizeof(BeatChannelState) + sizeof(BeatSoundProgramExtension);
  memcpy(payload.body + offset, &extension, sizeof(extension));
  return true;
}

// Expands a validated piecewise-linear gradient into the palette used by renderers.
inline bool expandPaletteGradient(
    const PaletteGradientDefinition& gradient,
    PaletteGradient16& palette
) {
  if (gradient.count < 2 || gradient.count > 8)
    return false;
  if (gradient.stops[0].position != 0
      || gradient.stops[gradient.count - 1].position != 255)
    return false;
  for (uint8_t stop = 1; stop < gradient.count; stop++) {
    if (gradient.stops[stop].position < gradient.stops[stop - 1].position)
      return false;
  }

  // Match CRGBPalette16::loadDynamicGradientPalette(), including its handling of
  // repeated positions used by WLED palettes to preserve hard color boundaries.
  int8_t lastSlotUsed = -1;
  for (uint8_t stop = 1; stop < gradient.count; stop++) {
    const PaletteGradientStop& first = gradient.stops[stop - 1];
    const PaletteGradientStop& second = gradient.stops[stop];
    uint8_t firstSlot = first.position / 16;
    uint8_t secondSlot = second.position / 16;
    if (gradient.count < 16 && firstSlot <= lastSlotUsed && lastSlotUsed < 15) {
      firstSlot = lastSlotUsed + 1;
      if (secondSlot < firstSlot)
        secondSlot = firstSlot;
    }
    lastSlotUsed = secondSlot;
    uint8_t span = secondSlot - firstSlot;
    int16_t divisor = span ? span : 1;
    int16_t redDelta = (int16_t(second.red - first.red) * 128) / divisor * 2;
    int16_t greenDelta = (int16_t(second.green - first.green) * 128) / divisor * 2;
    int16_t blueDelta = (int16_t(second.blue - first.blue) * 128) / divisor * 2;
    int32_t red = int32_t(first.red) << 8;
    int32_t green = int32_t(first.green) << 8;
    int32_t blue = int32_t(first.blue) << 8;
    for (uint8_t slot = firstSlot; slot <= secondSlot; slot++) {
      palette.rgb[slot][0] = red >> 8;
      palette.rgb[slot][1] = green >> 8;
      palette.rgb[slot][2] = blue >> 8;
      red += redDelta;
      green += greenDelta;
      blue += blueDelta;
    }
  }
  return true;
}

inline uint32_t paletteGradientFingerprint(const PaletteGradient16& palette) {
  uint32_t hash = 2166136261U;
  for (const auto& color : palette.rgb) {
    for (uint8_t component : color) {
      hash ^= component;
      hash *= 16777619U;
    }
  }
  return hash;
}

struct ChannelAuthority {
  DeviceId channelId = 0;
  DeviceId controlId = 0;
};

inline int compareChannelAuthority(const ChannelAuthority& first, const ChannelAuthority& second) {
  if (first.channelId != second.channelId)
    return first.channelId > second.channelId ? 1 : -1;
  if (first.controlId != second.controlId)
    return first.controlId > second.controlId ? 1 : -1;
  return 0;
}

template<typename Envelope>
inline ChannelAuthority channelAuthority(const Envelope& envelope) {
  ChannelAuthority authority;
  authority.channelId = envelope.channelId;
  authority.controlId = envelope.sourceControlId;
  return authority;
}

inline bool channelDeadlineReached(uint32_t nowMs, uint32_t deadlineMs) {
  return int32_t(nowMs - deadlineMs) >= 0;
}

struct ChannelWinner {
  bool active = false;
  ChannelAuthority authority;
  uint32_t sourceSession = 0;
  uint16_t sequence = 0;
  uint32_t expiresAtMs = 0;
};

class ChannelWinnerTable {
  public:
    template<typename Envelope>
    bool acceptRequest(uint8_t channel, const Envelope& envelope, uint32_t nowMs) {
      if (!isApplicationChannel(channel) || envelope.messageKind != ChannelRequest)
        return false;
      ChannelWinner& winner = entries[indexFor(channel)];
      expireOne(winner, nowMs);
      ChannelAuthority candidate = channelAuthority(envelope);
      bool sameSource = winner.active
          && winner.authority.channelId == candidate.channelId
          && winner.authority.controlId == candidate.controlId
          && winner.sourceSession == envelope.sourceSession;
      if (winner.active && !sameSource && compareChannelAuthority(candidate, winner.authority) <= 0)
        return false;
      if (sameSource && !sequenceIsNewer(envelope.sequence, winner.sequence))
        return false;
      setWinner(winner, envelope, nowMs);
      return true;
    }

    template<typename Envelope>
    bool acceptDeclaration(uint8_t channel, const Envelope& envelope, uint32_t nowMs) {
      if (!isApplicationChannel(channel) || envelope.messageKind != ChannelDeclaration)
        return false;
      ChannelWinner& winner = entries[indexFor(channel)];
      bool sameSource = winner.active
          && winner.authority.channelId == envelope.channelId
          && winner.authority.controlId == envelope.sourceControlId
          && winner.sourceSession == envelope.sourceSession;
      if (sameSource && !sequenceIsNewer(envelope.sequence, winner.sequence))
        return false;
      setWinner(winner, envelope, nowMs);
      return true;
    }

    const ChannelWinner& get(uint8_t channel, uint32_t nowMs) {
      static const ChannelWinner empty;
      if (!isApplicationChannel(channel)) return empty;
      ChannelWinner& winner = entries[indexFor(channel)];
      expireOne(winner, nowMs);
      return winner;
    }

    bool localMayRequest(uint8_t channel, DeviceId localChannelId, DeviceId localControlId, uint32_t nowMs) {
      const ChannelWinner& winner = get(channel, nowMs);
      if (!winner.active) return true;
      ChannelAuthority local;
      local.channelId = localChannelId;
      local.controlId = localControlId;
      return compareChannelAuthority(local, winner.authority) >= 0;
    }

    void clear() {
      for (ChannelWinner& winner : entries)
        winner = ChannelWinner();
    }

    void clear(uint8_t channel) {
      if (isApplicationChannel(channel))
        entries[indexFor(channel)] = ChannelWinner();
    }

  private:
    ChannelWinner entries[3];

    static uint8_t indexFor(uint8_t channel) {
      return channel - BeatChannel;
    }

    static bool sequenceIsNewer(uint16_t candidate, uint16_t previous) {
      return candidate != previous && int16_t(candidate - previous) > 0;
    }

    template<typename Envelope>
    static void setWinner(ChannelWinner& winner, const Envelope& envelope, uint32_t nowMs) {
      winner.active = true;
      winner.authority = channelAuthority(envelope);
      winner.sourceSession = envelope.sourceSession;
      winner.sequence = envelope.sequence;
      winner.expiresAtMs = nowMs + uint32_t(envelope.leaseDeciseconds) * 100U;
    }

    static void expireOne(ChannelWinner& winner, uint32_t nowMs) {
      if (winner.active && channelDeadlineReached(nowMs, winner.expiresAtMs))
        winner = ChannelWinner();
    }
};

// AI: end
