#pragma once

#include <stdint.h>
#include <string.h>

#include "v3_authority.h"
#include "v3_protocol.h"

// AI: below section was generated by an AI

constexpr uint32_t V3_CLAIM_REPEAT_MS = 10000;
constexpr uint16_t V3_DEFAULT_TOPIC_LEASE_DECISECONDS = 300;
constexpr uint8_t V3_POSITION_PEER_CAPACITY = 8;
constexpr uint32_t V3_POSITION_PEER_TIMEOUT_MS = 5000;

struct V3ProtocolCounters {
  uint32_t accepted = 0;
  uint32_t rejected = 0;
  uint32_t stale = 0;
  uint32_t unknown = 0;
  uint32_t legacyPackets = 0;
};

struct V3PaletteDefinitionKey {
  DeviceId authorityId = 0;
  uint32_t authoritySession = 0;
  uint16_t sequence = 0;
};

struct V3PaletteCacheEntry {
  bool valid = false;
  V3PaletteDefinitionKey key;
  V3Palette16Definition definition;
};

class V3PaletteCache {
  public:
    void store(const V3TopicEnvelope& envelope, const V3Palette16Definition& definition) {
      uint8_t destination = 0;
      if (entries[0].valid && !sameKey(entries[0].key, envelope))
        destination = 1;
      entries[destination].valid = true;
      entries[destination].key.authorityId = envelope.authorityId;
      entries[destination].key.authoritySession = envelope.authoritySession;
      entries[destination].key.sequence = envelope.sequence;
      entries[destination].definition = definition;
      if (destination == 1) {
        V3PaletteCacheEntry newest = entries[1];
        entries[1] = entries[0];
        entries[0] = newest;
      }
    }

    const V3Palette16Definition* find(
        DeviceId authorityId,
        uint32_t authoritySession,
        uint16_t sequence
    ) const {
      for (const V3PaletteCacheEntry& entry : entries) {
        if (entry.valid
            && entry.key.authorityId == authorityId
            && entry.key.authoritySession == authoritySession
            && entry.key.sequence == sequence)
          return &entry.definition;
      }
      return nullptr;
    }

    void clear() {
      entries[0] = V3PaletteCacheEntry();
      entries[1] = V3PaletteCacheEntry();
    }

  private:
    V3PaletteCacheEntry entries[2];

    static bool sameKey(const V3PaletteDefinitionKey& key, const V3TopicEnvelope& envelope) {
      return key.authorityId == envelope.authorityId
          && key.authoritySession == envelope.authoritySession
          && key.sequence == envelope.sequence;
    }
};

// Expand bounded gradient stops into the canonical sixteen-color runtime palette.
inline bool expandV3Gradient(
    const V3GradientPaletteDefinition& gradient,
    V3Palette16Definition& palette
) {
  if (gradient.count < 2 || gradient.count > 8)
    return false;
  if (gradient.stops[0].position != 0 || gradient.stops[gradient.count - 1].position != 255)
    return false;
  for (uint8_t stop = 1; stop < gradient.count; stop++) {
    if (gradient.stops[stop].position <= gradient.stops[stop - 1].position)
      return false;
  }

  uint8_t right = 1;
  for (uint8_t index = 0; index < 16; index++) {
    uint8_t position = index == 15 ? 255 : uint16_t(index) * 255 / 15;
    while (right < gradient.count - 1 && position > gradient.stops[right].position)
      right++;
    const V3GradientStop& first = gradient.stops[right - 1];
    const V3GradientStop& second = gradient.stops[right];
    uint16_t span = second.position - first.position;
    uint16_t offset = position - first.position;
    palette.rgb[index][0] = first.red + int16_t(second.red - first.red) * offset / span;
    palette.rgb[index][1] = first.green + int16_t(second.green - first.green) * offset / span;
    palette.rgb[index][2] = first.blue + int16_t(second.blue - first.blue) * offset / span;
  }
  return true;
}

struct V3PositionPeer {
  bool valid = false;
  DeviceId senderId = 0;
  int8_t rssi = 0;
  uint32_t lastSeenMs = 0;
  V3PositionAdvertisementPayload advertisement;
};

class V3PositionPeers {
  public:
    // Retain only direct transmitters; relayed position advertisements never enter here.
    void observe(
        DeviceId senderId,
        int8_t rssi,
        uint32_t nowMs,
        const V3PositionAdvertisementPayload& advertisement
    ) {
      uint8_t destination = V3_POSITION_PEER_CAPACITY;
      uint8_t oldest = 0;
      for (uint8_t index = 0; index < V3_POSITION_PEER_CAPACITY; index++) {
        if (peers[index].valid && peers[index].senderId == senderId) {
          destination = index;
          break;
        }
        if (!peers[index].valid && destination == V3_POSITION_PEER_CAPACITY)
          destination = index;
        if (peers[index].lastSeenMs < peers[oldest].lastSeenMs)
          oldest = index;
      }
      if (destination == V3_POSITION_PEER_CAPACITY)
        destination = oldest;
      peers[destination].valid = true;
      peers[destination].senderId = senderId;
      peers[destination].rssi = rssi;
      peers[destination].lastSeenMs = nowMs;
      peers[destination].advertisement = advertisement;
    }

    const V3PositionPeer* entries() const {
      return peers;
    }

    void expire(uint32_t nowMs) {
      for (V3PositionPeer& peer : peers) {
        if (peer.valid && v3DeadlineReached(nowMs, peer.lastSeenMs + V3_POSITION_PEER_TIMEOUT_MS))
          peer = V3PositionPeer();
      }
    }

    void clear() {
      for (V3PositionPeer& peer : peers)
        peer = V3PositionPeer();
    }

  private:
    V3PositionPeer peers[V3_POSITION_PEER_CAPACITY];
};

struct V3PublisherState {
  uint16_t sequence = 0;
  uint32_t nextClaimAtMs = 0;
};

class V3ProtocolRuntime {
  public:
    V3AuthorityBook authorities;
    V3PaletteCache palettes;
    V3PositionPeers positionPeers;
    V3ProtocolCounters counters;
    V3PositionFramePayload positionFrame;
    bool hasPositionFrame = false;

    void setup(DeviceId nodeId, uint32_t session) {
      localId = nodeId;
      localSession = session ? session : 1;
      authorities.clear();
      palettes.clear();
      positionPeers.clear();
      counters = V3ProtocolCounters();
      positionFrame = V3PositionFramePayload();
      hasPositionFrame = false;
      for (V3PublisherState& publisher : publishers)
        publisher = V3PublisherState();
    }

    void setLocalId(DeviceId nodeId) {
      localId = nodeId;
    }

    void observeLegacyPacket() {
      counters.legacyPackets++;
    }

    void update(uint32_t nowMs) {
      authorities.expire(nowMs);
      positionPeers.expire(nowMs);
    }

    // Claims are repeated independently so packet loss cannot leave a live publisher unauthorized.
    bool prepareClaim(uint8_t topic, uint32_t nowMs, V3TopicPayload& payload, bool force = false) {
      if (!isKnownV3Topic(topic) || topic == V3TopicPresence)
        return false;
      V3PublisherState& publisher = publishers[topic];
      const V3AuthorityState& authority = authorities.get(topic);
      bool ownsTopic = authority.active
          && authority.authorityId == localId
          && authority.authoritySession == localSession;
      if (!force && ownsTopic && !v3DeadlineReached(nowMs, publisher.nextClaimAtMs))
        return false;

      payload = V3TopicPayload();
      payload.envelope = makeEnvelope(topic, V3Claim, 0, V3_DEFAULT_TOPIC_LEASE_DECISECONDS);
      publisher.nextClaimAtMs = nowMs + V3_CLAIM_REPEAT_MS;
      authorities.claimLocal(topic, payload.envelope, nowMs);
      return true;
    }

    bool prepareMessage(
        uint8_t topic,
        V3MessageKind kind,
        const void* body,
        uint8_t bodyLength,
        uint16_t leaseDeciseconds,
        uint32_t nowMs,
        V3TopicPayload& payload,
        uint8_t quality = 0,
        uint8_t flags = 0
    ) {
      if (!isKnownV3Topic(topic))
        return false;
      payload = V3TopicPayload();
      payload.envelope = makeEnvelope(topic, kind, bodyLength, leaseDeciseconds);
      payload.envelope.quality = quality;
      payload.envelope.flags = flags;
      if (!writeV3Body(payload, body, bodyLength) || !isValidV3TopicPayload(topic, payload))
        return false;
      if (isAuthorityMessageKind(kind) && topic != V3TopicPresence) {
        const V3AuthorityState& authority = authorities.get(topic);
        if (!authority.active
            || authority.authorityId != localId
            || authority.authoritySession != localSession)
          return false;
        if (kind != V3Claim && !authorities.accept(topic, payload.envelope, nowMs))
          return false;
      }
      return true;
    }

    // Apply root-authorized topic ordering before the controller mutates visible state.
    bool acceptTopic(uint8_t topic, const V3TopicPayload& payload, uint32_t nowMs) {
      if (!isKnownV3Topic(topic)) {
        counters.unknown++;
        return false;
      }
      if (!isValidV3TopicPayload(topic, payload)) {
        counters.rejected++;
        return false;
      }
      if (topic == V3TopicPresence || (topic == V3TopicPosition && payload.envelope.messageKind == V3Advertisement)) {
        counters.accepted++;
        return true;
      }
      if (!authorities.accept(topic, payload.envelope, nowMs)) {
        counters.stale++;
        return false;
      }
      counters.accepted++;
      return true;
    }

    DeviceId nodeId() const {
      return localId;
    }

    uint32_t session() const {
      return localSession;
    }

  private:
    DeviceId localId = 0;
    uint32_t localSession = 1;
    V3PublisherState publishers[V3TopicControl + 1];

    V3TopicEnvelope makeEnvelope(
        uint8_t topic,
        V3MessageKind kind,
        uint8_t bodyLength,
        uint16_t leaseDeciseconds
    ) {
      V3PublisherState& publisher = publishers[topic];
      V3TopicEnvelope envelope;
      envelope.messageKind = kind;
      envelope.bodyLength = bodyLength;
      envelope.authorityId = localId;
      envelope.authoritySession = localSession;
      envelope.sequence = ++publisher.sequence;
      envelope.leaseDeciseconds = leaseDeciseconds;
      return envelope;
    }
};

// AI: end
