#pragma once

#include <stdint.h>

// AI: below section was generated by an AI

// Carries untouched 16-band FFT mappings from AudioReactive's FFT task to a
// tempo consumer. Two slots let the reader take a consistent copy while the
// producer publishes the next spectrum without blocking either task.
struct AudioTempoSpectrum {
  uint32_t timestampUs = 0;
  float bands[16] = {0.0f};
};

struct AudioTempoData {
  volatile uint32_t publishedSequence = 0;
  AudioTempoSpectrum slots[2];
};

// AI: end
