#ifdef WAVESHARE_S3_TUBES_REMOTE

// AI: below section was generated by an AI
// Attribution: uses Arduino_GFX, SensorLib, XPowersLib, and WLED Tubes APIs
// following the Waveshare ESP32-S3-Touch-AMOLED-2.16 vendor documentation.

#include "wled.h"

#undef BLACK
#undef BLUE
#undef GREEN
#undef CYAN
#undef RED
#undef MAGENTA
#undef YELLOW
#undef WHITE
#undef ORANGE
#undef PURPLE
#undef DARKGREY

#include <Arduino_GFX_Library.h>
#include <SensorQMI8658.hpp>
#include <touch/TouchDrvCST92xx.h>
#include <XPowersLib.h>

#ifdef TUBES_S3_FIELD_OS
#include "../Tubes/s3_field_api.h"
#include "../Tubes/device_report_protocol.h"
#endif

namespace {
constexpr int8_t DISPLAY_CS = 12;
constexpr int8_t DISPLAY_SCLK = 38;
constexpr int8_t DISPLAY_SDIO0 = 4;
constexpr int8_t DISPLAY_SDIO1 = 5;
constexpr int8_t DISPLAY_SDIO2 = 6;
constexpr int8_t DISPLAY_SDIO3 = 7;
constexpr int8_t DISPLAY_RESET = 39;
constexpr int8_t PERIPHERAL_SDA = 15;
constexpr int8_t PERIPHERAL_SCL = 14;
constexpr int8_t TOUCH_IRQ = 11;
constexpr int8_t TOUCH_RESET = 40;
constexpr int16_t DISPLAY_WIDTH = 480;
constexpr int16_t DISPLAY_HEIGHT = 480;
constexpr uint32_t SAMPLE_INTERVAL_MS = 1000;
constexpr uint32_t PREVIEW_INTERVAL_MS = 50;
#ifdef TUBES_S3_FIELD_OS
constexpr uint32_t MICROPHONE_PREVIEW_INTERVAL_MS = 100;
constexpr uint8_t FIELD_OS_DEFAULT_BRIGHTNESS = 255;
constexpr uint32_t FIELD_OS_IDLE_TIMEOUT_MS = 30000;
constexpr uint32_t BATTERY_PULSE_INTERVAL_MS = 80;
constexpr uint32_t BATTERY_PULSE_CYCLE_MS = 2400;
constexpr int16_t FIELD_OS_HEADER_HEIGHT = 64;
constexpr int16_t FIELD_OS_STRIP_TOP = FIELD_OS_HEADER_HEIGHT;
constexpr int16_t FIELD_OS_STRIP_HEIGHT = 32;
constexpr int16_t FIELD_OS_APP_TOP = FIELD_OS_STRIP_TOP + FIELD_OS_STRIP_HEIGHT;
#else
constexpr uint8_t SMOKE_DEFAULT_BRIGHTNESS = 160;
#endif

volatile bool touchInterruptPending = false;

void IRAM_ATTR handleTouchInterrupt() {
  touchInterruptPending = true;
}

Arduino_ESP32QSPI displayBus(DISPLAY_CS, DISPLAY_SCLK, DISPLAY_SDIO0, DISPLAY_SDIO1,
                             DISPLAY_SDIO2, DISPLAY_SDIO3);
Arduino_CO5300 display(&displayBus, DISPLAY_RESET, 0, false, DISPLAY_WIDTH, DISPLAY_HEIGHT);
TouchDrvCST92xx touch;
SensorQMI8658 imu;
XPowersPMU pmu;

#ifdef TUBES_S3_FIELD_OS
enum class FieldViewId : uint8_t {
  Home,
  Patterns,
  Beats,
  Mesh,
  Colors,
  Update,
};

class WaveshareS3FieldOs : public Usermod {
private:
  struct Rect {
    int16_t x;
    int16_t y;
    int16_t width;
    int16_t height;

    bool contains(int16_t px, int16_t py) const {
      return px >= x && py >= y && px < x + width && py < y + height;
    }
  };

  struct ButtonComponent {
    Rect bounds;
    uint16_t color;
    const __FlashStringHelper *label;
  };

  struct DeviceCard {
    uint16_t id;
    uint16_t version;
    uint16_t uplinkId;
    uint32_t ageSeconds;
    const char *kind;

    DeviceCard(uint16_t id, uint16_t version, uint16_t uplinkId,
               uint32_t ageSeconds, const char *kind)
        : id(id), version(version), uplinkId(uplinkId), ageSeconds(ageSeconds), kind(kind) {}
  };

  bool displayReady = false;
  bool touchReady = false;
  bool pmuReady = false;
  bool microphoneReady = false;
  bool nextSendFailed = false;
  bool touchDown = false;
  bool screenOn = true;
  bool usbPresent = false;
  bool charging = false;
  int16_t batteryPercent = -1;
  uint16_t batteryMv = 0;
  uint32_t lastActivityMs = 0;
  uint32_t lastBatterySampleMs = 0;
  uint32_t lastPmuPollMs = 0;
  uint32_t lastPreviewMs = 0;
  uint32_t lastBatteryPulseMs = 0;
  bool physicalButtonDown[WLED_MAX_BUTTONS] = {};
  uint8_t selectedGradientStop = 1;
  uint32_t gradientStops[3] = {0xFF3A7A, 0x7A5CFF, 0x28D7D0};
  uint32_t gradientPresets[8][3] = {};
  bool drawnTempoListening = false;
  uint8_t drawnBeatOverlayChoice = UINT8_MAX;
  uint8_t drawnNextBeatOverlayChoice = UINT8_MAX;

  static constexpr uint16_t COLOR_BACKGROUND = 0x0863;
  static constexpr uint16_t COLOR_SURFACE = 0x10E7;
  static constexpr uint16_t COLOR_SURFACE_RAISED = 0x194A;
  static constexpr uint16_t COLOR_PRIMARY = 0x64FF;
  static constexpr uint16_t COLOR_MINT = 0x5F56;
  static constexpr uint16_t COLOR_AMBER = 0xFDC8;
  static constexpr uint16_t COLOR_MUTED = 0x8C51;
  static constexpr uint16_t COLOR_BEAT = 0x2104;
  static constexpr uint16_t COLOR_DOWNBEAT = 0x4A49;

  static uint16_t rgb565(uint32_t color) {
    // Production colors stay RGB888 until this existing color-depth conversion.
    // This is not gamma or brightness scaling.
    const uint8_t red = color >> 16;
    const uint8_t green = color >> 8;
    const uint8_t blue = color;
    return static_cast<uint16_t>(((red & 0xF8) << 8) | ((green & 0xFC) << 3) | (blue >> 3));
  }

  // CO5300 drops one-pixel transparent writes, so TubeOS uses Arduino_GFX's
  // built-in scaled font and always supplies a background color.
  // https://github.com/moononournation/Arduino_GFX/issues/780
  void setDetailFont() {
    display.setFont(nullptr);
    display.setTextSize(2);
  }

  void setBodyFont() {
    display.setFont(nullptr);
    display.setTextSize(2);
  }

  void setAppFont() {
    display.setFont(nullptr);
    display.setTextSize(3);
  }

  void setHeaderFont() {
    display.setFont(nullptr);
    display.setTextSize(5);
  }

  // Initializes the Waveshare ES7210 for its two onboard microphones. The register
  // sequence follows Waveshare's 16 kHz slave-mode reference implementation:
  // https://github.com/waveshareteam/ESP32-S3-Touch-AMOLED-2.16/tree/main/examples/arduino/06_ES7210
  bool writeEs7210(uint8_t reg, uint8_t value) {
    Wire.beginTransmission(0x40);
    Wire.write(reg);
    Wire.write(value);
    return Wire.endTransmission() == 0;
  }

  bool readEs7210(uint8_t reg, uint8_t &value) {
    Wire.beginTransmission(0x40);
    Wire.write(reg);
    if (Wire.endTransmission(false) != 0 || Wire.requestFrom(0x40, 1U) != 1)
      return false;
    value = Wire.read();
    return true;
  }

  bool initializeMicrophones() {
    bool ok = true;
    ok &= writeEs7210(0x00, 0xFF);
    ok &= writeEs7210(0x00, 0x41);
    ok &= writeEs7210(0x01, 0x1F);
    ok &= writeEs7210(0x09, 0x30);
    ok &= writeEs7210(0x0A, 0x30);
    ok &= writeEs7210(0x40, 0xC3);
    ok &= writeEs7210(0x41, 0x70);
    ok &= writeEs7210(0x42, 0x70);
    ok &= writeEs7210(0x02, 0xC1);
    ok &= writeEs7210(0x07, 0x20);
    ok &= writeEs7210(0x04, 0x01);
    ok &= writeEs7210(0x05, 0x00);
    // Waveshare's 16-bit reference sets SDP_INTERFACE1[7:5] to 0b011.
    // A value of 0x80 selects 32-bit samples and leaves the ESP32 reading empty slots.
    ok &= writeEs7210(0x11, 0x60);
    ok &= writeEs7210(0x12, 0x00);
    ok &= writeEs7210(0x43, 0x10);
    ok &= writeEs7210(0x44, 0x10);
    ok &= writeEs7210(0x45, 0x1E);
    ok &= writeEs7210(0x46, 0x1E);
    ok &= writeEs7210(0x4B, 0x00);
    ok &= writeEs7210(0x4C, 0x00);
    ok &= writeEs7210(0x01, 0x00);
    ok &= writeEs7210(0x06, 0x00);
    ok &= writeEs7210(0x47, 0x00);
    ok &= writeEs7210(0x48, 0x00);
    ok &= writeEs7210(0x49, 0x00);
    ok &= writeEs7210(0x4A, 0x00);
    const uint8_t registers[] = {0x01, 0x02, 0x11, 0x4B, 0x4C};
    const uint8_t expected[] = {0x00, 0xC1, 0x60, 0x00, 0x00};
    for (uint8_t i = 0; i < sizeof(registers); i++) {
      uint8_t actual = 0;
      const bool read = readEs7210(registers[i], actual);
      ok &= read && actual == expected[i];
    }
    return ok;
  }

  uint16_t batteryPulseColor(uint32_t now) const {
    const uint16_t phase = static_cast<uint32_t>(now % BATTERY_PULSE_CYCLE_MS) * 510
        / BATTERY_PULSE_CYCLE_MS;
    const uint8_t triangle = phase <= 255 ? phase : 510 - phase;
    const uint8_t brightness = 188 + static_cast<uint16_t>(triangle) * 67 / 255;
    return rgb565((static_cast<uint32_t>(brightness) << 16)
        | (static_cast<uint32_t>(brightness) << 8) | brightness);
  }

  void drawBatteryIcon(uint16_t color, bool showChargingSymbol) {
    constexpr int16_t iconX = 405;
    constexpr int16_t iconY = 14;
    constexpr int16_t iconWidth = 58;
    constexpr int16_t iconHeight = 34;
    display.fillRect(iconX - 2, iconY - 2, 77, iconHeight + 4, COLOR_BACKGROUND);
    display.drawRoundRect(iconX, iconY, iconWidth, iconHeight, 5, color);
    display.fillRect(iconX + iconWidth, iconY + 9, 6, 16, color);
    const int16_t levelWidth = batteryPercent < 0 ? 0
        : static_cast<int16_t>((iconWidth - 8) * batteryPercent / 100);
    if (levelWidth > 0)
      display.fillRect(iconX + 4, iconY + 4, levelWidth, iconHeight - 8, color);
    if (!showChargingSymbol) return;

    // A high-contrast bolt remains visible at every state of charge.
    display.fillTriangle(iconX + 31, iconY + 5, iconX + 20, iconY + 19,
                         iconX + 30, iconY + 19, RGB565_WHITE);
    display.fillTriangle(iconX + 27, iconY + 15, iconX + 38, iconY + 15,
                         iconX + 24, iconY + 29, RGB565_WHITE);
  }

  void drawBattery() {
    display.fillRect(385, 0, 95, FIELD_OS_HEADER_HEIGHT, COLOR_BACKGROUND);
    drawBatteryIcon(usbPresent ? COLOR_MINT : batteryPulseColor(millis()), usbPresent);
  }

  void drawHeader() {
    display.fillRect(0, 0, DISPLAY_WIDTH, FIELD_OS_HEADER_HEIGHT, COLOR_BACKGROUND);
    display.setTextWrap(false);
    display.setTextColor(RGB565_WHITE, COLOR_BACKGROUND);
    setHeaderFont();
    display.setCursor(14, 12);
    display.print(F("tubeOS"));
    TubesS3FieldStatus status;
    tubesS3ReadStatus(status);
    setAppFont();
    display.setTextColor(COLOR_MUTED, COLOR_BACKGROUND);
    display.setCursor(220, 24);
    display.printf("%04X v%u", status.localNodeId, status.tubesVersion);
    drawBattery();
  }

  void drawChrome(const __FlashStringHelper *, bool) {
    display.fillScreen(COLOR_BACKGROUND);
    drawHeader();
    stripComponent.draw(0, FIELD_OS_STRIP_TOP, DISPLAY_WIDTH, FIELD_OS_STRIP_HEIGHT, true);
  }

  void drawButton(const ButtonComponent &button) {
    const Rect &bounds = button.bounds;
    display.fillRoundRect(bounds.x, bounds.y, bounds.width, bounds.height, 20, button.color);
    display.setTextColor(RGB565_WHITE, button.color);
    setAppFont();
    int16_t textX = 0;
    int16_t textY = 0;
    uint16_t textWidth = 0;
    uint16_t textHeight = 0;
    display.getTextBounds(button.label, 0, 0, &textX, &textY, &textWidth, &textHeight);
    display.setCursor(bounds.x + (bounds.width - textWidth) / 2 - textX,
                      bounds.y + (bounds.height - textHeight) / 2 - textY);
    display.print(button.label);
  }

  void drawHomeContent() {
    drawButton({{20, 128, 210, 150}, COLOR_PRIMARY, F("Patterns")});
    drawButton({{250, 128, 210, 150}, COLOR_SURFACE_RAISED, F("Beats")});
    drawButton({{20, 294, 210, 150}, COLOR_SURFACE_RAISED, F("Colors")});
    drawButton({{250, 294, 210, 150}, COLOR_SURFACE_RAISED, F("Mesh")});
  }

  // Persistent Strip observes WLED's canonical, completed logical framebuffer.
  // The null bus supplies geometry only; it must not become a second pixel store.
  // A small display-only glow models diffusion through a tube without changing
  // the canonical pixels used by the pattern engine or mesh.
  class Strip {
  public:
    void draw(int16_t x, int16_t y, int16_t width, int16_t height, bool = false) {
      TubesS3FieldStatus status;
      tubesS3ReadStatus(status);
      uint32_t colors[TUBES_S3_PREVIEW_PIXELS];
      uint32_t diffused[TUBES_S3_PREVIEW_PIXELS];
      const bool validTopology = ::strip.getLengthTotal() >= TUBES_S3_PREVIEW_PIXELS;
      // draw() runs periodically, so this samples the previous completed show frame.
      for (size_t i = 0; i < TUBES_S3_PREVIEW_PIXELS; i++)
        colors[i] = validTopology ? ::strip.getPixelColor(i) : 0;
      for (size_t i = 0; i < TUBES_S3_PREVIEW_PIXELS; i++)
        diffused[i] = diffusePixel(colors, i);
      const uint8_t beat = status.beat & 0x0F;
      const int16_t laneTop = height * 3 / 4;
      for (int16_t row = 0; row < height; row++) {
        for (int16_t column = 0; column < width; column++) {
          if (row < laneTop) {
            const uint32_t sourceQ8 = width > 1
                ? static_cast<uint32_t>(column)
                    * ((TUBES_S3_PREVIEW_PIXELS - 1U) << 8) / (width - 1)
                : 0;
            frame[row * width + column] = rgb565(interpolatePixel(diffused, sourceQ8));
            continue;
          }
          const uint8_t segment = static_cast<uint32_t>(column) * 16 / width;
          frame[row * width + column] = segment == beat
              ? RGB565_WHITE
              : segment % 4 == 0 ? COLOR_DOWNBEAT : COLOR_BEAT;
        }
      }
      // One opaque transfer avoids the CO5300's missing-column behavior on narrow writes.
      display.draw16bitRGBBitmap(x, y, frame, width, height);
    }
  private:
    static uint8_t channel(uint32_t color, uint8_t shift) {
      return static_cast<uint8_t>(color >> shift);
    }

    static uint8_t scaledChannel(uint32_t color, uint8_t shift, uint8_t scale) {
      return static_cast<uint16_t>(channel(color, shift)) * scale / 255U;
    }

    static uint32_t diffusePixel(const uint32_t *colors, size_t pixel) {
      uint8_t red = 0;
      uint8_t green = 0;
      uint8_t blue = 0;
      for (int8_t offset = -2; offset <= 2; offset++) {
        const int16_t source = static_cast<int16_t>(pixel) + offset;
        if (source < 0 || source >= TUBES_S3_PREVIEW_PIXELS) continue;
        const uint8_t distance = abs(offset);
        const uint8_t scale = distance == 0 ? 255 : distance == 1 ? 112 : 48;
        const uint32_t color = colors[source];
        red = max(red, scaledChannel(color, 16, scale));
        green = max(green, scaledChannel(color, 8, scale));
        blue = max(blue, scaledChannel(color, 0, scale));
      }
      return (static_cast<uint32_t>(red) << 16)
          | (static_cast<uint32_t>(green) << 8) | blue;
    }

    static uint32_t interpolatePixel(const uint32_t *colors, uint32_t sourceQ8) {
      size_t left = sourceQ8 >> 8;
      if (left >= TUBES_S3_PREVIEW_PIXELS) left = TUBES_S3_PREVIEW_PIXELS - 1U;
      size_t right = left + 1U;
      if (right >= TUBES_S3_PREVIEW_PIXELS) right = TUBES_S3_PREVIEW_PIXELS - 1U;
      const uint8_t fraction = sourceQ8 & 0xFF;
      const uint16_t inverse = 256U - fraction;
      const uint8_t red = (channel(colors[left], 16) * inverse
          + channel(colors[right], 16) * fraction) >> 8;
      const uint8_t green = (channel(colors[left], 8) * inverse
          + channel(colors[right], 8) * fraction) >> 8;
      const uint8_t blue = (channel(colors[left], 0) * inverse
          + channel(colors[right], 0) * fraction) >> 8;
      return (static_cast<uint32_t>(red) << 16)
          | (static_cast<uint32_t>(green) << 8) | blue;
    }

    uint16_t frame[DISPLAY_WIDTH * FIELD_OS_STRIP_HEIGHT] = {};
  };

  Strip stripComponent;

  void setScreenOn(bool enabled) {
    if (!displayReady || screenOn == enabled) return;
    screenOn = enabled;
    if (!screenOn) {
      display.displayOff();
      return;
    }
    display.displayOn();
    display.setBrightness(FIELD_OS_DEFAULT_BRIGHTNESS);
    lastActivityMs = millis();
    viewManager.redraw();
  }

  void samplePower(uint32_t now, bool force = false) {
    if (!pmuReady || (!force && now - lastBatterySampleMs < SAMPLE_INTERVAL_MS)) return;
    lastBatterySampleMs = now;
    const bool wasUsbPresent = usbPresent;
    const bool nextUsbPresent = pmu.isVbusIn();
    const bool nextCharging = pmu.isCharging();
    const uint16_t nextBatteryMv = pmu.getBattVoltage();
    const int16_t nextBatteryPercent = pmu.isBatteryConnect()
        ? constrain(static_cast<int16_t>(pmu.getBatteryPercent()), 0, 100) : -1;
    const bool changed = nextUsbPresent != usbPresent || nextCharging != charging
        || nextBatteryPercent != batteryPercent || nextBatteryMv != batteryMv;
    usbPresent = nextUsbPresent;
    charging = nextCharging;
    batteryMv = nextBatteryMv;
    batteryPercent = nextBatteryPercent;
    if (wasUsbPresent && !usbPresent) lastActivityMs = now;
    if (!wasUsbPresent && usbPresent && !screenOn) setScreenOn(true);
    if (changed && displayReady && screenOn) drawBattery();
  }

  void handlePowerKey() {
    if (!pmuReady) return;
    const uint32_t now = millis();
    if (now - lastPmuPollMs < 25) return;
    lastPmuPollMs = now;
    pmu.getIrqStatus();
    if (pmu.isPekeyShortPressIrq()) {
      lastActivityMs = now;
      setScreenOn(!screenOn);
    }
    pmu.clearIrqStatus();
  }

  void tickShell(uint32_t now) {
    handlePowerKey();
    samplePower(now);
    if (!screenOn) return;
    if (!usbPresent && now - lastActivityMs >= FIELD_OS_IDLE_TIMEOUT_MS) {
      setScreenOn(false);
      return;
    }
    if (!usbPresent && now - lastBatteryPulseMs >= BATTERY_PULSE_INTERVAL_MS) {
      lastBatteryPulseMs = now;
      drawBatteryIcon(batteryPulseColor(now), false);
    }
    if (now - lastPreviewMs >= PREVIEW_INTERVAL_MS) {
      lastPreviewMs = now;
      stripComponent.draw(0, FIELD_OS_STRIP_TOP, DISPLAY_WIDTH, FIELD_OS_STRIP_HEIGHT);
    }
  }

  static uint8_t patternChoiceId(uint8_t index) {
    static constexpr uint8_t choices[] = {
      20, 22, 25, 26, 28, 30, 33, 35, 40, 44, 47, 50
    };
    return choices[index % (sizeof(choices) / sizeof(choices[0]))];
  }

  static const __FlashStringHelper *patternChoiceLabel(uint8_t index) {
    switch (index) {
      case 0: return F("Wave");
      case 1: return F("Pulse");
      case 2: return F("Chase");
      case 3: return F("Aurora");
      case 4: return F("Twinkle");
      case 5: return F("Scanner");
      case 6: return F("Fire");
      case 7: return F("Noise");
      case 8: return F("Lake");
      case 9: return F("Burst");
      case 10: return F("Popcorn");
      default: return F("Pacifica");
    }
  }

  // Draws a compact motion signature so patterns can be recognized before reading the label.
  void drawPatternTile(uint8_t index, const TubesS3FieldStatus &status) {
    constexpr int16_t tileWidth = 142;
    constexpr int16_t tileHeight = 76;
    const int16_t x = 20 + (index % 3) * 149;
    const int16_t y = 148 + (index / 3) * 82;
    const uint8_t patternId = patternChoiceId(index);
    const bool isNext = patternId == status.nextPatternId;
    const bool isCurrent = patternId == status.patternId;
    const uint16_t background = isNext ? COLOR_PRIMARY
        : isCurrent ? COLOR_MINT : COLOR_SURFACE_RAISED;
    display.fillRoundRect(x, y, tileWidth, tileHeight, 12, background);
    for (uint8_t bar = 0; bar < 6; bar++) {
      const int16_t barHeight = 6 + ((index * 7 + bar * 11) % 23);
      display.fillRoundRect(x + 12 + bar * 20, y + 34 - barHeight,
                            12, barHeight, 4,
                            isNext || isCurrent ? RGB565_WHITE : COLOR_MUTED);
    }
    display.setTextColor(RGB565_WHITE, background);
    setDetailFont();
    const __FlashStringHelper *label = patternChoiceLabel(index);
    int16_t textX = 0;
    int16_t textY = 0;
    uint16_t textWidth = 0;
    uint16_t textHeight = 0;
    display.getTextBounds(label, 0, 0, &textX, &textY, &textWidth, &textHeight);
    display.setCursor(x + (tileWidth - textWidth) / 2 - textX, y + 50);
    display.print(label);
  }

  void drawPatternsContent(bool) {
    TubesS3FieldStatus status;
    tubesS3ReadStatus(status);
    display.fillRect(0, FIELD_OS_APP_TOP, DISPLAY_WIDTH,
                     DISPLAY_HEIGHT - FIELD_OS_APP_TOP, COLOR_BACKGROUND);
    setDetailFont();
    display.setTextColor(nextSendFailed ? RGB565_RED : COLOR_MUTED, COLOR_BACKGROUND);
    display.setCursor(20, 110);
    if (nextSendFailed) display.print(F("COULD NOT SET PATTERN"));
    else display.printf("CURRENT %02u    NEXT %02u", status.patternId, status.nextPatternId);
    for (uint8_t index = 0; index < 12; index++)
      drawPatternTile(index, status);
  }

  static bool meshBefore(const TubesS3PeerStatus &candidate, const TubesS3PeerStatus &prior) {
    if (candidate.rssiKnown != prior.rssiKnown) return candidate.rssiKnown;
    if (candidate.rssiKnown && candidate.latestRssi != prior.latestRssi)
      return candidate.latestRssi > prior.latestRssi;
    return candidate.nodeId < prior.nodeId;
  }

  static uint32_t mixRevision(uint32_t value, uint32_t field) {
    return (value ^ field) * 16777619UL;
  }

  uint32_t patternsRevision(const TubesS3FieldStatus &status) {
    uint32_t value = mixRevision(status.patternId, status.nextPatternId);
    value = mixRevision(value, status.currentPatternPhrase);
    value = mixRevision(value, status.nextPatternPhrase);
    return value;
  }

  static const __FlashStringHelper *beatOverlayLabel(uint8_t choice) {
    switch (choice) {
      case 0: return F("Off");
      case 1: return F("Stream");
      case 2: return F("Boom");
      case 3: return F("Spring");
      case 4: return F("Ripple");
      case 5: return F("Puddle");
      case 6: return F("Falls");
      case 7: return F("Center");
      default: return F("Orbit");
    }
  }

  // Draws a rhythmic signature for each curated audio overlay choice.
  void drawBeatOverlayTile(uint8_t choice, const TubesS3FieldStatus &status) {
    constexpr int16_t tileWidth = 142;
    constexpr int16_t tileHeight = 78;
    const int16_t x = 20 + (choice % 3) * 149;
    const int16_t y = 210 + (choice / 3) * 86;
    const bool isNext = choice == status.nextBeatOverlayChoice;
    const bool isCurrent = choice == status.beatOverlayChoice;
    const uint16_t background = isNext ? COLOR_PRIMARY
        : isCurrent ? COLOR_MINT : COLOR_SURFACE_RAISED;
    display.fillRoundRect(x, y, tileWidth, tileHeight, 12, background);
    const uint16_t glyphColor = isNext || isCurrent ? RGB565_WHITE : COLOR_MUTED;
    if (choice == 0) {
      display.fillRoundRect(x + 34, y + 26, 74, 7, 3, glyphColor);
    } else {
      for (uint8_t bar = 0; bar < 7; bar++) {
        const int16_t barHeight = 5 + ((choice * 9 + bar * 7) % 23);
        display.fillRoundRect(x + 13 + bar * 17, y + 35 - barHeight,
                              10, barHeight, 3, glyphColor);
      }
    }
    display.setTextColor(RGB565_WHITE, background);
    setDetailFont();
    const __FlashStringHelper *label = beatOverlayLabel(choice);
    int16_t textX = 0;
    int16_t textY = 0;
    uint16_t textWidth = 0;
    uint16_t textHeight = 0;
    display.getTextBounds(label, 0, 0, &textX, &textY, &textWidth, &textHeight);
    display.setCursor(x + (tileWidth - textWidth) / 2 - textX, y + 52);
    display.print(label);
  }

  void drawMicrophonePanel(const TubesS3FieldStatus &status) {
    const Rect bounds = {150, 112, 230, 78};
    const uint16_t background = COLOR_SURFACE_RAISED;
    display.fillRoundRect(bounds.x, bounds.y, bounds.width, bounds.height, 20, background);
    display.setTextColor(status.tempoLocked ? COLOR_MINT : RGB565_WHITE, background);
    setAppFont();
    display.setCursor(status.bpm < 100 ? 211 : status.bpm < 1000 ? 202 : 193, 116);
    display.printf("%u BPM", status.bpm);
    for (uint8_t bin = 0; bin < TUBES_S3_MICROPHONE_BINS; bin++) {
      const int16_t x = 168 + bin * 16;
      display.fillRoundRect(x, 153, 12, 26, 3, COLOR_BEAT);
      const uint8_t level = status.tempoListening && status.microphoneActive
          ? status.microphoneSpectrum[bin] : 0;
      const int16_t height = static_cast<uint16_t>(level) * 26 / 255;
      if (height > 0)
        display.fillRoundRect(x, 179 - height, 12, height, 3,
                              bin < 4 ? COLOR_PRIMARY : bin < 8 ? COLOR_MINT : COLOR_AMBER);
    }
    display.fillRoundRect(163, 183, 204, 4, 2, COLOR_BEAT);
    const int16_t volumeWidth = status.tempoListening && status.microphoneActive
        ? static_cast<uint16_t>(status.microphoneLevel) * 204 / 255 : 0;
    if (volumeWidth > 0) display.fillRoundRect(163, 183, volumeWidth, 4, 2, RGB565_WHITE);
  }

  void drawBeatsContent(bool full) {
    TubesS3FieldStatus status;
    tubesS3ReadStatus(status);
    const bool controlsChanged = status.tempoListening != drawnTempoListening
        || status.beatOverlayChoice != drawnBeatOverlayChoice
        || status.nextBeatOverlayChoice != drawnNextBeatOverlayChoice;
    if (full || controlsChanged) {
      display.fillRect(0, FIELD_OS_APP_TOP, DISPLAY_WIDTH,
                       DISPLAY_HEIGHT - FIELD_OS_APP_TOP, COLOR_BACKGROUND);
      drawButton({{20, 112, 120, 78},
                  status.tempoListening ? COLOR_MINT : COLOR_SURFACE_RAISED,
                  F("Listen")});
      drawMicrophonePanel(status);
      drawButton({{390, 112, 70, 78}, COLOR_AMBER, F("1")});
      for (uint8_t choice = 0; choice < 9; choice++)
        drawBeatOverlayTile(choice, status);
    } else {
      drawMicrophonePanel(status);
    }
    drawnTempoListening = status.tempoListening;
    drawnBeatOverlayChoice = status.beatOverlayChoice;
    drawnNextBeatOverlayChoice = status.nextBeatOverlayChoice;
  }

  uint32_t beatsRevision(const TubesS3FieldStatus &status) {
    uint32_t value = mixRevision(status.tempoListening, status.beatOverlayChoice);
    value = mixRevision(value, status.nextBeatOverlayChoice);
    value = mixRevision(value, status.bpm);
    if (!status.tempoListening) return value;
    value = mixRevision(value, status.microphoneActive);
    value = mixRevision(value, status.microphoneLevel);
    for (uint8_t bin = 0; bin < TUBES_S3_MICROPHONE_BINS; bin++)
      value = mixRevision(value, status.microphoneSpectrum[bin]);
    return value;
  }

  void drawDeviceCard(int16_t y, const DeviceCard &device,
                      uint16_t color = COLOR_SURFACE_RAISED) {
    display.fillRoundRect(20, y, 440, 62, 10, color);
    display.setTextColor(RGB565_WHITE, color);
    setDetailFont();
    display.setCursor(34, y + 5);
    display.printf("%s", device.kind);
    if (device.id) display.printf(" | %04X", device.id);
    else display.print(F(" | UNKNOWN"));
    display.print(F(" | "));
    if (device.version) display.printf("v%u", device.version);
    else display.print(F("UNKNOWN"));
    display.setTextColor(COLOR_MUTED, color);
    display.setCursor(34, y + 32);
    if (device.uplinkId) display.printf("UPLINK: %04X", device.uplinkId);
    else display.print(F("UPLINK: NONE"));
    if (device.ageSeconds != UINT32_MAX)
      display.printf(" | HEARD: %lus AGO", device.ageSeconds);
  }

  void drawMeshContent() {
    TubesS3FieldStatus status;
    tubesS3ReadStatus(status);
    display.fillRect(0, FIELD_OS_APP_TOP, DISPLAY_WIDTH,
                     DISPLAY_HEIGHT - FIELD_OS_APP_TOP, COLOR_BACKGROUND);
    TubesS3PeerStatus sorted[4];
    size_t shown = 0;
    const uint32_t now = millis();
    for (size_t i = 0; i < status.peerCount; i++) {
      TubesS3PeerStatus candidate;
      if (!tubesS3ReadPeer(i, candidate) || candidate.nodeId == status.localNodeId
          || now - candidate.lastSeenMs > 60000) continue;
      if (shown == 4 && !meshBefore(candidate, sorted[3])) continue;
      size_t position = shown < 4 ? shown++ : 3;
      while (position > 0 && meshBefore(candidate, sorted[position - 1])) {
        if (position < 4) sorted[position] = sorted[position - 1];
        position--;
      }
      if (position < 4) sorted[position] = candidate;
    }
    if (shown == 0) {
      display.setTextColor(RGB565_WHITE, COLOR_BACKGROUND);
      setDetailFont();
      display.setCursor(24, 116);
      display.println(F("No Tubes heard in 60 seconds."));
    }
    for (size_t i = 0; i < shown; i++) {
      const TubesS3PeerStatus &peer = sorted[i];
      drawDeviceCard(106 + i * 70, {peer.nodeId, peer.tubesVersion, peer.uplinkId,
                     (now - peer.lastSeenMs) / 1000, "TUBES DEVICE"});
    }
    drawButton({{120, 408, 240, 56}, COLOR_PRIMARY, F("Update")});
  }

  static uint32_t blendColor(uint32_t first, uint32_t second, uint8_t amount) {
    const uint8_t inverse = 255 - amount;
    const uint8_t red = ((first >> 16) * inverse + (second >> 16) * amount) / 255;
    const uint8_t green = (((first >> 8) & 0xFF) * inverse
        + ((second >> 8) & 0xFF) * amount) / 255;
    const uint8_t blue = ((first & 0xFF) * inverse + (second & 0xFF) * amount) / 255;
    return (static_cast<uint32_t>(red) << 16)
        | (static_cast<uint32_t>(green) << 8) | blue;
  }

  static uint32_t gradientColor(const uint32_t colors[3], uint8_t position) {
    if (position < 128)
      return blendColor(colors[0], colors[1], position * 2);
    return blendColor(colors[1], colors[2],
                      static_cast<uint16_t>(position - 128) * 255 / 127);
  }

  static uint8_t gradientBrightness(uint8_t index) {
    static constexpr uint8_t levels[4] = {88, 144, 200, 255};
    return levels[index % 4];
  }

  // Changes perceived brightness while preserving the selected stop's hue.
  static uint32_t setColorBrightness(uint32_t color, uint8_t brightness) {
    const uint8_t red = color >> 16;
    const uint8_t green = color >> 8;
    const uint8_t blue = color;
    const uint8_t peak = max(red, max(green, blue));
    if (peak == 0)
      return static_cast<uint32_t>(brightness) * 0x010101UL;
    return (static_cast<uint32_t>(red) * brightness / peak << 16)
        | (static_cast<uint32_t>(green) * brightness / peak << 8)
        | static_cast<uint32_t>(blue) * brightness / peak;
  }

  // Maps RGB to FastLED's circular hue scale so preset companions rotate with the anchor.
  static uint8_t colorHue(uint32_t color) {
    const uint8_t red = color >> 16;
    const uint8_t green = color >> 8;
    const uint8_t blue = color;
    const uint8_t high = max(red, max(green, blue));
    const uint8_t low = min(red, min(green, blue));
    const uint8_t range = high - low;
    if (range == 0)
      return 0;
    if (high == red)
      return static_cast<uint8_t>(43 * static_cast<int16_t>(green - blue) / range);
    if (high == green)
      return static_cast<uint8_t>(85 + 43 * static_cast<int16_t>(blue - red) / range);
    return static_cast<uint8_t>(171 + 43 * static_cast<int16_t>(red - green) / range);
  }

  static uint32_t colorFromHsv(uint8_t hue, uint8_t saturation, uint8_t value) {
    const CRGB color = CHSV(hue, saturation, value);
    return (static_cast<uint32_t>(color.r) << 16)
        | (static_cast<uint32_t>(color.g) << 8) | color.b;
  }

  static uint8_t hueFromPaletteX(int16_t x) {
    return static_cast<uint32_t>(constrain(x, 20, 459) - 20) * 255 / 439;
  }

  // Builds eight distinct relationships while preserving the chosen color at its stop.
  void regenerateGradientPresets() {
    static constexpr uint8_t hueLayouts[8][3] = {
      {0, 18, 40}, {0, 85, 170}, {0, 105, 150}, {0, 128, 148},
      {0, 28, 196}, {0, 58, 186}, {0, 42, 92}, {0, 230, 205}
    };
    const uint32_t anchor = gradientStops[selectedGradientStop];
    const uint8_t red = anchor >> 16;
    const uint8_t green = anchor >> 8;
    const uint8_t blue = anchor;
    const uint8_t high = max(red, max(green, blue));
    const uint8_t low = min(red, min(green, blue));
    const uint8_t saturation = high == 0 ? 0
        : static_cast<uint16_t>(high - low) * 255 / high;
    const uint8_t vividSaturation = saturation < 176 ? 176 : saturation;
    const uint8_t vividValue = high < 176 ? 176 : high;
    const uint8_t anchorHue = colorHue(anchor);
    for (uint8_t preset = 0; preset < 8; preset++) {
      const uint8_t anchorOffset = hueLayouts[preset][selectedGradientStop];
      for (uint8_t stop = 0; stop < 3; stop++) {
        if (stop == selectedGradientStop) {
          gradientPresets[preset][stop] = anchor;
          continue;
        }
        const uint8_t hue = anchorHue + hueLayouts[preset][stop] - anchorOffset;
        const uint8_t valueDrop = ((preset + stop) % 3) * 20;
        gradientPresets[preset][stop] = colorFromHsv(
            hue, vividSaturation, vividValue - valueDrop);
      }
    }
  }

  void queueGradient() {
    if (!tubesS3ScheduleGradient(gradientStops))
      Serial.println(F("TubeOS: gradient queue rejected"));
  }

  void drawGradientPreview(const Rect &bounds, const uint32_t colors[3]) {
    display.fillRoundRect(bounds.x, bounds.y, bounds.width, bounds.height, 12,
                          COLOR_SURFACE_RAISED);
    constexpr int16_t sliceWidth = 8;
    for (int16_t offset = 4; offset < bounds.width - 4; offset += sliceWidth) {
      const int16_t remaining = bounds.width - 4 - offset;
      const int16_t width = remaining < sliceWidth ? remaining : sliceWidth;
      const uint8_t position = static_cast<uint32_t>(offset - 4) * 255
          / (bounds.width - 9);
      display.fillRect(bounds.x + offset, bounds.y + 4, width,
                       bounds.height - 8, rgb565(gradientColor(colors, position)));
    }
  }

  void applyGradientPreset(uint8_t preset) {
    for (uint8_t stop = 0; stop < 3; stop++)
      gradientStops[stop] = gradientPresets[preset % 8][stop];
    queueGradient();
  }

  void drawColorsContent() {
    display.fillRect(0, FIELD_OS_APP_TOP, DISPLAY_WIDTH,
                     DISPLAY_HEIGHT - FIELD_OS_APP_TOP, COLOR_BACKGROUND);
    drawGradientPreview({20, 106, 440, 36}, gradientStops);
    const int16_t stopCenters[3] = {80, 240, 400};
    for (uint8_t stop = 0; stop < 3; stop++) {
      display.fillCircle(stopCenters[stop], 162, selectedGradientStop == stop ? 20 : 16,
                         selectedGradientStop == stop ? RGB565_WHITE : COLOR_MUTED);
      display.fillCircle(stopCenters[stop], 162, selectedGradientStop == stop ? 14 : 11,
                         rgb565(gradientStops[stop]));
    }

    display.fillRoundRect(20, 192, 440, 46, 10, COLOR_SURFACE_RAISED);
    constexpr int16_t hueSliceWidth = 8;
    for (int16_t x = 24; x < 456; x += hueSliceWidth) {
      const int16_t width = min(hueSliceWidth, static_cast<int16_t>(456 - x));
      display.fillRect(x, 196, width, 38,
                       rgb565(colorFromHsv(hueFromPaletteX(x), 255, 255)));
    }

    for (uint8_t level = 0; level < 4; level++) {
      const uint32_t color = setColorBrightness(
          gradientStops[selectedGradientStop], gradientBrightness(level));
      display.fillRoundRect(20 + level * 110, 252, 105, 42, 10, rgb565(color));
    }

    for (uint8_t preset = 0; preset < 8; preset++) {
      const int16_t x = 20 + (preset % 4) * 110;
      const int16_t y = 312 + (preset / 4) * 64;
      drawGradientPreview({x, y, 105, 52}, gradientPresets[preset]);
    }
  }

  void drawUpdateContent() {
    display.fillRect(20, 104, 440, 376, COLOR_BACKGROUND);
#ifdef TUBES_S3_FIRMWARE_CARRIER
    TubesS3FieldStatus status;
    tubesS3ReadStatus(status);
    display.setTextColor(COLOR_MUTED, COLOR_BACKGROUND);
    setBodyFont();
    display.setCursor(24, 112);
    display.println(F("THIS S3 UPDATE CARRIER"));
    drawDeviceCard(136, {status.localNodeId, status.tubesVersion, status.uplinkId,
                        UINT32_MAX, "THIS DEVICE"});
    display.setTextColor(COLOR_MUTED, COLOR_BACKGROUND);
    setDetailFont();
    display.setCursor(24, 204);
    display.println(F("EMBEDDED v47 FIRMWARE"));
    for (size_t index = 0; index < tubesS3CarrierArtifactCount(); index++) {
      TubesS3CarrierArtifact artifact;
      const int16_t y = 232 + index * 38;
      display.fillRoundRect(20, y, 440, 32, 8, COLOR_SURFACE_RAISED);
      display.setTextColor(RGB565_WHITE, COLOR_SURFACE_RAISED);
      setDetailFont();
      display.setCursor(32, y + 7);
      if (!tubesS3ReadCarrierArtifact(index, artifact)) {
        display.print(F("ARTIFACT UNAVAILABLE"));
      } else {
        if (artifact.family == TubeHardwareDig2Go) display.print(F("DIG2GO"));
        else if (artifact.family == TubeHardwareAthomC3) display.print(F("ATHOM C3"));
        else display.print(F("UNKNOWN TARGET"));
        if (artifact.variant == TubeVariantStandard) display.print(F(" | STANDARD | v"));
        else display.print(F(" | VARIANT UNKNOWN | v"));
        display.print(artifact.release);
      }
    }
    drawButton({{20, 316, 150, 46}, COLOR_PRIMARY, F("Scan")});
    TubesS3CarrierStatus carrier;
    tubesS3ReadCarrierStatus(carrier);
    setDetailFont();
    display.setTextColor(COLOR_MUTED, COLOR_BACKGROUND);
    display.setCursor(190, 332);
    display.printf("Carrier state %u  |  release %u\n", carrier.state, carrier.release);
    display.setCursor(24, 372);
    display.println(F("DISCOVERED UPDATE TARGETS"));
    const size_t count = tubesS3CarrierTargetCount();
    display.setTextColor(RGB565_WHITE, COLOR_BACKGROUND);
    if (count == 0) {
      setBodyFont();
      display.setCursor(24, 412);
      display.println(F("NO DEVICES NEARBY"));
    }
    for (size_t index = 0; index < count && index < 2; index++) {
      TubesS3CarrierTarget target;
      if (!tubesS3ReadCarrierTarget(index, target)) continue;
      const int16_t y = 400 + index * 66;
      drawDeviceCard(y, {target.nodeId, target.release, target.uplinkId,
                     (millis() - target.lastSeenMs) / 1000,
                     target.family == 1 ? "DIG2GO" : "C3"});
    }
#else
    display.setTextColor(COLOR_MUTED, COLOR_BACKGROUND);
    setBodyFont();
    display.setCursor(36, 136);
    display.println(F("Carrier build required"));
    setDetailFont();
    display.setCursor(36, 178);
    display.println(F("This build has no embedded device images."));
#endif
  }

  class FieldView {
  public:
    FieldView(WaveshareS3FieldOs &owner, FieldViewId id,
              const __FlashStringHelper *title, uint32_t refreshMs)
        : owner(owner), viewId(id), viewTitle(title), refreshIntervalMs(refreshMs) {}
    virtual ~FieldView() = default;

    FieldViewId id() const { return viewId; }
    void render(bool full) {
      if (full) owner.drawChrome(viewTitle, viewId != FieldViewId::Home);
      renderContent(full);
      lastRefreshMs = millis();
      lastRevision = revision();
    }
    virtual FieldViewId tap(int16_t, int16_t) { return viewId; }
    virtual void tick(uint32_t now) {
      if (refreshIntervalMs && now - lastRefreshMs >= refreshIntervalMs) {
        lastRefreshMs = now;
        const uint32_t nextRevision = revision();
        if (nextRevision != lastRevision) render(false);
      }
    }

  protected:
    WaveshareS3FieldOs &owner;
    virtual void renderContent(bool full) = 0;
    uint32_t lastRefreshMs = 0;
    virtual uint32_t revision() { return 0; }

  private:
    FieldViewId viewId;
    const __FlashStringHelper *viewTitle;
    uint32_t refreshIntervalMs;
    uint32_t lastRevision = 0;
  };

  class HomeView final : public FieldView {
  public:
    explicit HomeView(WaveshareS3FieldOs &owner)
        : FieldView(owner, FieldViewId::Home, F("Tubes Field OS"), 0) {}
    FieldViewId tap(int16_t x, int16_t y) override {
      if (Rect{20, 128, 210, 150}.contains(x, y)) return FieldViewId::Patterns;
      if (Rect{250, 128, 210, 150}.contains(x, y)) return FieldViewId::Beats;
      if (Rect{20, 294, 210, 150}.contains(x, y)) return FieldViewId::Colors;
      if (Rect{250, 294, 210, 150}.contains(x, y)) return FieldViewId::Mesh;
      return FieldViewId::Home;
    }
  protected:
    void renderContent(bool) override { owner.drawHomeContent(); }
  };

  class PatternsView final : public FieldView {
  public:
    explicit PatternsView(WaveshareS3FieldOs &owner)
        : FieldView(owner, FieldViewId::Patterns, F("Patterns"), SAMPLE_INTERVAL_MS) {}
    FieldViewId tap(int16_t x, int16_t y) override {
      if (x >= 20 && x < 460 && y >= 148 && y < 470) {
        const uint8_t column = (x - 20) / 149;
        const uint8_t row = (y - 148) / 82;
        if (column < 3 && row < 4) {
          const uint8_t index = row * 3 + column;
          owner.nextSendFailed = !tubesS3SelectPattern(owner.patternChoiceId(index));
          owner.drawPatternsContent(false);
        }
      }
      return FieldViewId::Patterns;
    }
  protected:
    void renderContent(bool full) override { owner.drawPatternsContent(full); }
    uint32_t revision() override {
      TubesS3FieldStatus status;
      tubesS3ReadStatus(status);
      return owner.patternsRevision(status);
    }
  };

  class BeatsView final : public FieldView {
  public:
    explicit BeatsView(WaveshareS3FieldOs &owner)
        : FieldView(owner, FieldViewId::Beats, F("Beats"), MICROPHONE_PREVIEW_INTERVAL_MS) {}
    FieldViewId tap(int16_t x, int16_t y) override {
      if (Rect{20, 112, 120, 78}.contains(x, y)) {
        TubesS3FieldStatus status;
        tubesS3ReadStatus(status);
        tubesS3SetTempoListening(!status.tempoListening);
        owner.drawBeatsContent(false);
      } else if (Rect{390, 112, 70, 78}.contains(x, y)) {
        tubesS3TapDownbeat();
      } else if (x >= 20 && x < 460 && y >= 210 && y < 468) {
        const uint8_t column = (x - 20) / 149;
        const uint8_t row = (y - 210) / 86;
        if (column < 3 && row < 3) {
          tubesS3SelectBeatOverlay(row * 3 + column);
          owner.drawBeatsContent(false);
        }
      }
      return FieldViewId::Beats;
    }
  protected:
    void renderContent(bool full) override { owner.drawBeatsContent(full); }
    uint32_t revision() override {
      TubesS3FieldStatus status;
      tubesS3ReadStatus(status);
      return owner.beatsRevision(status);
    }
  };

  class MeshView final : public FieldView {
  public:
    explicit MeshView(WaveshareS3FieldOs &owner)
        : FieldView(owner, FieldViewId::Mesh, F("Mesh"), SAMPLE_INTERVAL_MS) {}
    FieldViewId tap(int16_t x, int16_t y) override {
      if (Rect{120, 408, 240, 56}.contains(x, y)) return FieldViewId::Update;
      return FieldViewId::Mesh;
    }
  protected:
    void renderContent(bool) override { owner.drawMeshContent(); }
    uint32_t revision() override {
      TubesS3FieldStatus status;
      tubesS3ReadStatus(status);
      uint32_t value = owner.mixRevision(status.localNodeId, status.tubesVersion);
      value = owner.mixRevision(value, status.uplinkId);
      for (size_t index = 0; index < status.peerCount; index++) {
        TubesS3PeerStatus peer;
        if (!tubesS3ReadPeer(index, peer)) continue;
        value = owner.mixRevision(value, peer.nodeId);
        value = owner.mixRevision(value, peer.uplinkId);
        value = owner.mixRevision(value, peer.tubesVersion);
        value = owner.mixRevision(value, (millis() - peer.lastSeenMs) / 5000);
      }
      return value;
    }
  };

  class ColorsView final : public FieldView {
  public:
    explicit ColorsView(WaveshareS3FieldOs &owner)
        : FieldView(owner, FieldViewId::Colors, F("Colors"), 0) {}
    FieldViewId tap(int16_t x, int16_t y) override {
      if (y >= 142 && y < 184) {
        owner.selectedGradientStop = x < 160 ? 0 : x < 320 ? 1 : 2;
        owner.regenerateGradientPresets();
      } else if (x >= 20 && x < 460 && y >= 192 && y < 238) {
        owner.gradientStops[owner.selectedGradientStop] = owner.colorFromHsv(
            owner.hueFromPaletteX(x), 255, 255);
        owner.regenerateGradientPresets();
        owner.queueGradient();
      } else if (x >= 20 && x < 460 && y >= 252 && y < 294) {
        const uint8_t level = (x - 20) / 110;
        owner.gradientStops[owner.selectedGradientStop] = owner.setColorBrightness(
            owner.gradientStops[owner.selectedGradientStop], owner.gradientBrightness(level));
        owner.regenerateGradientPresets();
        owner.queueGradient();
      } else if (x >= 20 && x < 460 && y >= 312 && y < 428) {
        const uint8_t column = (x - 20) / 110;
        const uint8_t row = (y - 312) / 64;
        if (column < 4 && row < 2)
          owner.applyGradientPreset(row * 4 + column);
      }
      owner.drawColorsContent();
      return FieldViewId::Colors;
    }
  protected:
    void renderContent(bool) override { owner.drawColorsContent(); }
  };

  class UpdateView final : public FieldView {
  public:
    explicit UpdateView(WaveshareS3FieldOs &owner)
        : FieldView(owner, FieldViewId::Update, F("Update"), SAMPLE_INTERVAL_MS) {}
    FieldViewId tap(int16_t x, int16_t y) override {
#ifdef TUBES_S3_FIRMWARE_CARRIER
      if (Rect{20, 252, 150, 60}.contains(x, y)) {
        tubesS3ScanCarrierTargets();
      } else if (y >= 326) {
        const size_t index = (y - 332) / 66;
        TubesS3CarrierTarget target;
        if (tubesS3ReadCarrierTarget(index, target))
          tubesS3ArmCarrier(target.mac, target.family, target.variant, target.release);
      }
#endif
      return FieldViewId::Update;
    }
  protected:
    void renderContent(bool) override { owner.drawUpdateContent(); }
    uint32_t revision() override {
#ifdef TUBES_S3_FIRMWARE_CARRIER
      TubesS3CarrierStatus carrier;
      tubesS3ReadCarrierStatus(carrier);
      uint32_t value = owner.mixRevision(carrier.state, carrier.release);
      const size_t count = tubesS3CarrierTargetCount();
      value = owner.mixRevision(value, count);
      for (size_t index = 0; index < count; index++) {
        TubesS3CarrierTarget target;
        if (!tubesS3ReadCarrierTarget(index, target)) continue;
        value = owner.mixRevision(value, target.nodeId);
        value = owner.mixRevision(value, target.uplinkId);
        value = owner.mixRevision(value, target.release);
        value = owner.mixRevision(value, (millis() - target.lastSeenMs) / 5000);
      }
      return value;
#else
      return 0;
#endif
    }
  };

  class ViewManager {
  public:
    ViewManager(WaveshareS3FieldOs &owner, HomeView &home, PatternsView &patterns,
                BeatsView &beats, MeshView &mesh, ColorsView &colors, UpdateView &update)
        : owner(owner), home(home), patterns(patterns), beats(beats), mesh(mesh),
          colors(colors), update(update), active(&home) {}

    void begin() { active->render(true); }
    void redraw() { active->render(true); }
    void tick(uint32_t now) { active->tick(now); }
    void tap(int16_t x, int16_t y) {
      if (y < FIELD_OS_HEADER_HEIGHT) {
        if (active->id() != FieldViewId::Home) navigate(FieldViewId::Home);
        return;
      }
      const FieldViewId destination = active->tap(x, y);
      if (destination != active->id()) navigate(destination);
    }

  private:
    void navigate(FieldViewId id) {
      active = view(id);
      active->render(true);
    }
    FieldView *view(FieldViewId id) {
      switch (id) {
        case FieldViewId::Patterns: return &patterns;
        case FieldViewId::Beats: return &beats;
        case FieldViewId::Mesh: return &mesh;
        case FieldViewId::Colors: return &colors;
        case FieldViewId::Update: return &update;
        case FieldViewId::Home: default: return &home;
      }
    }

    WaveshareS3FieldOs &owner;
    HomeView &home;
    PatternsView &patterns;
    BeatsView &beats;
    MeshView &mesh;
    ColorsView &colors;
    UpdateView &update;
    FieldView *active;
  };

  HomeView homeView;
  PatternsView patternsView;
  BeatsView beatsView;
  MeshView meshView;
  ColorsView colorsView;
  UpdateView updateView;
  ViewManager viewManager;

public:
  WaveshareS3FieldOs()
      : homeView(*this), patternsView(*this), beatsView(*this), meshView(*this),
        colorsView(*this), updateView(*this),
        viewManager(*this, homeView, patternsView, beatsView, meshView, colorsView,
                    updateView) {}

  void setup() override {
    Wire.begin(PERIPHERAL_SDA, PERIPHERAL_SCL);
    microphoneReady = initializeMicrophones();
    pmuReady = pmu.begin(Wire, AXP2101_SLAVE_ADDRESS, PERIPHERAL_SDA, PERIPHERAL_SCL);
    if (pmuReady) {
      pmu.disableTSPinMeasure();
      pmu.enableBattDetection();
      pmu.enableBattVoltageMeasure();
      pmu.enableVbusVoltageMeasure();
      pmu.disableIRQ(XPOWERS_AXP2101_ALL_IRQ);
      pmu.clearIrqStatus();
      pmu.enableIRQ(XPOWERS_AXP2101_PKEY_SHORT_IRQ);
      pmu.setPowerKeyPressOffTime(XPOWERS_POWEROFF_10S);
      pmu.enableLongPressShutdown();
      pmu.setLongPressRestart();
      samplePower(millis(), true);
    }
    displayReady = display.begin();
    if (displayReady) {
      display.setBrightness(
#ifdef TUBES_S3_FIELD_OS
        FIELD_OS_DEFAULT_BRIGHTNESS
#else
        SMOKE_DEFAULT_BRIGHTNESS
#endif
      );
      display.setTextWrap(false);
    }
    pinMode(TOUCH_RESET, OUTPUT);
    digitalWrite(TOUCH_RESET, LOW);
    delay(10);
    digitalWrite(TOUCH_RESET, HIGH);
    delay(50);
    pinMode(TOUCH_IRQ, INPUT_PULLUP);
    touchReady = touch.begin(Wire, CST92XX_SLAVE_ADDRESS, PERIPHERAL_SDA, PERIPHERAL_SCL);
    if (touchReady) {
      touch.setMaxCoordinates(DISPLAY_WIDTH, DISPLAY_HEIGHT);
      touchInterruptPending = false;
      attachInterrupt(TOUCH_IRQ, handleTouchInterrupt, FALLING);
    }
    lastActivityMs = millis();
    regenerateGradientPresets();
    if (displayReady) viewManager.begin();
  }

  void loop() override {
    if (touchReady && touchInterruptPending) {
      touchInterruptPending = false;
      int16_t x = -1;
      int16_t y = -1;
      const bool pressed = touch.getPoint(&x, &y, 1) > 0;
      if (screenOn && pressed) {
        lastActivityMs = millis();
        if (!touchDown) viewManager.tap(x, y);
      }
      touchDown = pressed;
    }
    if (!displayReady) return;
    const uint32_t now = millis();
    tickShell(now);
    if (screenOn) viewManager.tick(now);
  }

  bool handleButton(uint8_t b) override {
    if (b >= WLED_MAX_BUTTONS) return false;
    const bool pressed = isButtonPressed(b);
    if (pressed && !physicalButtonDown[b]) {
      lastActivityMs = millis();
      if (!screenOn) setScreenOn(true);
    }
    physicalButtonDown[b] = pressed;
    return true;
  }

  void addToJsonInfo(JsonObject &root) override {
    JsonObject user = root[F("u")];
    if (user.isNull()) user = root.createNestedObject(F("u"));
    JsonArray fieldOs = user.createNestedArray(F("S3 field OS"));
    fieldOs.add(displayReady ? F("display OK") : F("display FAIL"));
    fieldOs.add(touchReady ? F("touch OK") : F("touch FAIL"));
    fieldOs.add(pmuReady ? F("PMU OK") : F("PMU FAIL"));
    fieldOs.add(microphoneReady ? F("microphones OK") : F("microphones FAIL"));
  }
};

static WaveshareS3FieldOs waveshareS3FieldOs;
REGISTER_USERMOD(waveshareS3FieldOs);
#else

class WaveshareS3PeripheralSmoke : public Usermod {
private:
  bool displayReady = false;
  bool touchReady = false;
  bool pmuReady = false;
  bool imuReady = false;
  uint8_t displayBrightness =
#ifdef TUBES_S3_FIELD_OS
    FIELD_OS_DEFAULT_BRIGHTNESS;
#else
    SMOKE_DEFAULT_BRIGHTNESS;
#endif
  uint32_t lastSample = 0;
  int16_t touchX = -1;
  int16_t touchY = -1;
  uint16_t batteryMv = 0;
  bool usbPresent = false;
  bool charging = false;
  float accelX = 0.0f;
  float accelY = 0.0f;
  float accelZ = 0.0f;

  // Samples only board-local peripherals and never enters a Tubes transport path.
  void samplePeripherals() {
    if (pmuReady) {
      batteryMv = pmu.getBattVoltage();
      usbPresent = pmu.isVbusIn();
      charging = pmu.isCharging();
    }

    if (imuReady) imu.getAccelerometer(accelX, accelY, accelZ);

  }

  // Consumes the CST9217's falling-edge notification before its short IRQ pulse is lost.
  void sampleTouch() {
    if (!touchReady || !touchInterruptPending) return;
    touchInterruptPending = false;
    int16_t x = -1;
    int16_t y = -1;
    if (touch.getPoint(&x, &y, 1) > 0) {
      touchX = x;
      touchY = y;
    }
  }

  // Paints a stable diagnostic surface intended for first hardware bring-up.
  void drawStatus() {
    if (!displayReady) return;

    display.fillScreen(RGB565_BLACK);
    display.setCursor(12, 14);
    display.setTextColor(RGB565_CYAN);
    display.setTextSize(2);
    display.println(F("WLEDTubes S3 smoke"));
    display.setTextColor(RGB565_WHITE);
    display.setTextSize(2);
    display.setCursor(12, 62);
    display.print(F("Display  OK   BRI "));
    display.println(displayBrightness);
    display.setCursor(12, 104);
    display.print(F("Touch    "));
    display.print(touchReady ? F("OK") : F("FAIL"));
    display.print(F("   "));
    display.print(touchX);
    display.print(F(","));
    display.println(touchY);
    display.setCursor(12, 146);
    display.print(F("PMU      "));
    display.print(pmuReady ? F("OK") : F("FAIL"));
    display.print(F("   "));
    display.print(batteryMv);
    display.println(F(" mV"));
    display.setCursor(12, 188);
    display.print(F("USB      "));
    display.print(usbPresent ? F("YES") : F("NO"));
    display.print(F("   CHG "));
    display.println(charging ? F("YES") : F("NO"));
    display.setCursor(12, 230);
    display.print(F("IMU      "));
    display.println(imuReady ? F("OK") : F("FAIL"));
    display.setCursor(12, 272);
    display.print(F("ACC X "));
    display.println(accelX, 2);
    display.setCursor(12, 314);
    display.print(F("ACC Y "));
    display.println(accelY, 2);
    display.setCursor(12, 356);
    display.print(F("ACC Z "));
    display.println(accelZ, 2);
    display.setTextSize(1);
    display.setTextColor(RGB565_YELLOW);
    display.setCursor(12, 414);
    display.println(F("TOUCH: COORDINATES ONLY"));
    display.setCursor(12, 438);
    display.println(F("No LED output. No smoke-test radio TX."));
  }

public:
  void setup() override {
    Wire.begin(PERIPHERAL_SDA, PERIPHERAL_SCL);

    displayReady = display.begin();
    if (displayReady) {
      display.setBrightness(displayBrightness);
      display.setTextWrap(false);
    }

    pinMode(TOUCH_RESET, OUTPUT);
    digitalWrite(TOUCH_RESET, LOW);
    delay(10);
    digitalWrite(TOUCH_RESET, HIGH);
    delay(50);
    pinMode(TOUCH_IRQ, INPUT_PULLUP);
    touchReady = touch.begin(Wire, CST92XX_SLAVE_ADDRESS, PERIPHERAL_SDA, PERIPHERAL_SCL);
    if (touchReady) {
      touch.setMaxCoordinates(DISPLAY_WIDTH, DISPLAY_HEIGHT);
      touchInterruptPending = false;
      attachInterrupt(TOUCH_IRQ, handleTouchInterrupt, FALLING);
    }

    pmuReady = pmu.begin(Wire, AXP2101_SLAVE_ADDRESS, PERIPHERAL_SDA, PERIPHERAL_SCL);
    if (pmuReady) {
      pmu.enableBattVoltageMeasure();
      pmu.enableVbusVoltageMeasure();
    }

    imuReady = imu.begin(Wire, QMI8658_L_SLAVE_ADDRESS, PERIPHERAL_SDA, PERIPHERAL_SCL);
    if (imuReady) {
      imu.configAccelerometer(SensorQMI8658::ACC_RANGE_2G, SensorQMI8658::ACC_ODR_31_25Hz);
      imu.enableAccelerometer();
    }

    samplePeripherals();
    drawStatus();
  }

  void loop() override {
    sampleTouch();
    const uint32_t now = millis();
    if (now - lastSample < SAMPLE_INTERVAL_MS) return;
    lastSample = now;
    samplePeripherals();
    drawStatus();
  }

  void addToJsonInfo(JsonObject &root) override {
    JsonObject user = root[F("u")];
    if (user.isNull()) user = root.createNestedObject(F("u"));
    JsonArray smoke = user.createNestedArray(F("S3 peripheral smoke"));
    smoke.add(displayReady ? F("display OK") : F("display FAIL"));
    smoke.add(touchReady ? F("touch OK") : F("touch FAIL"));
    smoke.add(pmuReady ? F("PMU OK") : F("PMU FAIL"));
    smoke.add(imuReady ? F("IMU OK") : F("IMU FAIL"));

    JsonArray battery = user.createNestedArray(F("S3 battery"));
    battery.add(batteryMv);
    battery.add(F(" mV"));
    JsonArray power = user.createNestedArray(F("S3 power"));
    power.add(usbPresent ? F("USB") : F("battery"));
    power.add(charging ? F(", charging") : F(""));
  }
};

static WaveshareS3PeripheralSmoke waveshareS3PeripheralSmoke;
REGISTER_USERMOD(waveshareS3PeripheralSmoke);
#endif
} // namespace

// Forced-link anchor for the board-specific PlatformIO environment.
extern "C" void waveshareS3TubesRemoteLinkAnchor() {}
// AI: end

#endif
