#include <cstddef>
#include <cstdint>
#include <vector>

#include "bus_virtual_framebuffer_contract.h"

namespace {

// AI: below section was generated by an AI
constexpr int ERR_NONE = 0;
constexpr int ERR_NORAM_PX = 1;

struct AllocatorReturningSentinelForZero {
  unsigned calls = 0;

  uint32_t *allocate(unsigned count) {
    calls++;
    return count == 0 ? reinterpret_cast<uint32_t *>(1) : new uint32_t[count]();
  }
};

struct HostFramebuffer {
  HostFramebuffer(unsigned count, AllocatorReturningSentinelForZero& allocator)
    : data(isVirtualFramebufferCountValid(count) ? allocator.allocate(count) : nullptr)
    , valid(isVirtualFramebufferCountValid(count) && data != nullptr)
  {}

  ~HostFramebuffer() {
    delete[] data;
  }

  uint32_t *data;
  bool valid;
};

struct HostBusManager {
  int add(unsigned count, AllocatorReturningSentinelForZero& allocator) {
    if (!isVirtualFramebufferCountValid(count)) {
      error = ERR_NORAM_PX;
      return -1;
    }
    HostFramebuffer framebuffer(count, allocator);
    if (!framebuffer.valid) {
      error = ERR_NORAM_PX;
      return -1;
    }
    busses.push_back(count);
    return static_cast<int>(busses.size());
  }

  int error = ERR_NONE;
  std::vector<unsigned> busses;
};

static_assert(!isVirtualFramebufferCountValid(0), "zero pixels must be rejected");
static_assert(isVirtualFramebufferCountValid(1), "positive framebuffer counts remain valid");

} // namespace

int main() {
  AllocatorReturningSentinelForZero allocator;
  HostFramebuffer zeroFramebuffer(0, allocator);
  if (zeroFramebuffer.valid || zeroFramebuffer.data != nullptr || allocator.calls != 0) return 1;

  HostBusManager manager;
  if (manager.add(0, allocator) != -1) return 2;
  if (manager.error != ERR_NORAM_PX || !manager.busses.empty() || allocator.calls != 0) return 3;

  if (manager.add(2, allocator) != 1) return 4;
  if (manager.busses.size() != 1 || manager.busses.front() != 2 || allocator.calls != 1) return 5;
  return 0;
}
// AI: end
