import { ESPLoader, Transport } from "./vendor/esptool-js/bundle.js";

// AI: below section was generated by an AI
let activeConnection = null;
let flashInProgress = false;

export function chipFamily(value) {
	const chip = String(value).toUpperCase().replaceAll("_", "-").replace(/\s+/g, "");
	for (const family of ["ESP32-S3", "ESP32-S2", "ESP32-C2", "ESP32-C3", "ESP32-C5", "ESP32-C6", "ESP32-C61", "ESP32-H2", "ESP32-P4", "ESP8266"]) if (chip.startsWith(family)) return family;
	if (chip === "ESP32" || chip.startsWith("ESP32-")) return "ESP32";
	return chip;
}

function expectedFlashSize(bytes) {
	const megabytes = bytes / (1024 * 1024);
	if (!Number.isInteger(megabytes)) throw new Error("Unsupported firmware flash size");
	return `${megabytes}MB`;
}

async function sha256Hex(bytes) {
	const digest = await crypto.subtle.digest("SHA-256", bytes);
	return Array.from(new Uint8Array(digest), (byte) => byte.toString(16).padStart(2, "0")).join("");
}

async function fetchVerifiedImage(variant, artifact) {
	const response = await fetch(`/api/firmware/${encodeURIComponent(variant.id)}/usb`, { headers: {
		"X-Easy-Flash-Hardware-Family": variant.target.hardwareFamily,
		"X-Easy-Flash-Chip": variant.target.chip,
		"X-Easy-Flash-Flash-Bytes": String(variant.target.flashSizeBytes),
		"X-Easy-Flash-Partition-Sha256": variant.partition.tableSha256,
	} });
	if (!response.ok) throw new Error("Firmware image is unavailable");
	const bytes = new Uint8Array(await response.arrayBuffer());
	if (bytes.byteLength !== artifact.sizeBytes) throw new Error("Firmware image size does not match");
	if (await sha256Hex(bytes) !== artifact.sha256) throw new Error("Firmware image did not pass its safety check");
	return bytes;
}

export function canFlashLocally() {
	return window.isSecureContext && "serial" in navigator;
}

// Opens the browser-required chooser once and proves only the ROM chip family.
export async function connectToController({ variant, onStatus }) {
	if (!canFlashLocally()) throw new Error("Open Easy Flash in the desktop app or desktop Chrome/Edge");
	if (activeConnection) await disconnectController();
	onStatus("Choose the USB controller…");
	const port = await navigator.serial.requestPort();
	const portInfo = port.getInfo();
	const transport = new Transport(port, true);
	try {
		const terminal = { clean() {}, writeLine(message) { if (/chip|detect|connect/i.test(message)) onStatus(message); }, write(message) { if (/chip|detect|connect/i.test(message)) onStatus(message); } };
		const loader = new ESPLoader({ transport, baudrate:115200, terminal, debugLogging:false });
		onStatus("Identifying the controller chip…");
		const chipName = await loader.main();
		if (chipFamily(chipName) !== chipFamily(variant.target.chip)) throw new Error(`This is a ${chipName}, not the supported ${variant.target.chip} controller`);
		activeConnection = { loader, transport, portInfo, chipName };
		return { chipName, chipFamily:chipFamily(chipName), portInfo, proof:"chip-only", exactBoard:false };
	} catch (error) {
		try { await transport.disconnect(); } catch {}
		throw error;
	}
}
export async function disconnectController() {
	if (!activeConnection) return;
	try { await activeConnection.transport.disconnect(); } catch {}
	activeConnection = null;
}

// Writes only after a separate explicit Install action using the already-inspected connection.
export async function installConnectedController({ variant, artifact, onStatus, onProgress }) {
	if (flashInProgress) throw new Error("An install is already running");
	if (!activeConnection) throw new Error("Connect the controller again before installing");
	if (artifact.transport !== "usb" || artifact.kind !== "complete-merged-image" || artifact.offset !== 0) throw new Error("The bundled recovery image is not installable");
	flashInProgress = true;
	const { loader, transport, chipName } = activeConnection;
	try {
		onStatus("Checking the bundled firmware…");
		const image = await fetchVerifiedImage(variant, artifact);
		const fileArray = artifact.components.map((component) => ({ data:image.slice(component.offset, component.offset + component.sizeBytes), address:component.offset }));
		if (!fileArray.length) throw new Error("The firmware image is incomplete");
		onStatus("Backup is unavailable in this browser flow. Installing without erasing saved settings…");
		await loader.writeFlash({ fileArray, flashMode:variant.target.flashMode || "keep", flashFreq:"keep", flashSize:expectedFlashSize(variant.target.flashSizeBytes), eraseAll:false, compress:false, reportProgress(_index,written,total) { onProgress(Math.round((written / total) * 100)); } });
		onStatus("Restarting the controller…");
		await loader.after("hard_reset");
		await new Promise((resolve) => setTimeout(resolve, 3000));
		onProgress(100);
		return { chipName, bytesWritten:image.byteLength, sha256:artifact.sha256, backup:"unavailable", readback:"writer-verified", health:"unverified" };
	} finally {
		flashInProgress = false;
		activeConnection = null;
		try { await transport.disconnect(); } catch {}
	}
}
// AI: end
