#!/usr/bin/env node
import fs from 'node:fs';
import {generatedOutputs, loadContract, validateContract} from './update-contract.mjs';

// AI: below section was generated by an AI
const contract = loadContract();
const errors = validateContract(contract);
if (errors.length) throw new Error(errors.join('\n'));
const check = process.argv.includes('--check');
let dirty = false;
for (const [file, content] of generatedOutputs(contract)) {
  if (check) {
    if (!fs.existsSync(file) || fs.readFileSync(file, 'utf8') !== content) {
      console.error(`generated output is stale: ${file}`);
      dirty = true;
    }
  } else {
    fs.mkdirSync(new URL('.', `file://${file}`), {recursive: true});
    fs.writeFileSync(file, content);
  }
}
if (dirty) process.exit(1);
console.log(check ? 'Generated update contract outputs are clean' : 'Generated update contract outputs written');
// AI: end
