import assert from 'node:assert/strict';
import {execFileSync, spawnSync} from 'node:child_process';
import fs from 'node:fs';
import path from 'node:path';
import test from 'node:test';
import {fileURLToPath, pathToFileURL} from 'node:url';

import {
  contractPath,
  cppOutputPath,
  generatedOutputs,
  jsOutputPath,
  loadContract,
  parsePartitionCsv,
  renderCpp,
  renderJs, validatePartitionRows,
  validateContract
} from './update-contract.mjs';

// AI: below section was generated by an AI
const root = path.resolve(path.dirname(fileURLToPath(import.meta.url)), '../..');
const clone = value => structuredClone(value);
const pioAvailable = spawnSync('pio', ['--version'], {stdio: 'ignore'}).status === 0;

test('canonical update contract and pinned files validate', () => {
  assert.deepEqual(validateContract(loadContract()), []);
});

test('Athom C3 target preserves Steve main exact compiled hardware contract', () => {
  const contract = loadContract();
  const target = contract.targets.find(item => item.id === 'athom-c3-tubes');
  assert.ok(target);
  assert.deepEqual(target.compiledProfile, {
    environment: 'esp32-c3-athom_tubes',
    releaseIdentity: 'ESP32-C3_ATHOM_TUBES',
    ledPin: 10,
    buttonPin: 9,
    ledCount: 150
  });
  assert.equal(target.chipFamily, 'ESP32-C3');
  assert.equal(target.board, 'esp32-c3-devkitm-1');
  assert.equal(target.flashMode, 'dio');
  assert.equal(target.flashSizeBytes, 4194304);
  assert.deepEqual(target.partition.otaSlots, [
    {id: 'ota_0', offset: 65536, sizeBytes: 1572864},
    {id: 'ota_1', offset: 1638400, sizeBytes: 1572864}
  ]);

  const artifacts = contract.artifacts.filter(item => item.targetId === target.id);
  assert.deepEqual(artifacts.map(item => item.transport).sort(), ['ota', 'usb']);
  assert.ok(artifacts.every(item => item.releaseIdentity === target.compiledProfile.releaseIdentity));
  assert.ok(artifacts.every(item => item.buildSourceState.includes('generated C3 contract projection')));
  assert.ok(artifacts.every(item => item.lengthBytes <= target.flashSizeBytes));
  const header = fs.readFileSync(cppOutputPath, 'utf8');
  assert.match(header, /CANONICAL_TARGET_ATHOM_C3_TUBES[\s\S]*CanonicalTargetAthomC3Tubes, 2, 1,/);
});

test('Waveshare S3 target is a flash-only compiled hardware contract', () => {
  const contract = loadContract();
  const target = contract.targets.find(item => item.id === 'waveshare-s3-tubes-remote');
  assert.ok(target);
  assert.deepEqual(target.compiledProfile, {
    environment: 'waveshare_s3_tubes_target',
    releaseIdentity: 'WAVESHARE_S3_TUBES_TARGET'
  });
  assert.equal(target.chipFamily, 'ESP32-S3');
  assert.equal(target.board, 'esp32-s3-devkitc-1');
  assert.equal(target.flashMode, 'qio');
  assert.equal(target.flashSizeBytes, 16777216);
  assert.deepEqual(target.partition.otaSlots, [
    {id: 'ota_0', offset: 65536, sizeBytes: 6291456},
    {id: 'ota_1', offset: 6356992, sizeBytes: 6291456}
  ]);

  const artifacts = contract.artifacts.filter(item => item.targetId === target.id);
  assert.deepEqual(artifacts.map(item => item.transport).sort(), ['ota', 'usb']);
  assert.ok(artifacts.every(item => item.releaseIdentity === target.compiledProfile.releaseIdentity));
  assert.ok(artifacts.every(item => item.lengthBytes <= target.flashSizeBytes));
  assert.ok(artifacts.find(item => item.transport === 'ota').lengthBytes <= target.partition.otaSlots[0].sizeBytes);
  const header = fs.readFileSync(cppOutputPath, 'utf8');
  assert.match(header, /CANONICAL_TARGET_WAVESHARE_S3_TUBES_REMOTE[\s\S]*CanonicalTargetWaveshareS3TubesRemote, 3, 2,/);
});

// Resolve the composed PlatformIO configuration when the optional firmware
// toolchain is installed; Node-only environments still exercise the contract.
test('Waveshare S3 effective build preserves exact flash and USB identity', {
  skip: pioAvailable ? false : 'PlatformIO is not installed'
}, () => {
  const output = execFileSync('pio', ['project', 'config', '--json-output'], {
    cwd: root,
    encoding: 'utf8'
  });
  const sections = new Map(JSON.parse(output).map(([name, options]) => [name, Object.fromEntries(options)]));
  const environment = sections.get('env:waveshare_s3_tubes_target');
  assert.ok(environment);
  assert.equal(environment.board, 'esp32-s3-devkitc-1');
  assert.equal(environment['board_build.flash_mode'], 'qio');
  assert.equal(environment['board_upload.flash_size'], '16MB');
  assert.equal(environment['board_upload.maximum_size'], '16777216');
  assert.equal(environment['board_build.arduino.memory_type'], 'qio_opi');
  assert.equal(environment['board_build.partitions'], 'contracts/update/partitions/WLED_ESP32S3_WAVESHARE_16MB.csv');
  const flags = [].concat(environment.build_flags).join(' ');
  assert.match(flags, /WLED_RELEASE_NAME=\\\"WAVESHARE_S3_TUBES_TARGET\\\"/);
  assert.equal((flags.match(/ARDUINO_USB_CDC_ON_BOOT=1/g) || []).length, 1);
  for (const excluded of ['WaveshareS3CompileCanary', 'TUBES_NULL_OUTPUT', 'TUBES_READ_ONLY_FIELD_SHELL'])
    assert.doesNotMatch(flags + ' ' + environment.custom_usermods, new RegExp(excluded));
});

test('duplicate and unknown identities fail closed', () => {
  const canonical = loadContract();
  const duplicateTarget = clone(canonical);
  duplicateTarget.targets.push(clone(duplicateTarget.targets[0]));
  assert.match(validateContract(duplicateTarget, {checkFiles: false}).join('\n'), /duplicate target id/);

  const duplicateArtifact = clone(canonical);
  duplicateArtifact.artifacts.push(clone(duplicateArtifact.artifacts[0]));
  assert.match(validateContract(duplicateArtifact, {checkFiles: false}).join('\n'), /duplicate artifact id/);

  const unknownTarget = clone(canonical);
  unknownTarget.artifacts[0].targetId = 'unknown-target';
  assert.match(validateContract(unknownTarget, {checkFiles: false}).join('\n'), /unknown targetId/);

  const unknownClass = clone(canonical);
  unknownClass.artifacts[0].releaseClass = 'Unknown';
  assert.match(validateContract(unknownClass, {checkFiles: false}).join('\n'), /unknown releaseClass/);

  const missingIdentity = clone(canonical);
  delete missingIdentity.artifacts[0].releaseIdentity;
  assert.match(validateContract(missingIdentity, {checkFiles: false}).join('\n'), /missing releaseIdentity/);
});

test('numeric discriminators are unique, ranged, and state values are frozen', () => {
  for (const key of ['releaseClasses', 'targets', 'artifacts', 'updateStates']) {
    const contract = loadContract();
    contract[key][1].cppValue = contract[key][0].cppValue;
    assert.match(validateContract(contract, {checkFiles: false}).join('\n'), /duplicate .* cppValue/);
    contract[key][1].cppValue = 256;
    assert.match(validateContract(contract, {checkFiles: false}).join('\n'), /invalid cppValue/);
  }
  const changedState = loadContract();
  changedState.updateStates.find(item => item.id === 'Complete').cppValue = 7;
  assert.match(validateContract(changedState, {checkFiles: false}).join('\n'), /must preserve cppValue 5/);
});

test('partition CSV parser and semantic geometry fail closed', () => {
  const contract = loadContract();
  for (const target of contract.targets) {
    const rows = parsePartitionCsv(fs.readFileSync(path.join(root, target.partition.csvPath), 'utf8'));
    const errors = [];
    validatePartitionRows(errors, target, rows);
    assert.deepEqual(errors, []);
    assert.equal(rows.filter(row => row.type === 'app' && row.subtype.startsWith('ota_')).length, 2);
  }
  assert.throws(() => parsePartitionCsv('bad,app,ota_0,0x10000,wat,'), /invalid offset or size/);
  assert.throws(() => parsePartitionCsv('bad,app,ota_0,0x10000,0x10000'), /6 columns/);
  assert.throws(() => parsePartitionCsv('bad,garbage,ota_0,0x10000,0x10000,'), /unsupported tokens/);
  assert.throws(() => parsePartitionCsv('bad,app,ota 0,0x10000,0x10000,'), /unsupported tokens/);
  assert.throws(() => parsePartitionCsv('bad,app,ota_0,0x10000,0x10000,encrypted'), /unsupported tokens/);
  const target = contract.targets[0];
  const rows = parsePartitionCsv(fs.readFileSync(path.join(root, target.partition.csvPath), 'utf8'));
  rows.find(row => row.subtype === 'ota_1').offset += 0x10000;
  const errors = [];
  validatePartitionRows(errors, target, rows);
  assert.match(errors.join('\n'), /geometry does not match|rows overlap/);
});

test('generated C++ names cannot collide', () => {
  const contract = loadContract();
  const duplicate = clone(contract.artifacts[0]);
  duplicate.id = 'dig2go_v14_usb_merged';
  duplicate.cppValue = 3;
  contract.artifacts.push(duplicate);
  assert.match(validateContract(contract, {checkFiles: false}).join('\n'), /duplicate generated artifact name/);
});

test('artifact vocabularies, combinations, identities, and bounds are closed', () => {
  const cases = [
    ['kind', 'mystery', /unsupported kind/],
    ['transport', 'wifi', /unsupported transport/],
    ['transport', 'usb', /application image must use OTA/],
    ['writeOffset', 0, /OTA application must not have writeOffset/],
    ['buildOffset', -1, /invalid buildOffset/],
    ['buildCommit', '02abdd5d', /invalid buildCommit/],
    ['lengthBytes', 99999999, /exceeds every OTA slot/],
  ];
  for (const [field, value, pattern] of cases) {
    const contract = loadContract();
    Object.assign(contract.artifacts[1], {[field]: value});
    assert.match(validateContract(contract, {checkFiles: false}).join('\n'), pattern);
  }
  const merged = loadContract();
  merged.artifacts[0].components[0].sha256 = 'bad';
  assert.match(validateContract(merged, {checkFiles: false}).join('\n'), /invalid sha256/);
  const mergedOffset = loadContract();
  mergedOffset.artifacts[0].writeOffset = 65536;
  assert.match(validateContract(mergedOffset, {checkFiles: false}).join('\n'), /writeOffset must be 0/);
  const duplicate = loadContract();
  duplicate.artifacts[0].components[1].id = duplicate.artifacts[0].components[0].id;
  assert.match(validateContract(duplicate, {checkFiles: false}).join('\n'), /duplicate .* component id/);
});

// A merged image and its OTA artifact represent one build, so their application
// bytes must remain identical even when both individual files are internally valid.
test('merged and OTA artifacts from one build share exact application bytes', () => {
  const mismatchedApplication = loadContract();
  mismatchedApplication.artifacts.find(item => item.id === 'waveshare-s3-v14-ota-application').sha256 = '0'.repeat(64);
  assert.match(validateContract(mismatchedApplication, {checkFiles: false}).join('\n'),
    /merged.*application does not match/i);

  const missingOtaPair = loadContract();
  missingOtaPair.artifacts.find(item => item.id === 'waveshare-s3-v14-ota-application').buildSourceState += ' mismatch';
  assert.match(validateContract(missingOtaPair, {checkFiles: false}).join('\n'),
    /missing matching OTA application/);
});

test('generated outputs are deterministic and committed clean', () => {
  const contract = loadContract();
  assert.equal(renderJs(contract), renderJs(clone(contract)));
  assert.equal(renderCpp(contract), renderCpp(clone(contract)));
  for (const [file, content] of generatedOutputs(contract))
    assert.equal(fs.readFileSync(file, 'utf8'), content, `${path.relative(root, file)} is stale`);
});

test('JS and minimal C++ admission fields have parity for two slots and artifacts', async () => {
  const moduleUrl = `${pathToFileURL(jsOutputPath).href}?test=${Date.now()}`;
  const {updateContract} = await import(moduleUrl);
  const header = fs.readFileSync(cppOutputPath, 'utf8');
  for (const target of updateContract.targets) {
    assert.match(header, new RegExp(`${target.flashSizeBytes}U, 2,`));
    for (const slot of target.partition.otaSlots)
      assert.match(header, new RegExp(`\\{${slot.offset}U, ${slot.sizeBytes}U\\}`));
    for (const byte of target.partition.sha256.match(/../g)) assert.match(header, new RegExp(`0x${byte}`));
  }
  for (const artifact of updateContract.artifacts) {
    assert.match(header, new RegExp(`${artifact.lengthBytes}U`));
    for (const byte of artifact.sha256.match(/../g)) assert.match(header, new RegExp(`0x${byte}`));
  }
  assert.match(header, /Minimal firmware admission projection/);
  const headerCode = header.split('\n').filter(line => !line.trim().startsWith('//')).join('\n');
  for (const omittedField of [
    'hardwareFamily', 'board', 'csvPath', 'hardwareAcceptance', 'compiledProfile', 'buildSourceState', 'tubesRelease',
    'wledBaseVersion', 'releaseIdentity', 'buildCommit', 'path', 'components',
    'writeOffset', 'buildOffset'
  ])
    assert.doesNotMatch(headerCode, new RegExp(`\\b${omittedField}\\b`));
  for (const omitted of ['DIG2GO_TUBES', 'c6522acef3e954b14aad30d6f687cdb99bd1624e'])
    assert.doesNotMatch(header, new RegExp(omitted));
});

test('wire layout and command/action registry remain frozen', () => {
  const mesh = fs.readFileSync(path.join(root, 'usermods/Tubes/mesh_protocol.h'), 'utf8');
  const state = fs.readFileSync(path.join(root, 'usermods/Tubes/global_state.h'), 'utf8');
  const report = fs.readFileSync(path.join(root, 'usermods/Tubes/device_report_protocol.h'), 'utf8');
  const controller = fs.readFileSync(path.join(root, 'usermods/Tubes/controller.h'), 'utf8');
  assert.match(mesh, /static_assert\(sizeof\(NodeMessage\) == 84/);
  const commands = [...state.matchAll(/COMMAND_[A-Z]+\s*=\s*(0x[0-9A-F]+)/g)].map(match => match[1]);
  assert.deepEqual(commands, ['0x10', '0x20', '0x30', '0x40', '0x50', '0xE0', '0xF0']);
  assert.match(report, /DEVICE_REPORT_ACTION_KEY = 'z'/);
  assert.match(report, /static_assert\(sizeof\(DeviceReportMessage\) == 38/);
  assert.match(controller, /static_assert\(sizeof\(Action\) == 2/);
});

test('canonical source remains valid JSON', () => {
  assert.doesNotThrow(() => JSON.parse(fs.readFileSync(contractPath, 'utf8')));
});
// AI: end
