#!/usr/bin/env node
import {loadContract, validateContract} from './update-contract.mjs';

// AI: below section was generated by an AI
const errors = validateContract(loadContract());
if (errors.length) {
  for (const error of errors) console.error(error);
  process.exit(1);
}
console.log('Update contract is valid');
// AI: end
