import concurrent.futures
import hashlib
import pathlib
import sys
import tempfile
import threading
import unittest
import urllib.error
import urllib.request


REPO_DIR = pathlib.Path(__file__).resolve().parents[2]
sys.path.insert(0, str(REPO_DIR / "usermods" / "Tubes"))
import fleet_update_server as SERVER  # noqa: E402


# AI: below section was generated by an AI

NONCE = 0x89ABCDEF
RELEASE = 22


class RunningFleetServer:
    """Own one real threaded HTTP server for an integration-test scenario."""

    def __init__(self, firmware: pathlib.Path, devices: dict[str, SERVER.FleetDevice]) -> None:
        image = SERVER.FirmwareImage.from_path(firmware, "DIG2GO_TUBES")
        self.server = SERVER.FleetUpdateHTTPServer(
            ("127.0.0.1", 0),
            NONCE,
            RELEASE,
            devices,
            {(1, 0): image},
        )
        self.thread = threading.Thread(target=self.server.serve_forever, daemon=True)

    def __enter__(self) -> "RunningFleetServer":
        self.thread.start()
        return self

    def __exit__(self, *ignored: object) -> None:
        self.server.shutdown()
        self.server.server_close()
        self.thread.join()

    def url(self, mac: str, family: int = 1, variant: int = 0, nonce: int = NONCE) -> str:
        """Construct the same explicit query emitted by the production firmware."""
        port = self.server.server_address[1]
        return (
            f"http://127.0.0.1:{port}{SERVER.FIRMWARE_PATH}"
            f"?nonce={nonce:08X}&release={RELEASE}&family={family}"
            f"&variant={variant}&mac={mac}"
        )


class FleetUpdateServerTest(unittest.TestCase):
    def setUp(self) -> None:
        """Create a realistic image size so concurrency exercises file streaming."""
        self.temporary = tempfile.TemporaryDirectory()
        self.firmware = pathlib.Path(self.temporary.name) / "firmware.bin"
        block = bytes(range(256))
        identity = SERVER.FIRMWARE_IDENTITY.pack(
            SERVER.FIRMWARE_IDENTITY_MAGIC, 1, 1, 0, RELEASE, b"\0\0\0"
        )
        self.contents = identity + block * 5120  # 1.25 MiB, close to the current image.
        self.firmware.write_bytes(self.contents)

    def tearDown(self) -> None:
        self.temporary.cleanup()

    def test_serves_one_authorized_image_with_integrity_metadata(self) -> None:
        """An enrolled family and variant receives the exact bytes and MD5 expected by ESP32 Update."""
        mac = "001122334455"
        with RunningFleetServer(self.firmware, {mac: SERVER.FleetDevice(1, 0)}) as running:
            with urllib.request.urlopen(running.url(mac), timeout=5) as response:
                body = response.read()
                digest = response.headers["x-MD5"]

        self.assertEqual(body, self.contents)
        self.assertEqual(digest, hashlib.md5(self.contents).hexdigest())  # noqa: S324
        self.assertEqual(running.server.ledger.snapshot()[mac].bytes_sent, len(self.contents))

    def test_rejects_a_stale_wave_before_sending_firmware(self) -> None:
        """A request from another offer nonce cannot reuse a server left running after its wave."""
        mac = "001122334455"
        with RunningFleetServer(self.firmware, {mac: SERVER.FleetDevice(1, 0)}) as running:
            with self.assertRaises(urllib.error.HTTPError) as rejected:
                urllib.request.urlopen(running.url(mac, nonce=NONCE + 1), timeout=5)

        self.assertEqual(rejected.exception.code, 403)
        rejected.exception.close()
        self.assertEqual(running.server.ledger.snapshot(), {})

    def test_rejects_a_malformed_query_without_starting_a_transfer(self) -> None:
        """Malformed query syntax receives a bounded client error and never opens an image."""
        mac = "001122334455"
        with RunningFleetServer(self.firmware, {mac: SERVER.FleetDevice(1, 0)}) as running:
            port = running.server.server_address[1]
            with self.assertRaises(urllib.error.HTTPError) as rejected:
                urllib.request.urlopen(
                    f"http://127.0.0.1:{port}{SERVER.FIRMWARE_PATH}?broken",
                    timeout=5,
                )

        self.assertEqual(rejected.exception.code, 400)
        rejected.exception.close()
        self.assertEqual(running.server.ledger.snapshot(), {})

    def test_serves_fifty_manifest_devices_concurrently(self) -> None:
        """Fifty simultaneous pulls complete independently without sharing identity or response state."""
        macs = {f"02000000{index:04x}" for index in range(50)}
        devices = {mac: SERVER.FleetDevice(1, 0) for mac in macs}
        with RunningFleetServer(self.firmware, devices) as running:
            with concurrent.futures.ThreadPoolExecutor(max_workers=50) as workers:
                downloads = list(workers.map(
                    lambda mac: urllib.request.urlopen(running.url(mac), timeout=20).read(),
                    sorted(macs),
                ))

        self.assertTrue(all(download == self.contents for download in downloads))
        completed = running.server.ledger.snapshot()
        self.assertEqual(set(completed), macs)
        self.assertEqual(sum(result.bytes_sent for result in completed.values()), 50 * len(self.contents))


# AI: end


if __name__ == "__main__":
    unittest.main()
