#include <array>
#include <cstdint>
#include <iostream>
#include <stdexcept>
#include <string>
#include <utility>

#include "downbeat_tracker.h"

// AI: below section was generated by an AI

namespace {

void expect(bool condition, const std::string& message) {
  if (!condition)
    throw std::runtime_error(message);
}

void observeBar(DownbeatTracker& tracker, uint32_t firstOrdinal,
    uint8_t downbeatSlot, float wrongBeatSpike = 0.0f) {
  for (uint8_t beat = 0; beat < 4; beat++) {
    uint32_t ordinal = firstOrdinal + beat;
    uint8_t position = uint8_t((ordinal - downbeatSlot) & 3U);
    float kick = position == 0 ? 150.0f : (position == 2 ? 105.0f : 35.0f);
    float snare = position & 1U ? 125.0f : 25.0f;
    float novelty = position == 0 ? 90.0f : 45.0f;
    if (wrongBeatSpike > 0.0f && beat == 2) {
      kick += wrongBeatSpike;
      novelty += wrongBeatSpike;
    }
    tracker.observe(ordinal, kick, snare, novelty);
  }
}

void regular_four_four_finds_the_correct_rotation() {
  DownbeatTracker tracker;
  constexpr uint8_t downbeatSlot = 3;
  for (uint8_t bar = 0; bar < 10; bar++)
    observeBar(tracker, uint32_t(bar) * 4U, downbeatSlot);

  DownbeatEstimate estimate = tracker.estimate(40);
  expect(estimate.locked, "regular 4/4 pattern did not lock");
  expect(estimate.downbeatSlot == downbeatSlot, "tracker chose the wrong bar rotation");
  expect(estimate.beatInBar == 1, "current beat was numbered incorrectly");
}

void identical_kicks_do_not_invent_a_downbeat() {
  DownbeatTracker tracker;
  for (uint32_t ordinal = 0; ordinal < 64; ordinal++)
    tracker.observe(ordinal, 100.0f, 30.0f, 50.0f);

  expect(!tracker.estimate(64).locked,
      "indistinguishable beats produced a false downbeat lock");
}

void one_bad_accent_cannot_move_a_locked_bar() {
  DownbeatTracker tracker;
  constexpr uint8_t downbeatSlot = 1;
  for (uint8_t bar = 0; bar < 10; bar++)
    observeBar(tracker, uint32_t(bar) * 4U, downbeatSlot);
  expect(tracker.estimate(40).downbeatSlot == downbeatSlot, "fixture did not establish lock");

  observeBar(tracker, 40, downbeatSlot, 500.0f);
  DownbeatEstimate estimate = tracker.estimate(44);
  expect(estimate.locked, "single bad accent removed bar lock");
  expect(estimate.downbeatSlot == downbeatSlot, "single bad accent moved bar alignment");
}

void missed_beats_preserve_the_bar_rotation() {
  DownbeatTracker tracker;
  constexpr uint8_t downbeatSlot = 2;
  for (uint8_t bar = 0; bar < 10; bar++)
    observeBar(tracker, uint32_t(bar) * 4U, downbeatSlot);

  tracker.observe(45, 35.0f, 125.0f, 45.0f); // Ordinals 40-44 were not observed.
  DownbeatEstimate estimate = tracker.estimate(45);
  expect(estimate.locked, "short observation gap removed bar lock");
  expect(estimate.beatInBar == 3, "missed beats shifted bar numbering");
}

} // namespace

int main() {
  const std::array<std::pair<const char*, void (*)()>, 4> tests = {{
      {"regular 4/4 rotation", regular_four_four_finds_the_correct_rotation},
      {"ambiguous kicks remain unlocked", identical_kicks_do_not_invent_a_downbeat},
      {"one bad accent is rejected", one_bad_accent_cannot_move_a_locked_bar},
      {"missed beats preserve rotation", missed_beats_preserve_the_bar_rotation},
  }};

  for (const auto& test : tests) {
    try {
      test.second();
      std::cout << "PASS: " << test.first << '\n';
    } catch (const std::exception& error) {
      std::cerr << "FAIL: " << test.first << ": " << error.what() << '\n';
      return 1;
    }
  }
}

// AI: end
