#include <cstdint>
#include <iostream>
#include <stdexcept>

#include "effect_chance.h"

// AI: below section was generated by an AI
namespace {

void expect(bool condition, const char* message) {
  if (!condition)
    throw std::runtime_error(message);
}

// The shared chance boundary must retain the inclusive comparison used by
// regular Tubes effects so Beat overlays select poles with identical semantics.
void chance_matches_regular_effect_boundaries() {
  expect(effectChanceAccepts(255, 255), "all-poles chance rejected a pole");
  expect(effectChanceAccepts(128, 128), "half chance rejected its boundary roll");
  expect(!effectChanceAccepts(128, 129), "half chance accepted a roll above its boundary");
  expect(effectChanceAccepts(64, 64), "quarter chance rejected its boundary roll");
  expect(!effectChanceAccepts(64, 65), "quarter chance accepted a roll above its boundary");
  expect(effectChanceAccepts(0, 0), "zero chance changed the existing one-in-256 behavior");
  expect(!effectChanceAccepts(0, 1), "zero chance accepted a nonzero roll");
}

} // namespace

int main() {
  try {
    chance_matches_regular_effect_boundaries();
    std::cout << "PASS: chance matches regular effect boundaries\n";
  } catch (const std::exception& error) {
    std::cerr << "FAIL: " << error.what() << '\n';
    return 1;
  }
  return 0;
}
// AI: end
