#include <array>
#include <cstdint>
#include <iostream>
#include <stdexcept>
#include <string>
#include <utility>

#include "firmware_image_source.h"

// AI: below section was generated by an AI
namespace {

void expect(bool condition, const std::string& message) {
  if (!condition)
    throw std::runtime_error(message);
}

FirmwareTargetContract dig2GoTarget() {
  const FirmwareTargetContract staticTarget = firmwareStaticTargetFromCanonical(
      CANONICAL_TARGET_QUINLED_DIG2GO, TubeHardwareDig2Go);
  FirmwareTargetContract target;
  expect(firmwareReceiverTargetFromStatic(staticTarget, 0, target),
      "verified inactive slot did not construct receiver target");
  return target;
}

void static_target_is_receiver_incomplete() {
  const FirmwareTargetContract staticTarget = firmwareStaticTargetFromCanonical(
      CANONICAL_TARGET_QUINLED_DIG2GO, TubeHardwareDig2Go);
  expect(firmwareStaticTargetIsKnown(staticTarget), "static target projection was incomplete");
  expect(!firmwareTargetIsKnown(staticTarget), "static target claimed receiver runtime evidence");
  expect(firmwareInactiveSlotDestination(staticTarget).otaSlot == CANONICAL_MAX_OTA_SLOTS,
      "static target produced a receiver destination");

  FirmwareTargetContract receiver;
  expect(!firmwareReceiverTargetFromStatic(staticTarget, CANONICAL_MAX_OTA_SLOTS, receiver),
      "out-of-range inactive slot constructed receiver target");
  expect(!firmwareTargetIsKnown(receiver), "failed receiver construction left admissible state");
  expect(firmwareReceiverTargetFromStatic(staticTarget, 1, receiver),
      "verified inactive slot did not construct receiver target");
  expect(firmwareTargetIsKnown(receiver), "verified receiver target remained incomplete");
}

void exact_target_is_admitted() {
  const auto artifactTarget = firmwareStaticTargetFromCanonical(
      CANONICAL_TARGET_QUINLED_DIG2GO, TubeHardwareDig2Go);
  const auto receiverTarget = dig2GoTarget();
  expect(firmwareStaticTargetIsKnown(artifactTarget), "static artifact target was unknown");
  expect(!firmwareTargetIsKnown(artifactTarget), "artifact target claimed receiver evidence");
  expect(matchFirmwareArtifactTarget(artifactTarget, receiverTarget) == FirmwareTargetMatchExact,
      "identical targets did not match");
}

void unknown_target_fails_closed() {
  const auto artifactTarget = firmwareStaticTargetFromCanonical(
      CANONICAL_TARGET_QUINLED_DIG2GO, TubeHardwareDig2Go);
  FirmwareTargetContract receiver;
  receiver.targetId = CanonicalTargetQuinledDig2go;
  receiver.hardwareFamily = TubeHardwareDig2Go;
  receiver.chipFamily = FirmwareChipEsp32;
  expect(!firmwareTargetIsKnown(receiver), "partial target was treated as known");
  expect(matchFirmwareArtifactTarget(artifactTarget, receiver) == FirmwareTargetUnknown,
      "partial target did not fail closed");
}

void every_hardware_dimension_must_match() {
  const auto artifactTarget = firmwareStaticTargetFromCanonical(
      CANONICAL_TARGET_QUINLED_DIG2GO, TubeHardwareDig2Go);

  auto receiver = dig2GoTarget();
  receiver.hardwareFamily = TubeHardwareAthomC3;
  expect(matchFirmwareArtifactTarget(artifactTarget, receiver) == FirmwareTargetHardwareMismatch,
      "wrong board family was admitted");

  receiver = dig2GoTarget();
  receiver.chipFamily = FirmwareChipEsp32C3;
  expect(matchFirmwareArtifactTarget(artifactTarget, receiver) == FirmwareTargetChipMismatch,
      "wrong chip family was admitted");

  receiver = dig2GoTarget();
  receiver.flashMode = FirmwareFlashModeQio;
  expect(matchFirmwareArtifactTarget(artifactTarget, receiver) == FirmwareTargetFlashModeMismatch,
      "wrong flash mode was admitted");

  receiver = dig2GoTarget();
  receiver.flashSizeBytes *= 2;
  expect(matchFirmwareArtifactTarget(artifactTarget, receiver) == FirmwareTargetFlashSizeMismatch,
      "wrong flash size was admitted");

  receiver = dig2GoTarget();
  receiver.partitionTableSha256[31] ^= 0xff;
  expect(matchFirmwareArtifactTarget(artifactTarget, receiver) == FirmwareTargetPartitionMismatch,
      "wrong partition table was admitted");

  receiver = dig2GoTarget();
  receiver.otaSlots[1].sizeBytes -= 0x1000;
  expect(matchFirmwareArtifactTarget(artifactTarget, receiver) == FirmwareTargetOtaSlotMismatch,
      "wrong OTA slot was admitted");
}

void generated_targets_preserve_cross_target_rejection() {
  const FirmwareTargetContract dig2goStatic = firmwareStaticTargetFromCanonical(
      CANONICAL_TARGET_QUINLED_DIG2GO, TubeHardwareDig2Go);
  const FirmwareTargetContract s3Static = firmwareStaticTargetFromCanonical(
      CANONICAL_TARGET_WAVESHARE_S3_TUBES_REMOTE, TubeHardwareMatrixM1);
  FirmwareTargetContract dig2go;
  FirmwareTargetContract admittedS3;
  expect(firmwareReceiverTargetFromStatic(dig2goStatic, 0, dig2go),
      "Dig2Go receiver construction failed");
  expect(firmwareReceiverTargetFromStatic(s3Static, 1, admittedS3),
      "S3 receiver construction failed");
  expect(firmwareTargetIsKnown(dig2go), "generated Dig2Go target was incomplete");
  expect(firmwareTargetIsKnown(admittedS3), "generated S3 metadata target was incomplete");
  expect(matchFirmwareArtifactTarget(dig2go, admittedS3) == FirmwareTargetHardwareMismatch,
      "S3 admitted a Dig2Go artifact");
}

void athom_c3_uses_exact_compiled_target_and_artifact() {
  const FirmwareTargetContract c3Static = firmwareStaticTargetFromCanonical(
      CANONICAL_TARGET_ATHOM_C3_TUBES, TubeHardwareAthomC3);
  FirmwareTargetContract receiver;
  expect(c3Static.chipFamily == FirmwareChipEsp32C3, "Athom target lost C3 chip identity");
  expect(c3Static.flashMode == FirmwareFlashModeDio, "Athom target lost DIO flash mode");
  expect(c3Static.flashSizeBytes == 4194304U, "Athom target lost 4 MB flash size");
  expect(firmwareReceiverTargetFromStatic(c3Static, 1, receiver),
      "Athom receiver construction failed");
  const FirmwareImageArtifact artifact = firmwareArtifactFromCanonical(
      CANONICAL_ARTIFACT_ATHOM_C3_V14_OTA_APPLICATION, c3Static);
  expect(firmwareArtifactMatchesCanonical(artifact), "Athom OTA artifact was not canonical");
  expect(firmwareArtifactFitsInactiveSlot(receiver, firmwareInactiveSlotDestination(receiver),
      artifact.imageLengthBytes), "Athom OTA artifact exceeded the exact inactive slot");
  expect(matchFirmwareArtifactTarget(c3Static, receiver) == FirmwareTargetMatchExact,
      "Athom artifact target did not match exact receiver");
  expect(matchFirmwareArtifactTarget(firmwareStaticTargetFromCanonical(
      CANONICAL_TARGET_QUINLED_DIG2GO, TubeHardwareDig2Go), receiver)
      == FirmwareTargetHardwareMismatch, "Dig2Go artifact crossed into Athom C3");
}

void inactive_slot_is_explicit_and_bounded() {
  const FirmwareTargetContract staticTarget = firmwareStaticTargetFromCanonical(
      CANONICAL_TARGET_QUINLED_DIG2GO, TubeHardwareDig2Go);
  FirmwareTargetContract target;
  expect(firmwareReceiverTargetFromStatic(staticTarget, 0, target),
      "first inactive slot construction failed");
  expect(firmwareArtifactFitsInactiveSlot(target, firmwareInactiveSlotDestination(target), 0x1000),
      "declared inactive slot rejected bounded image");
  expect(firmwareReceiverTargetFromStatic(staticTarget, 1, target),
      "second inactive slot construction failed");
  expect(firmwareArtifactFitsInactiveSlot(target, firmwareInactiveSlotDestination(target), 0x1000),
      "second inactive slot rejected bounded image");
  expect(!firmwareReceiverTargetFromStatic(staticTarget, CANONICAL_MAX_OTA_SLOTS, target),
      "invalid inactive slot constructed receiver target");
  expect(!firmwareArtifactFitsInactiveSlot(target, firmwareInactiveSlotDestination(target), 0x1000),
      "missing inactive-slot evidence was admitted");
}

} // namespace

int main() {
  const std::array<std::pair<const char*, void (*)()>, 7> tests = {{
    {"static target is receiver incomplete", static_target_is_receiver_incomplete},
    {"exact target is admitted", exact_target_is_admitted},
    {"unknown target fails closed", unknown_target_fails_closed},
    {"every hardware dimension must match", every_hardware_dimension_must_match},
    {"generated targets preserve cross-target rejection", generated_targets_preserve_cross_target_rejection},
    {"Athom C3 exact target and artifact", athom_c3_uses_exact_compiled_target_and_artifact},
    {"inactive slot is explicit and bounded", inactive_slot_is_explicit_and_bounded},
  }};

  for (const auto& test : tests) {
    try {
      test.second();
      std::cout << "PASS: " << test.first << '\n';
    } catch (const std::exception& error) {
      std::cerr << "FAIL: " << test.first << ": " << error.what() << '\n';
      return 1;
    }
  }
  return 0;
}
// AI: end
