#include <array>
#include <cstdint>
#include <cstring>
#include <iostream>
#include <stdexcept>
#include <string>
#include <utility>

#include "firmware_update_session.h"

// AI: below section was generated by an AI
namespace {

void expect(bool condition, const std::string& message) {
  if (!condition)
    throw std::runtime_error(message);
}

FirmwareTargetContract exactTarget(uint8_t marker = 1) {
  FirmwareTargetContract target;
  target.targetId = CanonicalTargetQuinledDig2go;
  target.hardwareFamily = TubeHardwareDig2Go;
  target.chipFamily = FirmwareChipEsp32;
  target.flashMode = FirmwareFlashModeDio;
  target.flashSizeBytes = 4 * 1024 * 1024;
  target.otaSlotOffset = 0x210000;
  target.otaSlotSizeBytes = 0x1E0000;
  target.partitionTableSha256[0] = marker;
  return target;
}

FirmwareImageArtifact exactArtifact() {
  FirmwareImageArtifact artifact;
  artifact.target = exactTarget();
  artifact.releaseClass = CanonicalReleaseCurrent;
  artifact.imageLengthBytes = 1024;
  artifact.releaseHash = 0x12345678;
  artifact.imageSha256[0] = 0xAB;
  return artifact;
}

FirmwareUpdateHealthProof healthyProof() {
  const FirmwareImageArtifact artifact = exactArtifact();
  FirmwareUpdateHealthProof proof;
  proof.target = artifact.target;
  proof.releaseHash = artifact.releaseHash;
  std::memcpy(proof.imageSha256, artifact.imageSha256, sizeof(proof.imageSha256));
  proof.runtimeConfigurationPreserved = true;
  proof.meshRejoined = true;
  proof.stable = true;
  return proof;
}

constexpr uint8_t SENDER[6] = {1, 2, 3, 4, 5, 6};
constexpr uint8_t TARGET[6] = {7, 8, 9, 10, 11, 12};
constexpr uint8_t OTHER[6] = {13, 14, 15, 16, 17, 18};

void exact_target_completes_only_after_health_proof() {
  FirmwareUpdateSession session;
  const FirmwareImageArtifact artifact = exactArtifact();

  expect(session.select(SENDER, TARGET, artifact, exactTarget(), 100, 1000),
      "exact target was not selected");
  expect(session.state() == FirmwareUpdateTargetSelected, "selection state changed");
  expect(!session.forwardingEnabled(), "forwarding enabled during selection");
  expect(session.startTransfer(TARGET, 200), "selected target could not start transfer");
  expect(session.recordProgress(TARGET, 512, 300), "valid progress was rejected");
  expect(session.recordProgress(TARGET, 1024, 400), "complete progress was rejected");
  expect(session.verifyTransfer(TARGET, artifact.imageSha256, 500),
      "matching completed image was not verified");
  expect(session.state() == FirmwareUpdateAwaitingHealth, "health gate was skipped");
  expect(!session.complete(TARGET), "session completed before health proof");
  expect(session.proveHealthy(TARGET, healthyProof(), 600),
      "exact health proof was rejected");
  expect(session.complete(TARGET), "healthy target did not complete");
  expect(session.state() == FirmwareUpdateComplete, "completion state changed");
  expect(session.batonReady(), "completed healthy target did not release baton");
  expect(!session.forwardingEnabled(), "completion autonomously enabled forwarding");
}

void unknown_or_mismatched_identity_fails_before_selection() {
  FirmwareUpdateSession session;
  FirmwareImageArtifact artifact = exactArtifact();
  FirmwareTargetContract unknown;
  expect(!session.select(SENDER, TARGET, artifact, unknown, 0, 1000),
      "unknown receiver was selected");
  expect(session.state() == FirmwareUpdateIdle, "failed selection changed state");

  FirmwareTargetContract mismatch = exactTarget(2);
  expect(!session.select(SENDER, TARGET, artifact, mismatch, 0, 1000),
      "partition mismatch was selected");
  expect(session.state() == FirmwareUpdateIdle, "mismatch changed state");
}

void one_target_and_mac_continuity_are_enforced() {
  FirmwareUpdateSession session;
  const FirmwareImageArtifact artifact = exactArtifact();
  expect(session.select(SENDER, TARGET, artifact, exactTarget(), 0, 1000),
      "initial target was rejected");
  expect(!session.select(SENDER, OTHER, artifact, exactTarget(), 0, 1000),
      "second target replaced active target");
  expect(!session.startTransfer(OTHER, 1), "different MAC started transfer");
  expect(session.startTransfer(TARGET, 1), "selected MAC could not start transfer");
  expect(!session.recordProgress(OTHER, 10, 2), "different MAC advanced transfer");
  expect(session.recordProgress(TARGET, 10, 3), "valid progress was rejected");
  expect(!session.recordProgress(TARGET, 9, 4), "progress moved backwards");
}

void lease_expiry_fails_closed() {
  FirmwareUpdateSession session;
  const FirmwareImageArtifact artifact = exactArtifact();
  expect(session.select(SENDER, TARGET, artifact, exactTarget(), 100, 50),
      "target selection failed");
  expect(!session.startTransfer(TARGET, 150), "expired lease started transfer");
  expect(session.state() == FirmwareUpdateFailed, "expired lease did not fail session");
  expect(!session.batonReady(), "failed session released baton");
}

void wrong_hash_or_release_cannot_pass_gates() {
  FirmwareUpdateSession session;
  const FirmwareImageArtifact artifact = exactArtifact();
  uint8_t wrongHash[32] = {0};
  expect(session.select(SENDER, TARGET, artifact, exactTarget(), 0, 1000),
      "target selection failed");
  expect(session.startTransfer(TARGET, 1), "transfer did not start");
  expect(session.recordProgress(TARGET, artifact.imageLengthBytes, 2),
      "complete progress was rejected");
  expect(!session.verifyTransfer(TARGET, wrongHash, 3), "wrong image hash passed");
  expect(session.state() == FirmwareUpdateFailed, "hash failure did not fail session");

  session.reset();
  expect(session.select(SENDER, TARGET, artifact, exactTarget(), 0, 1000),
      "target reselection failed");
  expect(session.startTransfer(TARGET, 1), "second transfer did not start");
  expect(session.recordProgress(TARGET, artifact.imageLengthBytes, 2),
      "second progress failed");
  expect(session.verifyTransfer(TARGET, artifact.imageSha256, 3), "valid hash failed");
  FirmwareUpdateHealthProof wrongRelease = healthyProof();
  wrongRelease.releaseHash++;
  expect(!session.proveHealthy(TARGET, wrongRelease, 4),
      "wrong release passed health gate");
  expect(session.state() == FirmwareUpdateFailed, "health mismatch did not fail session");
}

} // namespace

int main() {
  const std::array<std::pair<const char*, void (*)()>, 5> tests = {{
    {"exact target completes only after health proof", exact_target_completes_only_after_health_proof},
    {"unknown or mismatched identity fails before selection", unknown_or_mismatched_identity_fails_before_selection},
    {"one target and MAC continuity are enforced", one_target_and_mac_continuity_are_enforced},
    {"lease expiry fails closed", lease_expiry_fails_closed},
    {"wrong hash or release cannot pass gates", wrong_hash_or_release_cannot_pass_gates},
  }};

  for (const auto& test : tests) {
    try {
      test.second();
      std::cout << "PASS: " << test.first << '\n';
    } catch (const std::exception& error) {
      std::cerr << "FAIL: " << test.first << ": " << error.what() << '\n';
      return 1;
    }
  }
  return 0;
}
// AI: end
