#include <array>
#include <cstdint>
#include <iostream>
#include <stdexcept>
#include <string>
#include <utility>

#include "rubber_band_beat_clock.h"

// AI: below section was generated by an AI

namespace {

constexpr uint16_t BPM_120 = 120U << 8;
constexpr uint16_t BPM_125 = 125U << 8;
constexpr uint32_t ONE_BEAT = 1U << 8;
constexpr uint32_t UPDATE_MICROS = 100000;

void expect(bool condition, const std::string& message) {
  if (!condition)
    throw std::runtime_error(message);
}

// A tempo-only command preserves phase immediately, changes the running tempo
// gradually, and reaches the requested rate after a short convergence interval.
void tempo_change_slews_without_repositioning() {
  RubberBandBeatClock clock;
  expect(clock.reset(BPM_120, 7U * ONE_BEAT), "initial clock was rejected");
  uint32_t frameBeforeChange = clock.frame();

  expect(clock.setTempoGoal(BPM_125), "valid tempo goal was rejected");

  expect(clock.frame() == frameBeforeChange, "tempo command repositioned the beat frame");
  expect(clock.runningBpm() == BPM_120, "tempo command changed the running rate immediately");
  clock.advance(UPDATE_MICROS);
  expect(clock.runningBpm() > BPM_120, "running tempo did not begin moving toward its goal");
  expect(clock.runningBpm() < BPM_125, "running tempo reached its goal in one update");

  for (uint8_t update = 1; update < 40; update++) {
    clock.advance(UPDATE_MICROS);
    expect(clock.phaseError() == 0, "tempo-only change created a phase correction");
  }
  expect(clock.runningBpm() < BPM_125, "tempo change completed in less than five seconds");

  for (uint8_t update = 40; update < 50; update++) {
    clock.advance(UPDATE_MICROS);
    expect(clock.phaseError() == 0, "tempo-only change created a phase correction");
  }
  expect(clock.runningBpm() == BPM_125,
      "tempo change did not complete after five seconds: "
      + std::to_string(clock.runningBpm()));
}

// A remote clock behind the local pole is approached by slowing forward motion;
// no synchronization update is allowed to decrement the local beat frame.
void backward_phase_goal_keeps_local_frame_monotonic() {
  RubberBandBeatClock clock;
  expect(clock.reset(BPM_120, 8U * ONE_BEAT), "initial clock was rejected");
  expect(clock.setGoal(BPM_120, 4U * ONE_BEAT), "backward phase goal was rejected");
  uint32_t previousFrame = clock.frame();
  int32_t initialError = clock.phaseError();

  for (uint16_t update = 0; update < 400; update++) {
    clock.advance(UPDATE_MICROS);
    expect(clock.frame() >= previousFrame, "phase correction moved the clock backward");
    previousFrame = clock.frame();
  }

  expect(clock.phaseError() > initialError, "backward phase error did not shrink");
  expect(clock.phaseError() == 0,
      "backward phase correction did not converge exactly: "
      + std::to_string(clock.phaseError()) + " at running BPM Q8 "
      + std::to_string(clock.runningBpm()));
}

// A distant forward goal does not jump the local frame when received; bounded
// faster motion reduces the gap over time while every individual update stays small.
void forward_phase_goal_closes_without_a_discontinuity() {
  RubberBandBeatClock clock;
  expect(clock.reset(BPM_120, 2U * ONE_BEAT), "initial clock was rejected");
  uint32_t frameBeforeGoal = clock.frame();
  expect(clock.setGoal(BPM_120, 10U * ONE_BEAT), "forward phase goal was rejected");
  int32_t initialError = clock.phaseError();

  expect(clock.frame() == frameBeforeGoal, "forward phase goal jumped the beat frame");
  uint32_t previousFrame = clock.frame();
  for (uint16_t update = 0; update < 600; update++) {
    clock.advance(UPDATE_MICROS);
    uint32_t step = clock.frame() - previousFrame;
    expect(step <= ONE_BEAT / 2, "one correction update produced a visible frame jump");
    previousFrame = clock.frame();
  }

  expect(clock.phaseError() < initialError, "forward phase error did not shrink");
  expect(clock.phaseError() == 0,
      "forward phase correction did not converge exactly: "
      + std::to_string(clock.phaseError()));
}

// Whole-phrase counter differences are invisible to renderers and must be removed
// immediately so phrase-keyed channel operations refer to the same boundary.
void whole_phrase_offsets_rebase_without_changing_visible_phase() {
  RubberBandBeatClock clock;
  constexpr uint32_t phrase = 16U * ONE_BEAT;
  constexpr uint32_t visiblePhase = 5U * ONE_BEAT + 73U;
  expect(clock.reset(BPM_120, 207U * phrase + visiblePhase), "initial clock was rejected");

  expect(clock.setGoal(BPM_120, 82U * phrase + visiblePhase), "remote clock was rejected");
  expect(clock.frame() == 82U * phrase + visiblePhase, "whole-phrase offset was not rebased");
  expect((clock.frame() % phrase) == visiblePhase, "visible beat phase changed during rebase");
  expect(clock.phaseError() == 0, "exact phrase rebase left a phase error");
}

} // namespace

int main() {
  const std::array<std::pair<const char*, void (*)()>, 4> tests = {{
      {"tempo change slews without repositioning", tempo_change_slews_without_repositioning},
      {"backward phase goal keeps local frame monotonic", backward_phase_goal_keeps_local_frame_monotonic},
      {"forward phase goal closes without a discontinuity", forward_phase_goal_closes_without_a_discontinuity},
      {"whole phrase offsets rebase without changing visible phase", whole_phrase_offsets_rebase_without_changing_visible_phase},
  }};

  for (const auto& test : tests) {
    try {
      test.second();
      std::cout << "PASS: " << test.first << '\n';
    } catch (const std::exception& error) {
      std::cerr << "FAIL: " << test.first << ": " << error.what() << '\n';
      return 1;
    }
  }
}

// AI: end
