#include <array>
#include <iostream>
#include <stdexcept>
#include <string>

#include "s3_peer_catalog.h"

// AI: below section was generated by an AI
namespace {
void expect(bool condition, const std::string& message) {
  if (!condition) throw std::runtime_error(message);
}

void fresh_external_rows_are_sorted_by_receiver_rssi() {
  S3PeerCatalog catalog;
  catalog.observe(0x101, 0x201, -72, 1000);
  catalog.observe(0x102, 0x202, -41, 1100);
  catalog.observe(0x103, 0x203, -55, 1200);
  std::array<S3PeerEvidence, 8> rows = {};
  const size_t count = catalog.copyFresh(2000, 0x999, rows.data(), rows.size());
  expect(count == 3, "fresh external count drifted");
  expect(rows[0].remoteId == 0x102 && rows[1].remoteId == 0x103
      && rows[2].remoteId == 0x101, "rows were not strongest-RSSI first");
  expect(rows[0].uplinkId == 0x202, "exact uplink evidence was lost");
}

void local_and_stale_rows_are_excluded_without_distance_inference() {
  S3PeerCatalog catalog;
  catalog.observe(0x111, 0, -20, 1000);
  catalog.observe(0x222, 0x333, -60, 1000);
  std::array<S3PeerEvidence, 8> rows = {};
  expect(catalog.copyFresh(61000, 0x111, rows.data(), rows.size()) == 1,
      "fresh external row was not retained at the boundary");
  expect(catalog.copyFresh(61001, 0x111, rows.data(), rows.size()) == 0,
      "stale or local row remained counted");
}

void updates_are_in_place_and_output_is_bounded() {
  S3PeerCatalog catalog;
  for (uint16_t id = 1; id <= 20; id++) catalog.observe(id, id + 1, -int8_t(id), id);
  catalog.observe(5, 0x444, -1, 5000);
  std::array<S3PeerEvidence, 4> rows = {};
  const size_t count = catalog.copyFresh(5001, 0x999, rows.data(), rows.size());
  expect(count == rows.size(), "bounded result count exceeded display rows");
  expect(rows[0].remoteId == 5 && rows[0].uplinkId == 0x444,
      "updated peer was duplicated or lost");
}
} // namespace

int main() {
  try {
    fresh_external_rows_are_sorted_by_receiver_rssi();
    local_and_stale_rows_are_excluded_without_distance_inference();
    updates_are_in_place_and_output_is_bounded();
    std::cout << "S3 peer catalog tests passed\n";
    return 0;
  } catch (const std::exception& error) {
    std::cerr << error.what() << '\n';
    return 1;
  }
}
// AI: end
