#include <array>
#include <cstdint>
#include <iostream>
#include <stdexcept>
#include <string>
#include <utility>

#include "legacy_projection.h"
#include "v3_authority.h"
#include "v3_protocol.h"
#include "v3_runtime.h"
#include "v3_channels.h"

// AI: below section was generated by an AI

namespace {

void expect(bool condition, const std::string& message) {
  if (!condition)
    throw std::runtime_error(message);
}

V3TopicEnvelope envelope(
    DeviceId authorityId,
    uint32_t session,
    uint16_t sequence,
    V3MessageKind kind,
    uint8_t bodyLength = 0
) {
  V3TopicEnvelope result;
  result.authorityId = authorityId;
  result.authoritySession = session;
  result.sequence = sequence;
  result.messageKind = kind;
  result.bodyLength = bodyLength;
  result.leaseDeciseconds = 40;
  return result;
}

NodeMessage legacyMessage(DeviceId senderId) {
  NodeMessage message;
  message.header.id = senderId;
  message.header.version = TUBES_PROTOCOL_V2;
  message.recipients = RECIPIENTS_ALL;
  message.command = 0x20;
  return message;
}

// A valid payload proves the fixed envelope/body split, while impossible body lengths
// and command lengths are rejected before application code can inspect the body.
void wire_validation_rejects_malformed_lengths() {
  V3TopicPayload payload;
  V3BeatPayload beat;
  payload.envelope = envelope(100, 0x12345678, 1, V3State);
  expect(writeV3Body(payload, &beat, sizeof(beat)), "valid Beat body was not written");
  expect(isValidV3TopicPayload(V3TopicBeat, payload), "valid Beat payload was rejected");

  payload.envelope.bodyLength = TUBES_V3_BODY_SIZE + 1;
  expect(!isValidV3TopicPayload(V3TopicBeat, payload), "oversized body length was accepted");

  V3TopicPayload controlPayload;
  V3ControlPayload control;
  control.command = 0x10;
  control.commandLength = sizeof(control.commandData) + 1;
  controlPayload.envelope = envelope(100, 0x12345678, 2, V3State, 2);
  memcpy(controlPayload.body, &control, 2);
  expect(!isValidV3TopicPayload(V3TopicControl, controlPayload), "oversized control command was accepted");

  V3TopicPayload presenceClaim;
  presenceClaim.envelope = envelope(100, 0x12345678, 3, V3Claim);
  expect(!isValidV3TopicPayload(V3TopicPresence, presenceClaim), "Presence authority claim was accepted");
}

// Topic claims establish independent authority sessions, and a stale state from one
// topic cannot replace or refresh another topic's authority.
void topic_authorities_remain_independent() {
  V3AuthorityBook authorities;
  V3TopicEnvelope beatClaim = envelope(100, 0x11111111, 1, V3Claim);
  V3TopicEnvelope paletteClaim = envelope(200, 0x22222222, 1, V3Claim);
  paletteClaim.leaseDeciseconds = 600;

  expect(authorities.accept(V3TopicBeat, beatClaim, 1000), "Beat claim was rejected");
  expect(authorities.accept(V3TopicPalette, paletteClaim, 1000), "Palette claim was rejected");

  V3TopicEnvelope beatState = envelope(100, 0x11111111, 2, V3State, sizeof(V3BeatPayload));
  expect(authorities.accept(V3TopicBeat, beatState, 1100), "active Beat authority state was rejected");
  expect(!authorities.accept(V3TopicBeat, beatState, 1200), "duplicate Beat state refreshed its lease");
  expect(authorities.get(V3TopicBeat).authorityId == 100, "Beat authority changed unexpectedly");
  expect(authorities.get(V3TopicPalette).authorityId == 200, "Palette authority changed unexpectedly");

  authorities.expire(5200);
  expect(!authorities.get(V3TopicBeat).active, "expired Beat authority remained active");
  expect(authorities.get(V3TopicPalette).active, "independent Palette authority expired with Beat");
}

// A gen1 Control master marks its gen0 projection, and corruption cannot make an
// arbitrary legacy packet look like a projection that gen1 receivers should ignore.
void projection_marker_distinguishes_master_output() {
  NodeMessage projected = legacyMessage(makeDeviceId(CHANNEL_PROTOCOL_GENERATION, 0x300));
  V3ProjectionTrailer trailer;
  trailer.controlId = projected.header.id;
  trailer.controlSession = 7;
  writeV3ProjectionTrailer(projected, trailer);

  V3ProjectionTrailer parsed;
  expect(readV3ProjectionTrailer(projected, parsed), "generated projection marker did not validate");
  expect(parsed.controlId == projected.header.id, "projection marker changed the Control ID");

  projected.data[V3_PROJECTION_TRAILER_OFFSET + 5] ^= 0x40;
  expect(!readV3ProjectionTrailer(projected, parsed), "corrupt projection marker was accepted");
  expect(!readV3ProjectionTrailer(legacyMessage(0x300), parsed), "unmarked gen0 packet looked projected");
}

// The generation nibble makes every gen1 Control candidate outrank every deployed
// gen0 ID, which removes the need to install legacy state in upgraded receivers.
void gen1_device_ids_always_outrank_gen0() {
  DeviceId lowestGen1 = makeDeviceId(CHANNEL_PROTOCOL_GENERATION, 1);
  DeviceId highestGen0 = makeDeviceId(LEGACY_PROTOCOL_GENERATION, PROTOCOL_LOCAL_VALUE_MASK);
  expect(lowestGen1 > highestGen0, "gen1 Device ID did not outrank the highest gen0 ID");
}

// A publisher proves ownership with a claim before emitting state, and the receiver
// accepts the ordered pair while rejecting the same state a second time.
void runtime_claims_before_publishing_state() {
  V3ProtocolRuntime publisher;
  publisher.setup(300, 0x12345678);
  V3TopicPayload claim;
  expect(publisher.prepareClaim(V3TopicBeat, 1000, claim), "publisher did not create its initial claim");

  V3BeatPayload beat;
  beat.bpm = 120U << 8;
  V3TopicPayload state;
  expect(publisher.prepareMessage(
      V3TopicBeat,
      V3State,
      &beat,
      sizeof(beat),
      40,
      1000,
      state), "publisher did not create authority-owned state");

  V3ProtocolRuntime receiver;
  receiver.setup(200, 0x87654321);
  expect(receiver.acceptTopic(V3TopicBeat, claim, 1000), "receiver rejected the authority claim");
  expect(receiver.acceptTopic(V3TopicBeat, state, 1001), "receiver rejected ordered authority state");
  expect(!receiver.acceptTopic(V3TopicBeat, state, 1002), "receiver accepted duplicate authority state");
}

// A compact gradient expands to stable endpoint colors, while unsorted stops are
// rejected instead of producing a partially defined runtime palette.
void gradient_palette_expands_atomically() {
  V3GradientPaletteDefinition gradient;
  gradient.count = 2;
  gradient.stops[0] = {0, 255, 0, 0};
  gradient.stops[1] = {255, 0, 0, 255};
  V3Palette16Definition palette;

  expect(expandV3Gradient(gradient, palette), "valid two-stop gradient was rejected");
  expect(palette.rgb[0][0] == 255 && palette.rgb[0][2] == 0, "gradient start color changed");
  expect(palette.rgb[15][0] == 0 && palette.rgb[15][2] == 255, "gradient end color changed");

  gradient.stops[1].position = 0;
  expect(!expandV3Gradient(gradient, palette), "non-increasing gradient stops were accepted");
}

// WLED uses repeated source positions for hard boundaries. The channel expansion
// must preserve both sides of that boundary instead of rejecting the palette.
void palette_expansion_matches_wled_hard_stops() {
  PaletteGradientDefinition gradient;
  gradient.count = 4;
  gradient.stops[0] = {0, 0, 0, 0};
  gradient.stops[1] = {96, 0, 0, 0};
  gradient.stops[2] = {96, 255, 64, 0};
  gradient.stops[3] = {255, 255, 64, 0};
  PaletteGradient16 expanded;
  expect(expandPaletteGradient(gradient, expanded), "WLED hard stop was rejected");
  expect(expanded.rgb[7][0] == 0, "hard stop lost its dark side");
  expect(expanded.rgb[8][0] == 255, "hard stop lost its bright side");
}

// FastLED accumulates gradients in 8.8 fixed point. Matching that rounding keeps
// generated definitions byte-identical to palettes created locally by WLED.
void palette_expansion_matches_wled_fixed_point_rounding() {
  PaletteGradientDefinition gradient;
  gradient.count = 2;
  gradient.stops[0] = {0, 100, 0, 0};
  gradient.stops[1] = {255, 0, 100, 0};
  PaletteGradient16 expanded;
  expect(expandPaletteGradient(gradient, expanded), "valid gradient was rejected");
  expect(expanded.rgb[3][0] == 80, "descending fixed-point component was rounded differently");
  expect(expanded.rgb[3][1] == 19, "ascending fixed-point component was rounded differently");
}

// Gen1 carries all sixteen RGB entries losslessly, while the separate schedule
// retains the built-in fallback IDs used by the gen0 projection.
void palette_channel_carries_full_definition_and_fallback() {
  PaletteGradient16 definition;
  for (uint8_t index = 0; index < 16; index++) {
    definition.rgb[index][0] = index * 13;
    definition.rgb[index][1] = 255 - index * 11;
    definition.rgb[index][2] = index * 7;
  }
  TubesChannelPayload definitionPayload;
  definitionPayload.envelope.messageKind = ChannelRequest;
  definitionPayload.envelope.channelId = 0x1FFE;
  definitionPayload.envelope.sourceControlId = 0x1123;
  definitionPayload.envelope.sourceSession = 7;
  definitionPayload.envelope.sequence = 40;
  expect(writeChannelBody(definitionPayload, &definition, sizeof(definition)),
      "Palette16 definition did not fit in one channel packet");
  expect(isValidTubesChannelPayload(PaletteChannel, definitionPayload),
      "Palette16 definition packet was rejected");
  ChannelWinnerTable rootWinners;
  expect(rootWinners.acceptRequest(PaletteChannel, definitionPayload.envelope, 1000),
      "Palette16 definition bypassed the normal upward authority path");
  PaletteGradient16 decoded;
  expect(readChannelBody(definitionPayload, decoded), "Palette16 definition did not decode");
  expect(memcmp(&definition, &decoded, sizeof(definition)) == 0,
      "Palette16 definition changed on the wire");

  PaletteChannelSchedule schedule;
  schedule.state.current = {80, 71};
  schedule.state.next = {84, 98};
  schedule.currentDefinitionSequence = 40;
  schedule.nextDefinitionSequence = 41;
  TubesChannelPayload schedulePayload;
  schedulePayload.envelope = definitionPayload.envelope;
  schedulePayload.envelope.messageKind = ChannelRequest;
  schedulePayload.envelope.sequence = 42;
  expect(writeChannelBody(schedulePayload, &schedule, sizeof(schedule)),
      "Palette schedule did not fit in one channel packet");
  expect(isValidTubesChannelPayload(PaletteChannel, schedulePayload),
      "Palette schedule packet was rejected");
  expect(rootWinners.acceptRequest(PaletteChannel, schedulePayload.envelope, 1001),
      "Palette schedule bypassed the normal upward authority path");
  expect(schedule.state.current.paletteId == 71 && schedule.state.next.paletteId == 98,
      "Palette schedule lost its exact built-in fallback IDs");

  TubesChannelPayload legacyPayload;
  legacyPayload.envelope = definitionPayload.envelope;
  legacyPayload.envelope.sequence = 43;
  expect(writeChannelBody(legacyPayload, &schedule.state, sizeof(schedule.state)),
      "ID-based Palette compatibility state did not fit in one channel packet");
  expect(isValidTubesChannelPayload(PaletteChannel, legacyPayload),
      "ID-based Palette compatibility state was rejected");
  PaletteChannelState legacyState;
  expect(readChannelBody(legacyPayload, legacyState),
      "ID-based Palette compatibility state did not decode");
  expect(legacyState.current.paletteId == 71 && legacyState.next.paletteId == 98,
      "Palette compatibility state lost the built-in fallback IDs");
}

// A generation-1 Palette snapshot carries both complete palettes and their timing
// metadata in one ESP-NOW packet, and malformed lengths fail before queue admission.
void variable_palette_snapshot_is_atomic() {
  TubesChannelMessageV2 message;
  message.header.id = 0x1FF0;
  message.header.uplinkId = 0;
  message.header.version = TUBES_PROTOCOL_V3;
  message.recipients = RECIPIENTS_ALL;
  message.command = PaletteChannel;
  message.envelope.messageKind = ChannelDeclaration;
  message.envelope.channelId = 0x1FF0;
  message.envelope.sourceControlId = 0x1FF0;
  message.envelope.sourceSession = 0x12345678;
  message.envelope.sequence = 9;

  PaletteChannelSnapshot snapshot;
  snapshot.state.current = {80, 71};
  snapshot.state.next = {84, 98};
  snapshot.transitionMs = 1200;
  for (uint8_t index = 0; index < 16; index++) {
    snapshot.currentDefinition.rgb[index][0] = index * 13;
    snapshot.currentDefinition.rgb[index][1] = 255 - index * 11;
    snapshot.currentDefinition.rgb[index][2] = index * 7;
    snapshot.nextDefinition.rgb[index][0] = 255 - index * 9;
    snapshot.nextDefinition.rgb[index][1] = index * 5;
    snapshot.nextDefinition.rgb[index][2] = index * 15;
  }
  expect(writeChannelMessageV2Body(message, snapshot), "Palette snapshot did not fit");
  size_t wireLength = channelMessageV2WireSize(message.envelope.bodyLength);
  expect(wireLength < TUBES_ESPNOW_MAX_MESSAGE_SIZE, "Palette snapshot exceeded ESP-NOW");
  expect(isValidChannelMessageV2Prefix(reinterpret_cast<const uint8_t*>(&message), wireLength),
      "valid variable Palette snapshot failed ingress validation");

  PaletteChannelSnapshot decoded;
  expect(readChannelMessageV2Body(message, decoded), "Palette snapshot did not decode");
  expect(memcmp(&snapshot, &decoded, sizeof(snapshot)) == 0,
      "Palette current/next snapshot changed on the wire");

  expect(!isValidChannelMessageV2Prefix(
      reinterpret_cast<const uint8_t*>(&message), wireLength - 1),
      "truncated variable Palette snapshot passed ingress validation");
  message.envelope.magic ^= 1;
  expect(!isValidChannelMessageV2Prefix(reinterpret_cast<const uint8_t*>(&message), wireLength),
      "wrong variable-channel magic passed ingress validation");
}

// A raw Palette snapshot preserves every ordered source stop, including duplicate
// positions, while its distinct body length selects the new decoder at ingress.
void raw_palette_snapshot_preserves_source_stops() {
  TubesChannelMessageV2 message;
  message.header.id = 0x1FF0;
  message.header.version = TUBES_PROTOCOL_V3;
  message.recipients = RECIPIENTS_ALL;
  message.command = PaletteChannel;
  message.envelope.messageKind = ChannelDeclaration;
  message.envelope.channelId = 0x1FF0;
  message.envelope.sourceControlId = 0x1FF0;
  message.envelope.sourceSession = 0x12345678;
  message.envelope.sequence = 10;

  constexpr uint8_t positions[PALETTE_RAW_MAX_STOPS] = {
      0, 15, 30, 45, 60, 60, 90, 105, 120,
      135, 150, 165, 180, 195, 210, 225, 240, 255};
  PaletteRawChannelSnapshot snapshot;
  snapshot.state.current = {80, 71};
  snapshot.state.next = {84, PALETTE_PREDEFINED_ID_NONE};
  snapshot.transitionMs = 1200;
  snapshot.currentDefinition.count = PALETTE_RAW_MAX_STOPS;
  snapshot.nextDefinition.count = PALETTE_RAW_MAX_STOPS;
  for (uint8_t index = 0; index < PALETTE_RAW_MAX_STOPS; index++) {
    snapshot.currentDefinition.stops[index] = {
        positions[index], uint8_t(index * 13), uint8_t(255 - index * 11), uint8_t(index * 7)};
    snapshot.nextDefinition.stops[index] = {
        positions[index], uint8_t(255 - index * 9), uint8_t(index * 5), uint8_t(index * 15)};
  }

  expect(isValidPaletteRawDefinition(snapshot.currentDefinition),
      "valid raw Palette source stops were rejected");
  expect(writeChannelMessageV2Body(message, snapshot), "raw Palette snapshot did not fit");
  size_t wireLength = channelMessageV2WireSize(message.envelope.bodyLength);
  expect(message.envelope.bodyLength == sizeof(PaletteRawChannelSnapshot),
      "raw Palette body length did not select the new decoder");
  expect(wireLength < TUBES_ESPNOW_MAX_MESSAGE_SIZE,
      "raw current/next Palette snapshot exceeded ESP-NOW");
  expect(isValidChannelMessageV2Prefix(reinterpret_cast<const uint8_t*>(&message), wireLength),
      "valid raw Palette snapshot failed ingress validation");

  PaletteRawChannelSnapshot decoded;
  expect(readChannelMessageV2Body(message, decoded), "raw Palette snapshot did not decode");
  expect(memcmp(&snapshot, &decoded, sizeof(snapshot)) == 0,
      "raw Palette source stops changed on the wire");
  expect(decoded.currentDefinition.stops[4].position
          == decoded.currentDefinition.stops[5].position,
      "raw Palette hard stop lost its duplicate position");
  expect(decoded.state.current.paletteId == 71
          && decoded.state.next.paletteId == PALETTE_PREDEFINED_ID_NONE,
      "raw Palette predefined identity changed on the wire");

  decoded.currentDefinition.count = PALETTE_RAW_MAX_STOPS + 1;
  expect(!isValidPaletteRawDefinition(decoded.currentDefinition),
      "oversized raw Palette stop count was accepted");
  decoded.currentDefinition = snapshot.currentDefinition;
  decoded.currentDefinition.stops[7].position = 255;
  expect(!isValidPaletteRawDefinition(decoded.currentDefinition),
      "early raw Palette terminator was accepted");
}

// A modern Pattern snapshot carries exact WLED/Tubes render programs while its
// embedded legacy state remains a complete fallback for older receivers.
void variable_pattern_snapshot_preserves_program_and_fallback() {
  TubesChannelMessageV2 message;
  message.header.id = 0x1FF0;
  message.header.version = TUBES_PROTOCOL_V3;
  message.recipients = RECIPIENTS_ALL;
  message.command = PatternChannel;
  message.envelope.messageKind = ChannelDeclaration;
  message.envelope.channelId = 0x1FF0;
  message.envelope.sourceControlId = 0x1FF0;
  message.envelope.sourceSession = 0x12345678;
  message.envelope.sequence = 10;

  PatternChannelSnapshot snapshot;
  snapshot.state.current = {80, 61, 0, 78, 0, 0, 0, 0};
  snapshot.state.next = {UINT16_MAX, 61, 0, 84, 1, 2, 4, 40};
  snapshot.transitionMs = 8000;
  snapshot.currentProgram = {
      80, 0, PatternRendererWled, 61, 0, 214, 115, 170, 96, 120, 2, 7, 6};
  snapshot.currentProgram.paletteBlend = 3;
  snapshot.nextProgram = snapshot.currentProgram;
  snapshot.nextProgram.effectivePhrase = UINT16_MAX;
  snapshot.nextProgram.paletteBlend = 2;

  expect(writeChannelMessageV2Body(message, snapshot), "Pattern snapshot did not fit");
  expect(message.envelope.bodyLength == sizeof(PatternChannelSnapshot),
      "current Pattern snapshot did not select the version-2 body length");
  size_t wireLength = channelMessageV2WireSize(message.envelope.bodyLength);
  expect(isValidChannelMessageV2Prefix(reinterpret_cast<const uint8_t*>(&message), wireLength),
      "valid variable Pattern snapshot failed ingress validation");
  PatternChannelSnapshot decoded;
  expect(readChannelMessageV2Body(message, decoded), "Pattern snapshot did not decode");
  expect(memcmp(&snapshot, &decoded, sizeof(snapshot)) == 0,
      "Pattern program changed on the wire");
  expect(decoded.state.current.patternId == 61
          && decoded.currentProgram.fallbackPatternId == 61,
      "Pattern snapshot lost its exact legacy fallback");
  expect(decoded.currentProgram.renderId == 214,
      "Pattern snapshot lost the raw WLED effect");
  expect(decoded.currentProgram.paletteBlend == 3
          && decoded.nextProgram.paletteBlend == 2,
      "Pattern snapshot lost the master's palette-blend modes");

  PatternChannelSnapshotV1 version1;
  version1.state = snapshot.state;
  version1.transitionMs = snapshot.transitionMs;
  version1.currentProgram = {
      80, 0, PatternRendererWled, 61, 0, 214, 115, 170, 96, 120, 2, 7, 6};
  version1.nextProgram = version1.currentProgram;
  version1.nextProgram.effectivePhrase = UINT16_MAX;
  expect(writeChannelMessageV2Body(message, version1),
      "deployed version-1 Pattern snapshot was no longer accepted");
  expect(message.envelope.bodyLength == sizeof(PatternChannelSnapshotV1),
      "version-1 Pattern snapshot did not retain its distinct wire length");
  expect(isValidChannelMessageV2Prefix(
      reinterpret_cast<const uint8_t*>(&message),
      channelMessageV2WireSize(message.envelope.bodyLength)),
      "version-1 Pattern snapshot failed compatibility validation");

  PatternChannelState legacy = snapshot.state;
  expect(writeChannelMessageV2Body(message, legacy),
      "legacy Pattern snapshot was no longer accepted");
  expect(isValidChannelMessageV2Prefix(
      reinterpret_cast<const uint8_t*>(&message),
      channelMessageV2WireSize(message.envelope.bodyLength)),
      "legacy Pattern snapshot failed compatibility validation");
}

// The Beat owner chooses participation policy with the exact overlay program.
// Carrying both values prevents receivers with different local tables from diverging.
void beat_snapshot_carries_authoritative_chance() {
  TubesChannelMessageV2 message;
  message.header.id = 0x1FF0;
  message.header.version = TUBES_PROTOCOL_V3;
  message.recipients = RECIPIENTS_ALL;
  message.command = BeatChannel;
  message.envelope.messageKind = ChannelDeclaration;
  message.envelope.channelId = 0x1FF0;
  message.envelope.sourceControlId = 0x1FF0;
  message.envelope.sourceSession = 0x12345678;
  message.envelope.sequence = 11;

  BeatChannelSnapshot snapshot;
  snapshot.state.bpm = 128U << 8;
  snapshot.state.beatFrame = 80U << TUBES_BEAT_FRAME_PHRASE_SHIFT;
  snapshot.soundProgram.current = {
      80, SoundProgramEnabled, 188, 71, 115, 170, 96, 120, 2, 6, 10, 210};
  snapshot.soundProgram.next = snapshot.soundProgram.current;
  snapshot.soundProgram.next.effectivePhrase = 84;
  snapshot.soundProgram.currentChance = 64;
  snapshot.soundProgram.nextChance = 128;

  expect(writeChannelMessageV2Body(message, snapshot), "Beat snapshot did not fit");
  expect(channelMessageV2WireSize(message.envelope.bodyLength) < TUBES_ESPNOW_MAX_MESSAGE_SIZE,
      "Beat snapshot exceeded ESP-NOW");
  BeatChannelSnapshot decoded;
  expect(readChannelMessageV2Body(message, decoded), "Beat snapshot did not decode");
  expect(decoded.soundProgram.version == BEAT_SOUND_PROGRAM_VERSION_2,
      "Beat snapshot used the obsolete sound-program version");
  expect(decoded.soundProgram.currentChance == 64
          && decoded.soundProgram.nextChance == 128,
      "Beat owner participation chance changed on the wire");
  expect(memcmp(&snapshot.soundProgram.current, &decoded.soundProgram.current,
          sizeof(SoundProgramEntry)) == 0,
      "Beat overlay program changed on the wire");
}

// A complete snapshot can arrive after its advertised next boundary. Receivers
// must promote next immediately instead of flashing the obsolete current entry.
void delayed_pattern_snapshot_promotes_next() {
  expect(!tubesPatternPhraseReached(62, 63),
      "future Pattern phrase was treated as due");
  expect(tubesPatternPhraseReached(63, 63),
      "Pattern phrase was not due at its boundary");
  expect(tubesPatternPhraseReached(64, 63),
      "late Pattern snapshot did not promote next");
  expect(!tubesPatternPhraseReached(64, UINT16_MAX),
      "held Pattern schedule was treated as due");
  expect(tubesPatternPhraseReached(0, UINT16_MAX - 1),
      "Pattern phrase wrap was not handled");
}

// Once a complete snapshot arrives, its same-source compatibility packet must
// remain recognizable so a modern receiver can relay it without applying it.
void modern_source_recognizes_both_channel_envelopes() {
  ChannelModernSource source;
  source.valid = true;
  source.channelId = 0x1FFF;
  source.controlId = 0x1FF0;
  source.session = 0x12345678;

  TubesChannelEnvelope legacy;
  legacy.channelId = source.channelId;
  legacy.sourceControlId = source.controlId;
  legacy.sourceSession = source.session;
  expect(source.matches(legacy), "same-source v1 fallback was not recognized");

  TubesChannelEnvelopeV2 modern;
  modern.channelId = source.channelId;
  modern.sourceControlId = source.controlId;
  modern.sourceSession = source.session;
  expect(source.matches(modern), "same-source v2 snapshot was not recognized");

  legacy.sourceSession++;
  expect(!source.matches(legacy), "different-session fallback matched modern source");
}

// User-triggered visual changes move to the next phrase without collapsing the
// relative timing of later changes or turning the unscheduled sentinel into work.
void channel_operations_schedule_on_phrase_boundaries() {
  uint32_t middleOfPhrase = (41U << TUBES_BEAT_FRAME_PHRASE_SHIFT) | 0x0555;
  expect(nextTubesPhraseBoundary(middleOfPhrase) == 42,
      "mid-phrase operation did not target the next phrase");
  expect(shiftScheduledPhrase(45, 45, 42) == 42,
      "earliest scheduled operation did not move to the boundary");
  expect(shiftScheduledPhrase(49, 45, 42) == 46,
      "later operation lost its relative phrase offset");
  expect(shiftScheduledPhrase(UINT16_MAX, 45, 42) == UINT16_MAX,
      "unscheduled operation became scheduled");
  expect(nextTubesPhraseBoundary(UINT32_MAX) == 0,
      "phrase boundary did not wrap with the wire phrase field");
}

// Held Beat clocks are corrected once per 16-beat measure, not on every beat.
void beat_clock_publishes_only_on_measure_downbeat() {
  expect(isTubesMeasureDownbeat(0), "initial beat 1 was not a downbeat");
  expect(isTubesMeasureDownbeat((42U << TUBES_BEAT_FRAME_PHRASE_SHIFT) | 0x00FF),
      "fractional time within beat 1 was not a downbeat");
  expect(!isTubesMeasureDownbeat((42U << TUBES_BEAT_FRAME_PHRASE_SHIFT) | 0x0100),
      "beat 2 was treated as a downbeat");
  expect(!isTubesMeasureDownbeat((42U << TUBES_BEAT_FRAME_PHRASE_SHIFT) | 0x0FFF),
      "beat 16 was treated as a downbeat");
  expect(isTubesMeasureDownbeat(43U << TUBES_BEAT_FRAME_PHRASE_SHIFT),
      "next measure beat 1 was not a downbeat");
}

// A follower still generates and retains a finite next schedule, but only a
// channel authority receives permission to publish the schedule it generated.
void followers_keep_speculative_channel_schedules() {
  uint8_t pickerCalls = 0;
  uint16_t followerPhrase = UINT16_MAX;
  bool followerMayPublish = scheduleSpeculativeChannelChange(
      100, followerPhrase, false, [&pickerCalls]() {
        pickerCalls++;
        return 7;
      });

  expect(pickerCalls == 1, "follower skipped speculative schedule generation");
  expect(followerPhrase == 107, "follower did not retain its speculative schedule");
  expect(!followerMayPublish, "follower received permission to publish its schedule");

  uint16_t leaderPhrase = UINT16_MAX;
  bool leaderMayPublish = scheduleSpeculativeChannelChange(
      100, leaderPhrase, true, []() { return 7; });
  expect(leaderPhrase == followerPhrase, "authority used different scheduling semantics");
  expect(leaderMayPublish, "authority could not publish its local schedule");
}

// Direct-neighbor beliefs are bounded in both count and lifetime, so a departed
// radio neighbor cannot remain a usable position anchor indefinitely.
void position_peers_expire() {
  V3PositionPeers peers;
  V3PositionAdvertisementPayload advertisement;
  advertisement.flags = V3PositionValid;
  peers.observe(100, -55, 1000, advertisement);
  expect(peers.entries()[0].valid, "position peer was not retained");
  peers.expire(1000 + V3_POSITION_PEER_TIMEOUT_MS);
  expect(!peers.entries()[0].valid, "stale position peer did not expire");
}

} // namespace

int main() {
  const std::array<std::pair<const char*, void (*)()>, 19> tests = {{
      {"wire validation rejects malformed lengths", wire_validation_rejects_malformed_lengths},
      {"topic authorities remain independent", topic_authorities_remain_independent},
      {"projection marker distinguishes master output", projection_marker_distinguishes_master_output},
      {"gen1 Device IDs always outrank gen0", gen1_device_ids_always_outrank_gen0},
      {"runtime claims before publishing state", runtime_claims_before_publishing_state},
      {"gradient palette expands atomically", gradient_palette_expands_atomically},
      {"Palette expansion matches WLED hard stops", palette_expansion_matches_wled_hard_stops},
      {"Palette expansion matches WLED fixed-point rounding", palette_expansion_matches_wled_fixed_point_rounding},
      {"Palette channel carries full definition and fallback", palette_channel_carries_full_definition_and_fallback},
      {"variable Palette snapshot is atomic", variable_palette_snapshot_is_atomic},
      {"raw Palette snapshot preserves source stops", raw_palette_snapshot_preserves_source_stops},
      {"variable Pattern snapshot preserves program and fallback", variable_pattern_snapshot_preserves_program_and_fallback},
      {"Beat snapshot carries authoritative chance", beat_snapshot_carries_authoritative_chance},
      {"delayed Pattern snapshot promotes next", delayed_pattern_snapshot_promotes_next},
      {"modern source recognizes both channel envelopes", modern_source_recognizes_both_channel_envelopes},
      {"channel operations schedule on phrase boundaries", channel_operations_schedule_on_phrase_boundaries},
      {"Beat clock publishes only on measure downbeat", beat_clock_publishes_only_on_measure_downbeat},
      {"followers keep speculative channel schedules", followers_keep_speculative_channel_schedules},
      {"position peers expire", position_peers_expire},
  }};

  for (const auto& test : tests) {
    try {
      test.second();
      std::cout << "PASS: " << test.first << '\n';
    } catch (const std::exception& error) {
      std::cerr << "FAIL: " << test.first << ": " << error.what() << '\n';
      return 1;
    }
  }
  return 0;
}

// AI: end
