import assert from 'node:assert/strict';
import crypto from 'node:crypto';
import fs from 'node:fs';
import path from 'node:path';
import test from 'node:test';
import {fileURLToPath} from 'node:url';

import {loadContract} from './update-contract/update-contract.mjs';

// AI: below section was generated by an AI
const root = path.resolve(path.dirname(fileURLToPath(import.meta.url)), '..');
const manifestPath = path.join(root, 'migration-fixtures/manifest.json');

function sha256(file) {
  return crypto.createHash('sha256').update(fs.readFileSync(file)).digest('hex');
}

test('Athom C3 migration fixture is byte-exact and admitted only to its compiled target', () => {
  const manifest = JSON.parse(fs.readFileSync(manifestPath, 'utf8'));
  const fixture = manifest.fixtures.find(item => item.id === 'tubes-v14-athom-c3');
  assert.ok(fixture);
  assert.equal(fixture.hardwareEvidence, 'exact-athom-c3-compiled-target-contract');
  assert.equal(fixture.source.baseCommit, '0987e2665e144312f982a2363312e7f847a427eb');
  assert.match(fixture.source.buildSourceState, /commit 2 generated C3 contract projection/);

  const fixturePath = path.join(root, fixture.artifact.path);
  const bytes = fs.readFileSync(fixturePath);
  assert.equal(bytes.length, fixture.artifact.sizeBytes);
  assert.equal(sha256(fixturePath), fixture.artifact.sha256);

  const contract = loadContract();
  const c3Target = contract.targets.find(item => item.id === 'athom-c3-tubes');
  const otaArtifact = contract.artifacts.find(item => item.id === 'athom-c3-v14-ota-application');
  assert.ok(c3Target && otaArtifact);
  assert.equal(otaArtifact.targetId, c3Target.id);
  assert.equal(otaArtifact.sha256, fixture.artifact.sha256);
  assert.equal(otaArtifact.lengthBytes, fixture.artifact.sizeBytes);
  assert.ok(c3Target.partition.otaSlots.every(slot => otaArtifact.lengthBytes <= slot.sizeBytes));

  const dig2go = contract.targets.find(item => item.id === 'quinled-dig2go');
  assert.notEqual(otaArtifact.targetId, dig2go.id);
  assert.notEqual(c3Target.hardwareFamily, dig2go.hardwareFamily);
  assert.notEqual(c3Target.chipFamily, dig2go.chipFamily);
});
// AI: end
