import assert from 'node:assert/strict';
import crypto from 'node:crypto';
import fs from 'node:fs';
import path from 'node:path';
import test from 'node:test';
import {fileURLToPath} from 'node:url';

import {loadContract} from './update-contract/update-contract.mjs';

// AI: below section was generated by an AI
const root = path.resolve(path.dirname(fileURLToPath(import.meta.url)), '..');

function sha256(file) {
  return crypto.createHash('sha256').update(fs.readFileSync(file)).digest('hex');
}

// The migration fixture and OTA contract must identify the same exact image
// while retaining the target-only, physically unproven hardware boundary.
test('Waveshare S3 migration fixture is target-only and byte-exact', () => {
  const manifest = JSON.parse(fs.readFileSync(path.join(root, 'migration-fixtures/manifest.json'), 'utf8'));
  const fixture = manifest.fixtures.find(item => item.id === 'tubes-v14-waveshare-s3-target');
  assert.ok(fixture);
  assert.equal(fixture.hardwareEvidence, 'exact-waveshare-s3-compiled-target-contract');
  assert.equal(fixture.source.environment, 'waveshare_s3_tubes_target');
  assert.equal(fixture.source.releaseIdentity, 'WAVESHARE_S3_TUBES_TARGET');

  const fixturePath = path.join(root, fixture.artifact.path);
  assert.equal(fs.statSync(fixturePath).size, fixture.artifact.sizeBytes);
  assert.equal(sha256(fixturePath), fixture.artifact.sha256);

  const contract = loadContract();
  const target = contract.targets.find(item => item.id === 'waveshare-s3-tubes-remote');
  const ota = contract.artifacts.find(item => item.id === 'waveshare-s3-v14-ota-application');
  assert.ok(target && ota);
  assert.equal(ota.targetId, target.id);
  assert.equal(ota.lengthBytes, fixture.artifact.sizeBytes);
  assert.equal(ota.sha256, fixture.artifact.sha256);
  assert.ok(target.partition.otaSlots.every(slot => ota.lengthBytes <= slot.sizeBytes));
  assert.equal(target.hardwareAcceptance, 'unproven');
});
// AI: end
