#include <cmath>
#include <cstdint>
#include <cstdio>
#include <cstdlib>

#include "../usermods/Tubes/tempo_tracker.h"
#include "../usermods/Tubes/rubber_band_beat_clock.h"

// AI: below section was generated by an AI

class SpectrumFixture {
  public:
    explicit SpectrumFixture(uint32_t seed = 1) : randomState(seed) {}

    // Produces the smoothed 16-band frames that Tubes receives from AudioReactive.
    void frame(float seconds, float bpm, uint8_t* spectrum, bool percussion = true,
        bool lowFrequencyKick = true) {
      float raw[TempoTracker::SPECTRUM_BINS];
      for (uint8_t bin = 0; bin < TempoTracker::SPECTRUM_BINS; bin++) {
        raw[bin] = 20.0f + noise(1.5f);
        if (bin >= 3 && bin <= 11)
          raw[bin] += 28.0f + 12.0f * sinf(seconds * (0.3f + bin * 0.01f));
      }

      if (percussion) {
        uint32_t beat = uint32_t(floorf(seconds * bpm / 60.0f));
        bool beatStarts = beat != previousBeat;
        if (beatStarts) {
          if (lowFrequencyKick) {
            raw[0] += 150.0f;
            raw[1] += 220.0f;
            raw[2] += 165.0f;
          }
          if (!lowFrequencyKick || (beat & 1U))
            for (uint8_t bin = 9; bin <= 13; bin++) raw[bin] += 95.0f;
        }
        previousBeat = beat;

        if (lowFrequencyKick) {
          uint32_t halfBeat = uint32_t(floorf(seconds * bpm / 30.0f));
          if (halfBeat != previousHalfBeat)
            for (uint8_t bin = 12; bin < TempoTracker::SPECTRUM_BINS; bin++) raw[bin] += 42.0f;
          previousHalfBeat = halfBeat;
        }
      }

      for (uint8_t bin = 0; bin < TempoTracker::SPECTRUM_BINS; bin++) {
        float coefficient = raw[bin] > smoothed[bin] ? 0.75f : 0.17f;
        smoothed[bin] += (raw[bin] - smoothed[bin]) * coefficient;
        float bounded = fminf(255.0f, fmaxf(0.0f, smoothed[bin]));
        spectrum[bin] = uint8_t(bounded + 0.5f);
      }
    }

  private:
    uint32_t randomState;
    uint32_t previousBeat = UINT32_MAX;
    uint32_t previousHalfBeat = UINT32_MAX;
    float smoothed[TempoTracker::SPECTRUM_BINS] = {0.0f};

    float noise(float amplitude) {
      randomState = randomState * 1664525U + 1013904223U;
      return (float(randomState >> 16) / 65535.0f - 0.5f) * amplitude;
    }
};

static TempoEstimate track(float bpm, float seconds, bool percussion = true) {
  TempoTracker tracker;
  SpectrumFixture fixture;
  uint8_t spectrum[TempoTracker::SPECTRUM_BINS];
  uint32_t frames = uint32_t(seconds * TempoTracker::SPECTRUM_FRAMES_PER_SECOND);
  for (uint32_t frame = 0; frame < frames; frame++) {
    float at = frame / TempoTracker::SPECTRUM_FRAMES_PER_SECOND;
    fixture.frame(at, bpm, spectrum, percussion);
    tracker.addSpectrum(spectrum);
  }
  return tracker.currentEstimate();
}

static TempoEstimate trackSnareMetronome(float bpm, uint32_t frames) {
  TempoTracker tracker;
  SpectrumFixture fixture;
  uint8_t spectrum[TempoTracker::SPECTRUM_BINS];
  for (uint32_t frame = 0; frame < frames; frame++) {
    float at = frame / TempoTracker::SPECTRUM_FRAMES_PER_SECOND;
    fixture.frame(at, bpm, spectrum, true, false);
    uint32_t timestampUs = uint32_t(at * 1000000.0f + 0.5f);
    tracker.addSpectrumAt(spectrum, timestampUs);
  }
  return tracker.currentEstimate();
}

// Models the pre-visualization FFT export: a click can land outside the kick and
// snare groups, retain floating-point magnitude, and still provide exact timing.
static TempoEstimate trackRawMidbandMetronome(float bpm, float seconds) {
  TempoTracker tracker;
  float spectrum[TempoTracker::SPECTRUM_BINS] = {0.0f};
  uint32_t previousBeat = UINT32_MAX;
  uint32_t frames = uint32_t(seconds * TempoTracker::SPECTRUM_FRAMES_PER_SECOND);
  for (uint32_t frame = 0; frame < frames; frame++) {
    float at = frame / TempoTracker::SPECTRUM_FRAMES_PER_SECOND;
    for (uint8_t bin = 0; bin < TempoTracker::SPECTRUM_BINS; bin++)
      spectrum[bin] = 18.0f + float((frame * 13U + bin * 7U) % 5U);
    uint32_t beat = uint32_t(floorf(at * bpm / 60.0f));
    if (beat != previousBeat) {
      spectrum[6] += 1850.0f;
      spectrum[7] += 900.0f;
    }
    previousBeat = beat;
    tracker.addSpectrumAt(spectrum, uint32_t(at * 1000000.0f + 0.5f));
  }
  return tracker.currentEstimate();
}

// Gives every second kick extra energy, the common pattern that can make a
// 160-BPM pulse look like a strong 80-BPM autocorrelation candidate.
static TempoEstimate trackHalfTempoBait(float bpm, float seconds) {
  TempoTracker tracker;
  float spectrum[TempoTracker::SPECTRUM_BINS] = {0.0f};
  uint32_t previousBeat = UINT32_MAX;
  uint32_t frames = uint32_t(seconds * TempoTracker::SPECTRUM_FRAMES_PER_SECOND);
  for (uint32_t frame = 0; frame < frames; frame++) {
    float at = frame / TempoTracker::SPECTRUM_FRAMES_PER_SECOND;
    for (uint8_t bin = 0; bin < TempoTracker::SPECTRUM_BINS; bin++)
      spectrum[bin] = 16.0f;
    uint32_t beat = uint32_t(floorf(at * bpm / 60.0f));
    if (beat != previousBeat) {
      float strength = beat & 1U ? 900.0f : 1800.0f;
      spectrum[0] += strength * 0.7f;
      spectrum[1] += strength;
      spectrum[2] += strength * 0.8f;
    }
    previousBeat = beat;
    tracker.addSpectrumAt(spectrum, uint32_t(at * 1000000.0f + 0.5f));
  }
  return tracker.currentEstimate();
}

// Produces a conventional four-beat dance pattern with a stronger, broader
// first beat so the complete FFT-to-tempo path must recover bar position.
static TempoEstimate trackBarAccented(float bpm, float seconds) {
  TempoTracker tracker;
  float spectrum[TempoTracker::SPECTRUM_BINS] = {0.0f};
  uint32_t previousBeat = UINT32_MAX;
  uint32_t frames = uint32_t(seconds * TempoTracker::SPECTRUM_FRAMES_PER_SECOND);
  for (uint32_t frame = 0; frame < frames; frame++) {
    float at = frame / TempoTracker::SPECTRUM_FRAMES_PER_SECOND;
    for (uint8_t bin = 0; bin < TempoTracker::SPECTRUM_BINS; bin++)
      spectrum[bin] = 18.0f + float((frame + bin * 3U) % 4U);
    uint32_t beat = uint32_t(floorf(at * bpm / 60.0f));
    if (beat != previousBeat) {
      uint8_t beatInBar = beat & 3U;
      if (beatInBar == 0) {
        for (uint8_t bin = 0; bin < TempoTracker::SPECTRUM_BINS; bin++)
          spectrum[bin] += 500.0f;
        spectrum[0] += 900.0f;
        spectrum[1] += 1400.0f;
        spectrum[2] += 1000.0f;
      } else if (beatInBar == 2) {
        spectrum[0] += 650.0f;
        spectrum[1] += 1000.0f;
        spectrum[2] += 750.0f;
      } else {
        for (uint8_t bin = 9; bin <= 13; bin++)
          spectrum[bin] += 850.0f;
      }
    }
    previousBeat = beat;
    tracker.addSpectrumAt(spectrum, uint32_t(at * 1000000.0f + 0.5f));
  }
  return tracker.currentEstimate();
}

// Replays the short irregular burst observed on hardware after a long silence.
static TempoEstimate trackIrregularStartupBurst() {
  constexpr float events[] = {6.000f, 6.719f, 7.276f, 7.554f, 7.762f, 7.947f};
  TempoTracker tracker;
  float spectrum[TempoTracker::SPECTRUM_BINS] = {0.0f};
  uint8_t nextEvent = 0;
  uint32_t frames = uint32_t(14.0f * TempoTracker::SPECTRUM_FRAMES_PER_SECOND);
  for (uint32_t frame = 0; frame < frames; frame++) {
    float at = frame / TempoTracker::SPECTRUM_FRAMES_PER_SECOND;
    for (uint8_t bin = 0; bin < TempoTracker::SPECTRUM_BINS; bin++)
      spectrum[bin] = 12.0f;
    if (nextEvent < sizeof(events) / sizeof(events[0])
        && at >= events[nextEvent]) {
      spectrum[6] = 1600.0f;
      spectrum[10] = 900.0f;
      nextEvent++;
    }
    tracker.addSpectrumAt(spectrum, uint32_t(at * 1000000.0f + 0.5f));
  }
  return tracker.currentEstimate();
}

static void requireTempo(const char* scenario, float expectedBpm, const TempoEstimate& estimate, float tolerance) {
  float actualBpm = estimate.bpmQ8 / 256.0f;
  if (!estimate.locked || fabsf(actualBpm - expectedBpm) > tolerance) {
    fprintf(stderr, "%s: expected %.1f BPM, got lock=%d bpm=%.2f confidence=%u\n",
        scenario, expectedBpm, estimate.locked, actualBpm, estimate.confidence);
    exit(1);
  }
}

// Proves microphone lock establishes beat 1 without restarting phrase numbering.
static void requireBeatOneAlignment() {
  TempoEstimate estimate;
  estimate.beatPhase = 73;
  uint32_t currentFrame = (27U << 12) | (11U << 8) | 201U;
  uint32_t expectedFrame = (27U << 12) | 73U;

  uint32_t alignedFrame = estimate.beatOneFrame(currentFrame);

  if (alignedFrame != expectedFrame) {
    fprintf(stderr, "beat-one alignment: expected frame %u, got %u\n",
        expectedFrame, alignedFrame);
    exit(1);
  }
}

// Bar alignment changes the integer beat modulo four while retaining the
// measured sub-beat phase used by the rubber-band clock.
static void requireNearestBarAlignment() {
  TempoEstimate estimate;
  estimate.beatPhase = 73;
  estimate.beatInBar = 0;
  uint32_t currentFrame = (27U << 12) | (11U << 8) | 201U;
  uint32_t expectedFrame = (27U << 12) | (12U << 8) | 73U;

  uint32_t alignedFrame = estimate.nearestBarFrame(currentFrame);
  if (alignedFrame != expectedFrame) {
    fprintf(stderr, "bar alignment: expected frame %u, got %u\n",
        expectedFrame, alignedFrame);
    exit(1);
  }

  RubberBandBeatClock clock;
  if (!clock.reset(120U << 8, currentFrame)
      || !clock.setGoal(120U << 8, alignedFrame)) {
    fprintf(stderr, "bar alignment: rubber-band clock rejected a valid goal\n");
    exit(1);
  }
  if (clock.frame() != currentFrame) {
    fprintf(stderr, "bar alignment: setting the goal jumped the running frame\n");
    exit(1);
  }
  uint32_t previousFrame = clock.frame();
  for (uint16_t update = 0; update < 800 && clock.phaseError(); update++) {
    clock.advance(100000);
    if (clock.frame() < previousFrame) {
      fprintf(stderr, "bar alignment: correction moved the running frame backward\n");
      exit(1);
    }
    previousFrame = clock.frame();
  }
  if (clock.phaseError()) {
    fprintf(stderr, "bar alignment: correction did not converge, error=%d\n",
        clock.phaseError());
    exit(1);
  }
}

static uint8_t circularPhaseError(uint8_t left, uint8_t right) {
  uint8_t difference = left > right ? left - right : right - left;
  return difference > 128 ? 256 - difference : difference;
}

int main() {
  requireBeatOneAlignment();
  requireNearestBarAlignment();

  // A plain four-on-the-floor kick must establish the primary use-case quickly.
  requireTempo("steady 120 BPM", 120.0f, track(120.0f, 12.0f), 1.5f);

  // Offbeat hats, alternating snares, a sustained pad, and noise must not pull
  // the estimate away from the kick tempo used by electronic dance music.
  requireTempo("layered 128 BPM", 128.0f, track(128.0f, 14.0f), 1.5f);
  requireTempo("slow 90 BPM", 90.0f, track(90.0f, 14.0f), 1.5f);
  requireTempo("fast 160 BPM", 160.0f, track(160.0f, 14.0f), 2.0f);
  requireTempo("120 BPM half-tempo bait", 120.0f,
      trackHalfTempoBait(120.0f, 30.0f), 1.0f);
  requireTempo("160 BPM half-tempo bait", 160.0f,
      trackHalfTempoBait(160.0f, 30.0f), 1.0f);
  requireTempo("genuine 60 BPM", 60.0f, track(60.0f, 24.0f), 1.5f);

  TempoEstimate bar = trackBarAccented(120.0f, 32.0f);
  requireTempo("bar-accented 120 BPM", 120.0f, bar, 1.0f);
  if (!bar.barTracked) {
    fprintf(stderr, "bar-accented 120 BPM: expected a downbeat lock\n");
    return 1;
  }
  if (bar.beatInBar != 3) {
    fprintf(stderr, "bar-accented 120 BPM: expected beat 4, got beat %u\n",
        bar.beatInBar + 1);
    return 1;
  }

  // A high-frequency metronome must refine both frequency and phase without a kick.
  constexpr uint32_t metronomeFrames = 2585; // Leaves the last frame on an estimator scan.
  TempoEstimate metronome = trackSnareMetronome(130.0f, metronomeFrames);
  requireTempo("snare-only 130 BPM", 130.0f, metronome, 0.15f);
  float metronomeTime = (metronomeFrames - 1) / TempoTracker::SPECTRUM_FRAMES_PER_SECOND;
  uint8_t expectedPhase = uint8_t(fmodf(metronomeTime * 130.0f / 60.0f, 1.0f) * 255.0f + 0.5f);
  if (!metronome.phaseTracked || metronome.timingEvents < 20
      || circularPhaseError(metronome.beatPhase, expectedPhase) > 14) {
    fprintf(stderr,
        "snare-only phase: expected phase %u, got phase=%u bpm=%.2f tracked=%d events=%u error=%dms\n",
        expectedPhase, metronome.beatPhase, metronome.bpmQ8 / 256.0f,
        metronome.phaseTracked, metronome.timingEvents, metronome.phaseErrorMs);
    return 1;
  }

  // The known physical failure case is a regular 124 BPM click whose strongest
  // energy need not fall in the hand-selected kick or snare bins.
  requireTempo("raw midband 124 BPM", 124.0f,
      trackRawMidbandMetronome(124.0f, 60.0f), 0.15f);

  if (trackIrregularStartupBurst().locked) {
    fprintf(stderr, "irregular startup burst: expected no tempo lock\n");
    return 1;
  }

  // Smooth broad-band movement has energy but no percussive crest, so it must
  // leave the held clock untouched instead of inventing a tempo.
  TempoEstimate pad = track(120.0f, 14.0f, false);
  if (pad.locked) {
    fprintf(stderr, "sustained pad: expected no lock, got %.2f BPM\n", pad.bpmQ8 / 256.0f);
    return 1;
  }

  // A short observation gap preserves elapsed time and resumes without turning
  // the cross-gap spectrum difference into a fake beat.
  TempoTracker gapTracker;
  SpectrumFixture gapFixture;
  uint8_t spectrum[TempoTracker::SPECTRUM_BINS];
  for (uint32_t frame = 0; frame < 620; frame++) {
    float at = frame / TempoTracker::SPECTRUM_FRAMES_PER_SECOND;
    gapFixture.frame(at, 135.0f, spectrum);
    if (frame == 240)
      gapTracker.addSpectrum(spectrum, 3);
    else
      gapTracker.addSpectrum(spectrum);
  }
  requireTempo("135 BPM with dropped frames", 135.0f, gapTracker.currentEstimate(), 1.5f);

  // A new sustained tempo must eventually replace the decaying old history rather
  // than leaving the Beat owner permanently latched to its first song.
  TempoTracker changingTracker;
  SpectrumFixture changingFixture;
  for (uint32_t frame = 0; frame < 1120; frame++) {
    float at = frame / TempoTracker::SPECTRUM_FRAMES_PER_SECOND;
    float bpm = at < 12.0f ? 120.0f : 135.0f;
    changingFixture.frame(at, bpm, spectrum);
    changingTracker.addSpectrum(spectrum);
  }
  requireTempo("120 to 135 BPM transition", 135.0f, changingTracker.currentEstimate(), 1.5f);

  // Once percussion disappears, stale history must expire and withdraw lock. The
  // controller deliberately keeps free-running at the last good BPM afterward.
  TempoTracker staleTracker;
  SpectrumFixture staleFixture;
  for (uint32_t frame = 0; frame < 1120; frame++) {
    float at = frame / TempoTracker::SPECTRUM_FRAMES_PER_SECOND;
    staleFixture.frame(at, 128.0f, spectrum, at < 12.0f);
    staleTracker.addSpectrum(spectrum);
  }
  if (staleTracker.currentEstimate().locked) {
    fprintf(stderr, "stale percussion: expected the estimate to unlock\n");
    return 1;
  }

  printf("tempo tracker scenarios passed\n");
  return 0;
}

// AI: end
